// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO attendance_logs (employee_id, date, check_in, check_out, work_hours, status, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, employee_id, date, check_in, check_out, work_hours, status, note, created_at
`

type CreateAttendanceParams struct {
	EmployeeID pgtype.UUID    `json:"employee_id"`
	Date       pgtype.Date    `json:"date"`
	CheckIn    string         `json:"check_in"`
	CheckOut   string         `json:"check_out"`
	WorkHours  pgtype.Numeric `json:"work_hours"`
	Status     string         `json:"status"`
	Note       string         `json:"note"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, createAttendance,
		arg.EmployeeID,
		arg.Date,
		arg.CheckIn,
		arg.CheckOut,
		arg.WorkHours,
		arg.Status,
		arg.Note,
	)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.WorkHours,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttendance = `-- name: DeleteAttendance :exec
DELETE FROM attendance_logs WHERE id = $1
`

func (q *Queries) DeleteAttendance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttendance, id)
	return err
}

const getAttendanceByID = `-- name: GetAttendanceByID :one
SELECT id, employee_id, date, check_in, check_out, work_hours, status, note, created_at FROM attendance_logs WHERE id = $1
`

func (q *Queries) GetAttendanceByID(ctx context.Context, id pgtype.UUID) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, getAttendanceByID, id)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.WorkHours,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listAttendanceByMonth = `-- name: ListAttendanceByMonth :many
SELECT a.id, a.employee_id, a.date, a.check_in, a.check_out, a.work_hours, a.status, a.note, a.created_at, e.full_name AS employee_name
FROM attendance_logs a
JOIN employees e ON e.id = a.employee_id
WHERE date_trunc('month', a.date) = date_trunc('month', $1::date)
ORDER BY a.date DESC, e.full_name ASC
`

type ListAttendanceByMonthRow struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Date         pgtype.Date        `json:"date"`
	CheckIn      string             `json:"check_in"`
	CheckOut     string             `json:"check_out"`
	WorkHours    pgtype.Numeric     `json:"work_hours"`
	Status       string             `json:"status"`
	Note         string             `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) ListAttendanceByMonth(ctx context.Context, dollar_1 pgtype.Date) ([]ListAttendanceByMonthRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceByMonth, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttendanceByMonthRow
	for rows.Next() {
		var i ListAttendanceByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Date,
			&i.CheckIn,
			&i.CheckOut,
			&i.WorkHours,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendance = `-- name: UpdateAttendance :one
UPDATE attendance_logs
SET check_in = $2, check_out = $3, work_hours = $4, status = $5, note = $6
WHERE id = $1
RETURNING id, employee_id, date, check_in, check_out, work_hours, status, note, created_at
`

type UpdateAttendanceParams struct {
	ID        pgtype.UUID    `json:"id"`
	CheckIn   string         `json:"check_in"`
	CheckOut  string         `json:"check_out"`
	WorkHours pgtype.Numeric `json:"work_hours"`
	Status    string         `json:"status"`
	Note      string         `json:"note"`
}

func (q *Queries) UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, updateAttendance,
		arg.ID,
		arg.CheckIn,
		arg.CheckOut,
		arg.WorkHours,
		arg.Status,
		arg.Note,
	)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Date,
		&i.CheckIn,
		&i.CheckOut,
		&i.WorkHours,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
