// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_control.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveBudgetAdjustment = `-- name: ApproveBudgetAdjustment :one
UPDATE project_budget_adjustments SET status = 'approved', approved_by = $4, approved_at = now()
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'draft'
RETURNING id, organization_id, project_id, budget_id, budget_line_id, amount, reason, status, created_by, approved_by, approved_at, created_at, updated_at
`

type ApproveBudgetAdjustmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	ApprovedBy     pgtype.UUID `json:"approved_by"`
}

// ApproveBudgetAdjustment/RejectBudgetAdjustment, status='draft' koşuluyla
// korunur -- eşzamanlı iki onay/redden yalnızca biri satır döndürür
// (project_change_orders'daki RespondChangeOrder ile AYNI ilke).
func (q *Queries) ApproveBudgetAdjustment(ctx context.Context, arg ApproveBudgetAdjustmentParams) (ProjectBudgetAdjustment, error) {
	row := q.db.QueryRow(ctx, approveBudgetAdjustment,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ApprovedBy,
	)
	var i ProjectBudgetAdjustment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.BudgetLineID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveOrganizationCostCode = `-- name: ArchiveOrganizationCostCode :execrows
UPDATE organization_cost_codes SET is_active = false WHERE id = $1 AND organization_id = $2
`

type ArchiveOrganizationCostCodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// ArchiveOrganizationCostCode, HARD DELETE DEĞİLDİR (spec: geçmiş
// bütçe/taahhüt/gider kayıtları referans veriyor olabilir) -- yalnızca
// is_active=false yapar; kod, mevcut kayıtlarda görünmeye devam eder,
// yalnızca YENİ seçim listelerinden (bkz. ListOrganizationCostCodes'un
// çağıran tarafta is_active filtrelemesi) çıkar.
func (q *Queries) ArchiveOrganizationCostCode(ctx context.Context, arg ArchiveOrganizationCostCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveOrganizationCostCode, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveWBSNode = `-- name: ArchiveWBSNode :execrows
UPDATE project_wbs_nodes SET is_active = false WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type ArchiveWBSNodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) ArchiveWBSNode(ctx context.Context, arg ArchiveWBSNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveWBSNode, arg.ID, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const baselineProjectBudget = `-- name: BaselineProjectBudget :one
UPDATE project_budgets
SET status = 'baselined', baselined_at = now(), baselined_by = $4, version = version + 1
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'draft'
RETURNING id, organization_id, project_id, currency, status, version, created_by, created_at, updated_at, baselined_at, baselined_by
`

type BaselineProjectBudgetParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	BaselinedBy    pgtype.UUID `json:"baselined_by"`
}

func (q *Queries) BaselineProjectBudget(ctx context.Context, arg BaselineProjectBudgetParams) (ProjectBudget, error) {
	row := q.db.QueryRow(ctx, baselineProjectBudget,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BaselinedBy,
	)
	var i ProjectBudget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselinedAt,
		&i.BaselinedBy,
	)
	return i, err
}

const countActiveWBSChildren = `-- name: CountActiveWBSChildren :one
SELECT count(*)::bigint FROM project_wbs_nodes
WHERE parent_id = $1 AND organization_id = $2 AND project_id = $3 AND is_active = true
`

type CountActiveWBSChildrenParams struct {
	ParentID       pgtype.UUID `json:"parent_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// Arşivleme kapısı: aktif alt düğümü olan bir düğüm arşivlenmez (bkz.
// ArchiveWBSNode servis notu -- arşivden geri alma ucu olmadığı için
// alt ağacı sessizce arşivlemek geri döndürülemez olurdu).
func (q *Queries) CountActiveWBSChildren(ctx context.Context, arg CountActiveWBSChildrenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWBSChildren, arg.ParentID, arg.OrganizationID, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBudgetAdjustment = `-- name: CreateBudgetAdjustment :one

INSERT INTO project_budget_adjustments (organization_id, project_id, budget_id, budget_line_id, amount, reason, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, organization_id, project_id, budget_id, budget_line_id, amount, reason, status, created_by, approved_by, approved_at, created_at, updated_at
`

type CreateBudgetAdjustmentParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	BudgetID       pgtype.UUID    `json:"budget_id"`
	BudgetLineID   pgtype.UUID    `json:"budget_line_id"`
	Amount         pgtype.Numeric `json:"amount"`
	Reason         string         `json:"reason"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

// ============ Bütçe Revizyonları (Adjustments) ============
func (q *Queries) CreateBudgetAdjustment(ctx context.Context, arg CreateBudgetAdjustmentParams) (ProjectBudgetAdjustment, error) {
	row := q.db.QueryRow(ctx, createBudgetAdjustment,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BudgetID,
		arg.BudgetLineID,
		arg.Amount,
		arg.Reason,
		arg.CreatedBy,
	)
	var i ProjectBudgetAdjustment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.BudgetLineID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBudgetLine = `-- name: CreateBudgetLine :one

INSERT INTO project_budget_lines (
    organization_id, project_id, budget_id, wbs_node_id, cost_code_id,
    description, quantity, unit, unit_cost, original_amount, notes
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, organization_id, project_id, budget_id, wbs_node_id, cost_code_id, description, quantity, unit, unit_cost, original_amount, notes, created_at, updated_at
`

type CreateBudgetLineParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	BudgetID       pgtype.UUID    `json:"budget_id"`
	WbsNodeID      pgtype.UUID    `json:"wbs_node_id"`
	CostCodeID     pgtype.UUID    `json:"cost_code_id"`
	Description    string         `json:"description"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	UnitCost       pgtype.Numeric `json:"unit_cost"`
	OriginalAmount pgtype.Numeric `json:"original_amount"`
	Notes          string         `json:"notes"`
}

// ============ Bütçe Kalemleri ============
func (q *Queries) CreateBudgetLine(ctx context.Context, arg CreateBudgetLineParams) (ProjectBudgetLine, error) {
	row := q.db.QueryRow(ctx, createBudgetLine,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BudgetID,
		arg.WbsNodeID,
		arg.CostCodeID,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitCost,
		arg.OriginalAmount,
		arg.Notes,
	)
	var i ProjectBudgetLine
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.WbsNodeID,
		&i.CostCodeID,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitCost,
		&i.OriginalAmount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommitment = `-- name: CreateCommitment :one

INSERT INTO project_commitments (
    organization_id, project_id, budget_line_id, cost_code_id, source_type,
    description, committed_amount, currency, committed_at, idempotency_key, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, organization_id, project_id, budget_line_id, cost_code_id, source_type, source_id, description, committed_amount, currency, status, committed_at, idempotency_key, created_by, voided_at, voided_by, void_reason, created_at, updated_at
`

type CreateCommitmentParams struct {
	OrganizationID  pgtype.UUID    `json:"organization_id"`
	ProjectID       pgtype.UUID    `json:"project_id"`
	BudgetLineID    pgtype.UUID    `json:"budget_line_id"`
	CostCodeID      pgtype.UUID    `json:"cost_code_id"`
	SourceType      string         `json:"source_type"`
	Description     string         `json:"description"`
	CommittedAmount pgtype.Numeric `json:"committed_amount"`
	Currency        string         `json:"currency"`
	CommittedAt     pgtype.Date    `json:"committed_at"`
	IdempotencyKey  *string        `json:"idempotency_key"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

// ============ Taahhütler (Commitments) ============
func (q *Queries) CreateCommitment(ctx context.Context, arg CreateCommitmentParams) (ProjectCommitment, error) {
	row := q.db.QueryRow(ctx, createCommitment,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BudgetLineID,
		arg.CostCodeID,
		arg.SourceType,
		arg.Description,
		arg.CommittedAmount,
		arg.Currency,
		arg.CommittedAt,
		arg.IdempotencyKey,
		arg.CreatedBy,
	)
	var i ProjectCommitment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetLineID,
		&i.CostCodeID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CommittedAmount,
		&i.Currency,
		&i.Status,
		&i.CommittedAt,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommitmentFromSource = `-- name: CreateCommitmentFromSource :one

INSERT INTO project_commitments (
    organization_id, project_id, budget_line_id, cost_code_id, source_type, source_id,
    description, committed_amount, currency, committed_at, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, organization_id, project_id, budget_line_id, cost_code_id, source_type, source_id, description, committed_amount, currency, status, committed_at, idempotency_key, created_by, voided_at, voided_by, void_reason, created_at, updated_at
`

type CreateCommitmentFromSourceParams struct {
	OrganizationID  pgtype.UUID    `json:"organization_id"`
	ProjectID       pgtype.UUID    `json:"project_id"`
	BudgetLineID    pgtype.UUID    `json:"budget_line_id"`
	CostCodeID      pgtype.UUID    `json:"cost_code_id"`
	SourceType      string         `json:"source_type"`
	SourceID        pgtype.UUID    `json:"source_id"`
	Description     string         `json:"description"`
	CommittedAmount pgtype.Numeric `json:"committed_amount"`
	Currency        string         `json:"currency"`
	CommittedAt     pgtype.Date    `json:"committed_at"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

// Sprint 4 -- Procurement entegrasyonu. CreateCommitment (yukarı,
// MANUEL taahhütler için) İLE KARIŞTIRILMAMALI: bu sorgu source_type/
// source_id'yi AÇIKÇA kabul eder, yalnızca approved PO onay akışından
// (bkz. project_purchase_order_service.go) çağrılır -- hiçbir HTTP
// ucu bunu doğrudan istemciye AÇMAZ.
func (q *Queries) CreateCommitmentFromSource(ctx context.Context, arg CreateCommitmentFromSourceParams) (ProjectCommitment, error) {
	row := q.db.QueryRow(ctx, createCommitmentFromSource,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BudgetLineID,
		arg.CostCodeID,
		arg.SourceType,
		arg.SourceID,
		arg.Description,
		arg.CommittedAmount,
		arg.Currency,
		arg.CommittedAt,
		arg.CreatedBy,
	)
	var i ProjectCommitment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetLineID,
		&i.CostCodeID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CommittedAmount,
		&i.Currency,
		&i.Status,
		&i.CommittedAt,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationCostCode = `-- name: CreateOrganizationCostCode :one

INSERT INTO organization_cost_codes (organization_id, code, name, description, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, code, name, description, category, is_active, created_at, updated_at
`

type CreateOrganizationCostCodeParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	Category       string      `json:"category"`
}

// ============ Organizasyon Maliyet Kodları ============
func (q *Queries) CreateOrganizationCostCode(ctx context.Context, arg CreateOrganizationCostCodeParams) (OrganizationCostCode, error) {
	row := q.db.QueryRow(ctx, createOrganizationCostCode,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	var i OrganizationCostCode
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationEvent = `-- name: CreateOrganizationEvent :one


INSERT INTO organization_events (organization_id, event_type, user_id, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, event_type, user_id, metadata, created_at
`

type CreateOrganizationEventParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	EventType      string      `json:"event_type"`
	UserID         pgtype.UUID `json:"user_id"`
	Metadata       []byte      `json:"metadata"`
}

// ARVEND V2 — Sprint 2: WBS + Cost Codes + Project Budget + Cost Control.
// Formüller docs/cost-control.md'de belgelenmiştir. Bu dosyadaki
// ListCostControlLines ve GetProjectCostControlSummary AYNI CTE
// mantığını (satır satır maliyet/taahhüt/tahmin) kullanır -- proje
// toplamı, satır toplamlarının SQL SUM()'udur (spec: "Project total AYNI
// KURALLA aggregate edilmeli"), asla bağımsız bir formülle YENİDEN
// hesaplanmaz.
// ============ Organizasyon Olayları (org-seviyesi denetim) ============
func (q *Queries) CreateOrganizationEvent(ctx context.Context, arg CreateOrganizationEventParams) (OrganizationEvent, error) {
	row := q.db.QueryRow(ctx, createOrganizationEvent,
		arg.OrganizationID,
		arg.EventType,
		arg.UserID,
		arg.Metadata,
	)
	var i OrganizationEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventType,
		&i.UserID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectBudget = `-- name: CreateProjectBudget :one

INSERT INTO project_budgets (organization_id, project_id, currency, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, project_id, currency, status, version, created_by, created_at, updated_at, baselined_at, baselined_by
`

type CreateProjectBudgetParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Currency       string      `json:"currency"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// ============ Proje Bütçesi ============
func (q *Queries) CreateProjectBudget(ctx context.Context, arg CreateProjectBudgetParams) (ProjectBudget, error) {
	row := q.db.QueryRow(ctx, createProjectBudget,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Currency,
		arg.CreatedBy,
	)
	var i ProjectBudget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselinedAt,
		&i.BaselinedBy,
	)
	return i, err
}

const createWBSNode = `-- name: CreateWBSNode :one

INSERT INTO project_wbs_nodes (organization_id, project_id, parent_id, code, name, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, project_id, parent_id, code, name, sort_order, is_active, created_at, updated_at
`

type CreateWBSNodeParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	SortOrder      int32       `json:"sort_order"`
}

// ============ Proje WBS ============
func (q *Queries) CreateWBSNode(ctx context.Context, arg CreateWBSNodeParams) (ProjectWbsNode, error) {
	row := q.db.QueryRow(ctx, createWBSNode,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.SortOrder,
	)
	var i ProjectWbsNode
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudgetLine = `-- name: DeleteBudgetLine :execrows
DELETE FROM project_budget_lines WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type DeleteBudgetLineParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// DeleteBudgetLine, YALNIZCA draft (henüz baseline alınmamış) bütçenin
// kalemleri için kullanılır -- servis katmanı budget.status='draft'
// kontrolünü FOR UPDATE ile önce yapar (bkz. project_change_orders'daki
// requireOpenProject ile AYNI ilke).
func (q *Queries) DeleteBudgetLine(ctx context.Context, arg DeleteBudgetLineParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudgetLine, arg.ID, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBudgetAdjustmentForUpdate = `-- name: GetBudgetAdjustmentForUpdate :one
SELECT id, organization_id, project_id, budget_id, budget_line_id, amount, reason, status, created_by, approved_by, approved_at, created_at, updated_at FROM project_budget_adjustments WHERE id = $1 AND organization_id = $2 AND project_id = $3 FOR UPDATE
`

type GetBudgetAdjustmentForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetBudgetAdjustmentForUpdate(ctx context.Context, arg GetBudgetAdjustmentForUpdateParams) (ProjectBudgetAdjustment, error) {
	row := q.db.QueryRow(ctx, getBudgetAdjustmentForUpdate, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectBudgetAdjustment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.BudgetLineID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetLine = `-- name: GetBudgetLine :one
SELECT id, organization_id, project_id, budget_id, wbs_node_id, cost_code_id, description, quantity, unit, unit_cost, original_amount, notes, created_at, updated_at FROM project_budget_lines WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetBudgetLineParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetBudgetLine(ctx context.Context, arg GetBudgetLineParams) (ProjectBudgetLine, error) {
	row := q.db.QueryRow(ctx, getBudgetLine, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectBudgetLine
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.WbsNodeID,
		&i.CostCodeID,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitCost,
		&i.OriginalAmount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommitment = `-- name: GetCommitment :one
SELECT id, organization_id, project_id, budget_line_id, cost_code_id, source_type, source_id, description, committed_amount, currency, status, committed_at, idempotency_key, created_by, voided_at, voided_by, void_reason, created_at, updated_at FROM project_commitments WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetCommitmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetCommitment(ctx context.Context, arg GetCommitmentParams) (ProjectCommitment, error) {
	row := q.db.QueryRow(ctx, getCommitment, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectCommitment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetLineID,
		&i.CostCodeID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CommittedAmount,
		&i.Currency,
		&i.Status,
		&i.CommittedAt,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommitmentByIdempotencyKey = `-- name: GetCommitmentByIdempotencyKey :one
SELECT id, organization_id, project_id, budget_line_id, cost_code_id, source_type, source_id, description, committed_amount, currency, status, committed_at, idempotency_key, created_by, voided_at, voided_by, void_reason, created_at, updated_at FROM project_commitments WHERE project_id = $1 AND idempotency_key = $2
`

type GetCommitmentByIdempotencyKeyParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

func (q *Queries) GetCommitmentByIdempotencyKey(ctx context.Context, arg GetCommitmentByIdempotencyKeyParams) (ProjectCommitment, error) {
	row := q.db.QueryRow(ctx, getCommitmentByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i ProjectCommitment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetLineID,
		&i.CostCodeID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CommittedAmount,
		&i.Currency,
		&i.Status,
		&i.CommittedAt,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationCostCode = `-- name: GetOrganizationCostCode :one
SELECT id, organization_id, code, name, description, category, is_active, created_at, updated_at FROM organization_cost_codes WHERE id = $1 AND organization_id = $2
`

type GetOrganizationCostCodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetOrganizationCostCode(ctx context.Context, arg GetOrganizationCostCodeParams) (OrganizationCostCode, error) {
	row := q.db.QueryRow(ctx, getOrganizationCostCode, arg.ID, arg.OrganizationID)
	var i OrganizationCostCode
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBudget = `-- name: GetProjectBudget :one
SELECT id, organization_id, project_id, currency, status, version, created_by, created_at, updated_at, baselined_at, baselined_by FROM project_budgets WHERE project_id = $1 AND organization_id = $2
`

type GetProjectBudgetParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProjectBudget(ctx context.Context, arg GetProjectBudgetParams) (ProjectBudget, error) {
	row := q.db.QueryRow(ctx, getProjectBudget, arg.ProjectID, arg.OrganizationID)
	var i ProjectBudget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselinedAt,
		&i.BaselinedBy,
	)
	return i, err
}

const getProjectBudgetForUpdate = `-- name: GetProjectBudgetForUpdate :one
SELECT id, organization_id, project_id, currency, status, version, created_by, created_at, updated_at, baselined_at, baselined_by FROM project_budgets WHERE id = $1 AND organization_id = $2 AND project_id = $3 FOR UPDATE
`

type GetProjectBudgetForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// GetProjectBudgetForUpdate, satırı KİLİT ALTINDA okur -- baseline işlemi
// (project_change_orders'daki SendChangeOrder ile AYNI ilke) bunu
// kullanır, ardından status='draft' koşuluyla günceller; eşzamanlı iki
// "baseline al" isteğinden yalnızca biri satır döndürür.
func (q *Queries) GetProjectBudgetForUpdate(ctx context.Context, arg GetProjectBudgetForUpdateParams) (ProjectBudget, error) {
	row := q.db.QueryRow(ctx, getProjectBudgetForUpdate, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectBudget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselinedAt,
		&i.BaselinedBy,
	)
	return i, err
}

const getProjectCostControlSummary = `-- name: GetProjectCostControlSummary :one
WITH proj AS (
    SELECT pr.contract_amount, pr.currency FROM projects pr WHERE pr.id = $1 AND pr.organization_id = $2
),
co_effect AS (
    SELECT
        COALESCE(sum(grand_total) FILTER (WHERE change_type = 'addition' AND status = 'approved'), 0)::numeric(18,2) AS approved_additions,
        COALESCE(sum(grand_total) FILTER (WHERE change_type = 'deduction' AND status = 'approved'), 0)::numeric(18,2) AS approved_deductions
    FROM project_change_orders WHERE project_id = $1 AND organization_id = $2
),
current_value AS (
    SELECT (proj.contract_amount + co_effect.approved_additions - co_effect.approved_deductions)::numeric(18,2) AS total
    FROM proj, co_effect
),
lines AS (
    SELECT bl.id AS budget_line_id, bl.cost_code_id, bl.original_amount
    FROM project_budget_lines bl WHERE bl.project_id = $1 AND bl.organization_id = $2
),
adjustments AS (
    SELECT budget_line_id, COALESCE(sum(amount), 0)::numeric(18,2) AS total
    FROM project_budget_adjustments
    WHERE project_id = $1 AND organization_id = $2 AND status = 'approved'
    GROUP BY budget_line_id
),
single_line_codes AS (
    SELECT bl.cost_code_id, (array_agg(bl.id))[1] AS budget_line_id
    FROM project_budget_lines bl WHERE bl.project_id = $1 AND bl.organization_id = $2
    GROUP BY bl.cost_code_id
    HAVING count(*) = 1
),
committed_by_line AS (
    SELECT COALESCE(c.budget_line_id, slc.budget_line_id) AS budget_line_id,
        COALESCE(sum(c.committed_amount), 0)::numeric(18,2) AS total
    FROM project_commitments c
    LEFT JOIN single_line_codes slc ON c.budget_line_id IS NULL AND slc.cost_code_id = c.cost_code_id
    WHERE c.project_id = $1 AND c.organization_id = $2 AND c.status = 'active'
      AND COALESCE(c.budget_line_id, slc.budget_line_id) IS NOT NULL
    GROUP BY COALESCE(c.budget_line_id, slc.budget_line_id)
),
actual_by_line AS (
    SELECT COALESCE(e.budget_line_id, slc.budget_line_id) AS budget_line_id,
        COALESCE(sum(e.amount), 0)::numeric(18,2) AS total
    FROM project_expenses e
    LEFT JOIN single_line_codes slc ON e.budget_line_id IS NULL AND slc.cost_code_id = e.cost_code_id
    WHERE e.project_id = $1 AND e.organization_id = $2 AND e.voided_at IS NULL AND e.approval_status = 'approved'
      AND COALESCE(e.budget_line_id, slc.budget_line_id) IS NOT NULL
    GROUP BY COALESCE(e.budget_line_id, slc.budget_line_id)
),
forecast_by_line AS (
    SELECT budget_line_id, etc_amount FROM project_cost_forecasts WHERE project_id = $1 AND organization_id = $2
),
budgeted AS (
    SELECT
        l.original_amount,
        COALESCE(adj.total, 0)::numeric(18,2) AS approved_adjustments,
        (l.original_amount + COALESCE(adj.total, 0))::numeric(18,2) AS revised_budget,
        COALESCE(com.total, 0)::numeric(18,2) AS committed_cost,
        COALESCE(act.total, 0)::numeric(18,2) AS actual_cost,
        COALESCE(fc.etc_amount, GREATEST((l.original_amount + COALESCE(adj.total, 0)) - COALESCE(act.total, 0), 0))::numeric(18,2) AS etc_amount,
        (COALESCE(act.total, 0) + COALESCE(fc.etc_amount, GREATEST((l.original_amount + COALESCE(adj.total, 0)) - COALESCE(act.total, 0), 0)))::numeric(18,2) AS eac,
        ((l.original_amount + COALESCE(adj.total, 0)) - (COALESCE(act.total, 0) + COALESCE(fc.etc_amount, GREATEST((l.original_amount + COALESCE(adj.total, 0)) - COALESCE(act.total, 0), 0))))::numeric(18,2) AS variance
    FROM lines l
    LEFT JOIN adjustments adj ON adj.budget_line_id = l.budget_line_id
    LEFT JOIN committed_by_line com ON com.budget_line_id = l.budget_line_id
    LEFT JOIN actual_by_line act ON act.budget_line_id = l.budget_line_id
    LEFT JOIN forecast_by_line fc ON fc.budget_line_id = l.budget_line_id
),
unbudgeted_committed AS (
    SELECT c.cost_code_id, COALESCE(sum(c.committed_amount), 0)::numeric(18,2) AS total
    FROM project_commitments c
    WHERE c.project_id = $1 AND c.organization_id = $2 AND c.status = 'active' AND c.budget_line_id IS NULL
      AND NOT EXISTS (SELECT 1 FROM single_line_codes slc WHERE slc.cost_code_id = c.cost_code_id)
    GROUP BY c.cost_code_id
),
unbudgeted_actual AS (
    SELECT e.cost_code_id, COALESCE(sum(e.amount), 0)::numeric(18,2) AS total
    FROM project_expenses e
    WHERE e.project_id = $1 AND e.organization_id = $2 AND e.voided_at IS NULL AND e.approval_status = 'approved' AND e.budget_line_id IS NULL AND e.cost_code_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM single_line_codes slc WHERE slc.cost_code_id = e.cost_code_id)
    GROUP BY e.cost_code_id
),
unbudgeted_codes AS (
    SELECT cost_code_id FROM unbudgeted_committed
    UNION
    SELECT cost_code_id FROM unbudgeted_actual
),
unbudgeted AS (
    SELECT
        0::numeric(18,2) AS original_amount, 0::numeric(18,2) AS approved_adjustments, 0::numeric(18,2) AS revised_budget,
        COALESCE(ucom.total, 0)::numeric(18,2) AS committed_cost, COALESCE(uact.total, 0)::numeric(18,2) AS actual_cost,
        0::numeric(18,2) AS etc_amount, COALESCE(uact.total, 0)::numeric(18,2) AS eac, (0 - COALESCE(uact.total, 0))::numeric(18,2) AS variance
    FROM unbudgeted_codes uc
    LEFT JOIN unbudgeted_committed ucom ON ucom.cost_code_id = uc.cost_code_id
    LEFT JOIN unbudgeted_actual uact ON uact.cost_code_id = uc.cost_code_id
),
all_rows AS (
    SELECT original_amount, approved_adjustments, revised_budget, committed_cost, actual_cost, etc_amount, eac, variance FROM budgeted
    UNION ALL
    SELECT original_amount, approved_adjustments, revised_budget, committed_cost, actual_cost, etc_amount, eac, variance FROM unbudgeted
),
totals AS (
    SELECT
        COALESCE(sum(original_amount), 0)::numeric(18,2) AS original_budget,
        COALESCE(sum(approved_adjustments), 0)::numeric(18,2) AS approved_adjustments,
        COALESCE(sum(revised_budget), 0)::numeric(18,2) AS revised_budget,
        COALESCE(sum(committed_cost), 0)::numeric(18,2) AS committed_cost,
        COALESCE(sum(actual_cost), 0)::numeric(18,2) AS actual_cost,
        COALESCE(sum(etc_amount), 0)::numeric(18,2) AS etc_total,
        COALESCE(sum(eac), 0)::numeric(18,2) AS eac_total
    FROM all_rows
)
SELECT
    proj.currency,
    current_value.total AS contract_value,
    totals.original_budget,
    totals.approved_adjustments,
    totals.revised_budget,
    totals.committed_cost,
    totals.actual_cost,
    totals.etc_total,
    totals.eac_total,
    (totals.revised_budget - totals.eac_total)::numeric(18,2) AS variance,
    (current_value.total - totals.eac_total)::numeric(18,2) AS forecast_profit,
    -- Marj yüzdesi, GetProjectFinancialSummary'deki AYNI clamp/sıfıra
    -- bölme koruması deseniyle: current_value <= 0 ise güvenle 0 döner.
    CASE WHEN current_value.total > 0
         THEN GREATEST(-99999999.99, LEAST(99999999.99,
              round((current_value.total - totals.eac_total) * 100 / current_value.total, 2)))
         ELSE 0 END::numeric(10,2) AS forecast_margin_percent
FROM proj, current_value, totals
`

type GetProjectCostControlSummaryParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetProjectCostControlSummaryRow struct {
	Currency              string         `json:"currency"`
	ContractValue         pgtype.Numeric `json:"contract_value"`
	OriginalBudget        pgtype.Numeric `json:"original_budget"`
	ApprovedAdjustments   pgtype.Numeric `json:"approved_adjustments"`
	RevisedBudget         pgtype.Numeric `json:"revised_budget"`
	CommittedCost         pgtype.Numeric `json:"committed_cost"`
	ActualCost            pgtype.Numeric `json:"actual_cost"`
	EtcTotal              pgtype.Numeric `json:"etc_total"`
	EacTotal              pgtype.Numeric `json:"eac_total"`
	Variance              pgtype.Numeric `json:"variance"`
	ForecastProfit        pgtype.Numeric `json:"forecast_profit"`
	ForecastMarginPercent pgtype.Numeric `json:"forecast_margin_percent"`
}

// GetProjectCostControlSummary, ListCostControlLines'ın AYNI satır
// mantığını SUM() ile projeye toplar VE current_contract_value'yu
// (GetProjectFinancialSummary'deki co_effect İLE AYNI formül) ekleyip
// forecast_profit/forecast_margin'i (AYNI GREATEST/LEAST clamp deseni,
// sıfıra bölme koruması) hesaplar.
// Yalnızca maliyet koduyla (bütçe kalemi SEÇİLMEDEN) girilmiş gider/
// taahhüt, o maliyet kodunun bu projede TEK bir bütçe kalemi varsa O
// KALEME sayılır. Önceden böyle bir kayıt, kodun bütçe kalemi olsa bile
// ayrı bir "bütçe dışı" satıra düşüyordu: bütçe kaleminin ETC'si (revize -
// kendi gideri) hiç azalmadığı için aynı harcama hem o satırın ETC'sinde
// hem bütçe dışı satırın EAC'sinde sayılıyor, EAC şişiyordu. Eşleme
// OKUMA anında yapılır (kayıtlar yeniden yazılmaz): mevcut veriye de
// migration'sız uygulanır ve kodun ikinci bir bütçe kalemi açılırsa kayıt
// sessizce yanlış kalemde kalmaz -- hangi kaleme ait olduğu belirsiz
// olduğundan "bütçe dışı" satırda görünür (kullanıcı kalemi seçmelidir).
// ListCostControlLines ve GetProjectCostControlSummary'de BİREBİR AYNI.
// Gerçekleşen (actual) yalnızca ONAYLI masraflardan (migration 0060): onay
// bekleyen/reddedilen masraf EAC'yi ve bütçe aşımını şişirmez.
func (q *Queries) GetProjectCostControlSummary(ctx context.Context, arg GetProjectCostControlSummaryParams) (GetProjectCostControlSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProjectCostControlSummary, arg.ID, arg.OrganizationID)
	var i GetProjectCostControlSummaryRow
	err := row.Scan(
		&i.Currency,
		&i.ContractValue,
		&i.OriginalBudget,
		&i.ApprovedAdjustments,
		&i.RevisedBudget,
		&i.CommittedCost,
		&i.ActualCost,
		&i.EtcTotal,
		&i.EacTotal,
		&i.Variance,
		&i.ForecastProfit,
		&i.ForecastMarginPercent,
	)
	return i, err
}

const getWBSNode = `-- name: GetWBSNode :one
SELECT id, organization_id, project_id, parent_id, code, name, sort_order, is_active, created_at, updated_at FROM project_wbs_nodes WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetWBSNodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetWBSNode(ctx context.Context, arg GetWBSNodeParams) (ProjectWbsNode, error) {
	row := q.db.QueryRow(ctx, getWBSNode, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectWbsNode
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetAdjustments = `-- name: ListBudgetAdjustments :many
SELECT id, organization_id, project_id, budget_id, budget_line_id, amount, reason, status, created_by, approved_by, approved_at, created_at, updated_at FROM project_budget_adjustments WHERE project_id = $1 AND organization_id = $2
ORDER BY created_at DESC
`

type ListBudgetAdjustmentsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListBudgetAdjustments(ctx context.Context, arg ListBudgetAdjustmentsParams) ([]ProjectBudgetAdjustment, error) {
	rows, err := q.db.Query(ctx, listBudgetAdjustments, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectBudgetAdjustment
	for rows.Next() {
		var i ProjectBudgetAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetID,
			&i.BudgetLineID,
			&i.Amount,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetLinesDetailed = `-- name: ListBudgetLinesDetailed :many
SELECT bl.id, bl.organization_id, bl.project_id, bl.budget_id, bl.wbs_node_id, bl.cost_code_id, bl.description, bl.quantity, bl.unit, bl.unit_cost, bl.original_amount, bl.notes, bl.created_at, bl.updated_at, wn.code AS wbs_code, wn.name AS wbs_name, cc.code AS cost_code_code, cc.name AS cost_code_name
FROM project_budget_lines bl
LEFT JOIN project_wbs_nodes wn ON wn.id = bl.wbs_node_id
JOIN organization_cost_codes cc ON cc.id = bl.cost_code_id
WHERE bl.budget_id = $1 AND bl.organization_id = $2
ORDER BY wn.sort_order ASC NULLS LAST, cc.code ASC
`

type ListBudgetLinesDetailedParams struct {
	BudgetID       pgtype.UUID `json:"budget_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListBudgetLinesDetailedRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	BudgetID       pgtype.UUID        `json:"budget_id"`
	WbsNodeID      pgtype.UUID        `json:"wbs_node_id"`
	CostCodeID     pgtype.UUID        `json:"cost_code_id"`
	Description    string             `json:"description"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           string             `json:"unit"`
	UnitCost       pgtype.Numeric     `json:"unit_cost"`
	OriginalAmount pgtype.Numeric     `json:"original_amount"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	WbsCode        *string            `json:"wbs_code"`
	WbsName        *string            `json:"wbs_name"`
	CostCodeCode   string             `json:"cost_code_code"`
	CostCodeName   string             `json:"cost_code_name"`
}

// ListBudgetLinesDetailed, WBS/cost-code adlarını da (N+1'siz) getirir --
// Bütçe düzenleme ekranının liste görünümü içindir.
func (q *Queries) ListBudgetLinesDetailed(ctx context.Context, arg ListBudgetLinesDetailedParams) ([]ListBudgetLinesDetailedRow, error) {
	rows, err := q.db.Query(ctx, listBudgetLinesDetailed, arg.BudgetID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetLinesDetailedRow
	for rows.Next() {
		var i ListBudgetLinesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetID,
			&i.WbsNodeID,
			&i.CostCodeID,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.UnitCost,
			&i.OriginalAmount,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WbsCode,
			&i.WbsName,
			&i.CostCodeCode,
			&i.CostCodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitmentsBySourcePOItems = `-- name: ListCommitmentsBySourcePOItems :many
SELECT pc.id, pc.organization_id, pc.project_id, pc.budget_line_id, pc.cost_code_id, pc.source_type, pc.source_id, pc.description, pc.committed_amount, pc.currency, pc.status, pc.committed_at, pc.idempotency_key, pc.created_by, pc.voided_at, pc.voided_by, pc.void_reason, pc.created_at, pc.updated_at FROM project_commitments pc
WHERE pc.organization_id = $1 AND pc.project_id = $2
  AND pc.source_type = 'purchase_order'
  AND pc.source_id IN (SELECT poi.id FROM purchase_order_items poi WHERE poi.purchase_order_id = $3)
`

type ListCommitmentsBySourcePOItemsParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	PurchaseOrderID pgtype.UUID `json:"purchase_order_id"`
}

func (q *Queries) ListCommitmentsBySourcePOItems(ctx context.Context, arg ListCommitmentsBySourcePOItemsParams) ([]ProjectCommitment, error) {
	rows, err := q.db.Query(ctx, listCommitmentsBySourcePOItems, arg.OrganizationID, arg.ProjectID, arg.PurchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCommitment
	for rows.Next() {
		var i ProjectCommitment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetLineID,
			&i.CostCodeID,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.CommittedAmount,
			&i.Currency,
			&i.Status,
			&i.CommittedAt,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitmentsBySourceSubcontract = `-- name: ListCommitmentsBySourceSubcontract :many
SELECT pc.id, pc.organization_id, pc.project_id, pc.budget_line_id, pc.cost_code_id, pc.source_type, pc.source_id, pc.description, pc.committed_amount, pc.currency, pc.status, pc.committed_at, pc.idempotency_key, pc.created_by, pc.voided_at, pc.voided_by, pc.void_reason, pc.created_at, pc.updated_at FROM project_commitments pc
WHERE pc.organization_id = $1 AND pc.project_id = $2
  AND pc.source_type = 'subcontract' AND pc.source_id = $3
`

type ListCommitmentsBySourceSubcontractParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	SourceID       pgtype.UUID `json:"source_id"`
}

func (q *Queries) ListCommitmentsBySourceSubcontract(ctx context.Context, arg ListCommitmentsBySourceSubcontractParams) ([]ProjectCommitment, error) {
	rows, err := q.db.Query(ctx, listCommitmentsBySourceSubcontract, arg.OrganizationID, arg.ProjectID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCommitment
	for rows.Next() {
		var i ProjectCommitment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetLineID,
			&i.CostCodeID,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.CommittedAmount,
			&i.Currency,
			&i.Status,
			&i.CommittedAt,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitmentsDetailed = `-- name: ListCommitmentsDetailed :many
SELECT c.id, c.organization_id, c.project_id, c.budget_line_id, c.cost_code_id, c.source_type, c.source_id, c.description, c.committed_amount, c.currency, c.status, c.committed_at, c.idempotency_key, c.created_by, c.voided_at, c.voided_by, c.void_reason, c.created_at, c.updated_at, cc.code AS cost_code_code, cc.name AS cost_code_name
FROM project_commitments c
JOIN organization_cost_codes cc ON cc.id = c.cost_code_id
WHERE c.project_id = $1 AND c.organization_id = $2
ORDER BY c.committed_at DESC, c.created_at DESC
`

type ListCommitmentsDetailedParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListCommitmentsDetailedRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	BudgetLineID    pgtype.UUID        `json:"budget_line_id"`
	CostCodeID      pgtype.UUID        `json:"cost_code_id"`
	SourceType      string             `json:"source_type"`
	SourceID        pgtype.UUID        `json:"source_id"`
	Description     string             `json:"description"`
	CommittedAmount pgtype.Numeric     `json:"committed_amount"`
	Currency        string             `json:"currency"`
	Status          string             `json:"status"`
	CommittedAt     pgtype.Date        `json:"committed_at"`
	IdempotencyKey  *string            `json:"idempotency_key"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	VoidedAt        pgtype.Timestamptz `json:"voided_at"`
	VoidedBy        pgtype.UUID        `json:"voided_by"`
	VoidReason      string             `json:"void_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CostCodeCode    string             `json:"cost_code_code"`
	CostCodeName    string             `json:"cost_code_name"`
}

// ListCommitmentsDetailed, cost-code/wbs adlarını da (N+1'siz) getirir.
func (q *Queries) ListCommitmentsDetailed(ctx context.Context, arg ListCommitmentsDetailedParams) ([]ListCommitmentsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listCommitmentsDetailed, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommitmentsDetailedRow
	for rows.Next() {
		var i ListCommitmentsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetLineID,
			&i.CostCodeID,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.CommittedAmount,
			&i.Currency,
			&i.Status,
			&i.CommittedAt,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CostCodeCode,
			&i.CostCodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostControlLines = `-- name: ListCostControlLines :many

WITH lines AS (
    SELECT bl.id AS budget_line_id, bl.wbs_node_id, bl.cost_code_id, bl.description, bl.original_amount
    FROM project_budget_lines bl WHERE bl.project_id = $1 AND bl.organization_id = $2
),
adjustments AS (
    SELECT budget_line_id, COALESCE(sum(amount), 0)::numeric(18,2) AS total
    FROM project_budget_adjustments
    WHERE project_id = $1 AND organization_id = $2 AND status = 'approved'
    GROUP BY budget_line_id
),
single_line_codes AS (
    SELECT bl.cost_code_id, (array_agg(bl.id))[1] AS budget_line_id
    FROM project_budget_lines bl WHERE bl.project_id = $1 AND bl.organization_id = $2
    GROUP BY bl.cost_code_id
    HAVING count(*) = 1
),
committed_by_line AS (
    SELECT COALESCE(c.budget_line_id, slc.budget_line_id) AS budget_line_id,
        COALESCE(sum(c.committed_amount), 0)::numeric(18,2) AS total
    FROM project_commitments c
    LEFT JOIN single_line_codes slc ON c.budget_line_id IS NULL AND slc.cost_code_id = c.cost_code_id
    WHERE c.project_id = $1 AND c.organization_id = $2 AND c.status = 'active'
      AND COALESCE(c.budget_line_id, slc.budget_line_id) IS NOT NULL
    GROUP BY COALESCE(c.budget_line_id, slc.budget_line_id)
),
actual_by_line AS (
    SELECT COALESCE(e.budget_line_id, slc.budget_line_id) AS budget_line_id,
        COALESCE(sum(e.amount), 0)::numeric(18,2) AS total
    FROM project_expenses e
    LEFT JOIN single_line_codes slc ON e.budget_line_id IS NULL AND slc.cost_code_id = e.cost_code_id
    WHERE e.project_id = $1 AND e.organization_id = $2 AND e.voided_at IS NULL AND e.approval_status = 'approved'
      AND COALESCE(e.budget_line_id, slc.budget_line_id) IS NOT NULL
    GROUP BY COALESCE(e.budget_line_id, slc.budget_line_id)
),
forecast_by_line AS (
    SELECT budget_line_id, etc_amount FROM project_cost_forecasts WHERE project_id = $1 AND organization_id = $2
),
budgeted AS (
    SELECT
        l.budget_line_id, l.wbs_node_id, wn.code AS wbs_code, wn.name AS wbs_name,
        l.cost_code_id, cc.code AS cost_code_code, cc.name AS cost_code_name,
        l.description::varchar AS description, l.original_amount,
        COALESCE(adj.total, 0)::numeric(18,2) AS approved_adjustments,
        (l.original_amount + COALESCE(adj.total, 0))::numeric(18,2) AS revised_budget,
        COALESCE(com.total, 0)::numeric(18,2) AS committed_cost,
        COALESCE(act.total, 0)::numeric(18,2) AS actual_cost,
        COALESCE(fc.etc_amount, GREATEST((l.original_amount + COALESCE(adj.total, 0)) - COALESCE(act.total, 0), 0))::numeric(18,2) AS etc_amount,
        (COALESCE(act.total, 0) + COALESCE(fc.etc_amount, GREATEST((l.original_amount + COALESCE(adj.total, 0)) - COALESCE(act.total, 0), 0)))::numeric(18,2) AS eac,
        ((l.original_amount + COALESCE(adj.total, 0)) - (COALESCE(act.total, 0) + COALESCE(fc.etc_amount, GREATEST((l.original_amount + COALESCE(adj.total, 0)) - COALESCE(act.total, 0), 0))))::numeric(18,2) AS variance,
        false AS is_unbudgeted
    FROM lines l
    LEFT JOIN project_wbs_nodes wn ON wn.id = l.wbs_node_id
    JOIN organization_cost_codes cc ON cc.id = l.cost_code_id
    LEFT JOIN adjustments adj ON adj.budget_line_id = l.budget_line_id
    LEFT JOIN committed_by_line com ON com.budget_line_id = l.budget_line_id
    LEFT JOIN actual_by_line act ON act.budget_line_id = l.budget_line_id
    LEFT JOIN forecast_by_line fc ON fc.budget_line_id = l.budget_line_id
),
unbudgeted_committed AS (
    SELECT c.cost_code_id, COALESCE(sum(c.committed_amount), 0)::numeric(18,2) AS total
    FROM project_commitments c
    WHERE c.project_id = $1 AND c.organization_id = $2 AND c.status = 'active' AND c.budget_line_id IS NULL
      AND NOT EXISTS (SELECT 1 FROM single_line_codes slc WHERE slc.cost_code_id = c.cost_code_id)
    GROUP BY c.cost_code_id
),
unbudgeted_actual AS (
    SELECT e.cost_code_id, COALESCE(sum(e.amount), 0)::numeric(18,2) AS total
    FROM project_expenses e
    WHERE e.project_id = $1 AND e.organization_id = $2 AND e.voided_at IS NULL AND e.approval_status = 'approved' AND e.budget_line_id IS NULL AND e.cost_code_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM single_line_codes slc WHERE slc.cost_code_id = e.cost_code_id)
    GROUP BY e.cost_code_id
),
unbudgeted_codes AS (
    SELECT cost_code_id FROM unbudgeted_committed
    UNION
    SELECT cost_code_id FROM unbudgeted_actual
),
unbudgeted AS (
    SELECT
        NULL::uuid AS budget_line_id, NULL::uuid AS wbs_node_id, NULL::varchar AS wbs_code, NULL::varchar AS wbs_name,
        uc.cost_code_id, cc.code AS cost_code_code, cc.name AS cost_code_name,
        ''::varchar AS description, 0::numeric(18,2) AS original_amount,
        0::numeric(18,2) AS approved_adjustments, 0::numeric(18,2) AS revised_budget,
        COALESCE(ucom.total, 0)::numeric(18,2) AS committed_cost, COALESCE(uact.total, 0)::numeric(18,2) AS actual_cost,
        0::numeric(18,2) AS etc_amount, COALESCE(uact.total, 0)::numeric(18,2) AS eac,
        (0 - COALESCE(uact.total, 0))::numeric(18,2) AS variance, true AS is_unbudgeted
    FROM unbudgeted_codes uc
    JOIN organization_cost_codes cc ON cc.id = uc.cost_code_id
    LEFT JOIN unbudgeted_committed ucom ON ucom.cost_code_id = uc.cost_code_id
    LEFT JOIN unbudgeted_actual uact ON uact.cost_code_id = uc.cost_code_id
)
SELECT budget_line_id, wbs_node_id, wbs_code, wbs_name, cost_code_id, cost_code_code, cost_code_name, description, original_amount, approved_adjustments, revised_budget, committed_cost, actual_cost, etc_amount, eac, variance, is_unbudgeted FROM budgeted
UNION ALL
SELECT budget_line_id, wbs_node_id, wbs_code, wbs_name, cost_code_id, cost_code_code, cost_code_name, description, original_amount, approved_adjustments, revised_budget, committed_cost, actual_cost, etc_amount, eac, variance, is_unbudgeted FROM unbudgeted
ORDER BY is_unbudgeted ASC, wbs_code ASC NULLS LAST, cost_code_code ASC
`

type ListCostControlLinesParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListCostControlLinesRow struct {
	BudgetLineID        pgtype.UUID    `json:"budget_line_id"`
	WbsNodeID           pgtype.UUID    `json:"wbs_node_id"`
	WbsCode             *string        `json:"wbs_code"`
	WbsName             *string        `json:"wbs_name"`
	CostCodeID          pgtype.UUID    `json:"cost_code_id"`
	CostCodeCode        string         `json:"cost_code_code"`
	CostCodeName        string         `json:"cost_code_name"`
	Description         string         `json:"description"`
	OriginalAmount      pgtype.Numeric `json:"original_amount"`
	ApprovedAdjustments pgtype.Numeric `json:"approved_adjustments"`
	RevisedBudget       pgtype.Numeric `json:"revised_budget"`
	CommittedCost       pgtype.Numeric `json:"committed_cost"`
	ActualCost          pgtype.Numeric `json:"actual_cost"`
	EtcAmount           pgtype.Numeric `json:"etc_amount"`
	Eac                 pgtype.Numeric `json:"eac"`
	Variance            pgtype.Numeric `json:"variance"`
	IsUnbudgeted        bool           `json:"is_unbudgeted"`
}

// ============ Maliyet Kontrolü Özeti / Kırılım Tablosu ============
//
// Her iki sorgu da AYNI satır-bazlı mantığı (budgeted + unbudgeted CTE'ler)
// kullanır -- proje toplamı satır toplamlarının SQL SUM()'udur. Sorgu
// metni sqlc'nin sorgular-arası CTE paylaşımını desteklememesi nedeniyle
// İKİ KEZ yazılmıştır (project_finance.sql'deki co_effect/GetChangeOrder-
// EffectTotals AYNI, önceden kabul edilmiş desen) -- biri değişirse
// diğeri de GÜNCELLENMELİDİR (bkz. docs/cost-control.md).
// Yalnızca maliyet koduyla (bütçe kalemi SEÇİLMEDEN) girilmiş gider/
// taahhüt, o maliyet kodunun bu projede TEK bir bütçe kalemi varsa O
// KALEME sayılır. Önceden böyle bir kayıt, kodun bütçe kalemi olsa bile
// ayrı bir "bütçe dışı" satıra düşüyordu: bütçe kaleminin ETC'si (revize -
// kendi gideri) hiç azalmadığı için aynı harcama hem o satırın ETC'sinde
// hem bütçe dışı satırın EAC'sinde sayılıyor, EAC şişiyordu. Eşleme
// OKUMA anında yapılır (kayıtlar yeniden yazılmaz): mevcut veriye de
// migration'sız uygulanır ve kodun ikinci bir bütçe kalemi açılırsa kayıt
// sessizce yanlış kalemde kalmaz -- hangi kaleme ait olduğu belirsiz
// olduğundan "bütçe dışı" satırda görünür (kullanıcı kalemi seçmelidir).
// ListCostControlLines ve GetProjectCostControlSummary'de BİREBİR AYNI.
// Gerçekleşen (actual) yalnızca ONAYLI masraflardan (migration 0060): onay
// bekleyen/reddedilen masraf EAC'yi ve bütçe aşımını şişirmez.
// Bütçe dışı (unbudgeted) satırlar: bir cost_code'a doğrudan (budget_line_id
// OLMADAN) bağlanmış taahhüt/gider var ama bu cost code'un o projede bir
// bütçe kalemi yok (ya da birden fazla var ve hangisine ait olduğu
// belirsiz, bkz. single_line_codes) -- "kategorisiz/plansız harcama"
// olarak AÇIKÇA gösterilir (original_budget=0, variance HER ZAMAN negatif).
func (q *Queries) ListCostControlLines(ctx context.Context, arg ListCostControlLinesParams) ([]ListCostControlLinesRow, error) {
	rows, err := q.db.Query(ctx, listCostControlLines, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCostControlLinesRow
	for rows.Next() {
		var i ListCostControlLinesRow
		if err := rows.Scan(
			&i.BudgetLineID,
			&i.WbsNodeID,
			&i.WbsCode,
			&i.WbsName,
			&i.CostCodeID,
			&i.CostCodeCode,
			&i.CostCodeName,
			&i.Description,
			&i.OriginalAmount,
			&i.ApprovedAdjustments,
			&i.RevisedBudget,
			&i.CommittedCost,
			&i.ActualCost,
			&i.EtcAmount,
			&i.Eac,
			&i.Variance,
			&i.IsUnbudgeted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForecasts = `-- name: ListForecasts :many
SELECT id, organization_id, project_id, budget_line_id, etc_amount, note, updated_by, updated_at FROM project_cost_forecasts WHERE project_id = $1 AND organization_id = $2
`

type ListForecastsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListForecasts(ctx context.Context, arg ListForecastsParams) ([]ProjectCostForecast, error) {
	rows, err := q.db.Query(ctx, listForecasts, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCostForecast
	for rows.Next() {
		var i ProjectCostForecast
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetLineID,
			&i.EtcAmount,
			&i.Note,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationCostCodes = `-- name: ListOrganizationCostCodes :many
SELECT id, organization_id, code, name, description, category, is_active, created_at, updated_at FROM organization_cost_codes WHERE organization_id = $1 ORDER BY code ASC
`

func (q *Queries) ListOrganizationCostCodes(ctx context.Context, organizationID pgtype.UUID) ([]OrganizationCostCode, error) {
	rows, err := q.db.Query(ctx, listOrganizationCostCodes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationCostCode
	for rows.Next() {
		var i OrganizationCostCode
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationEvents = `-- name: ListOrganizationEvents :many
SELECT id, organization_id, event_type, user_id, metadata, created_at FROM organization_events WHERE organization_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOrganizationEventsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListOrganizationEvents(ctx context.Context, arg ListOrganizationEventsParams) ([]OrganizationEvent, error) {
	rows, err := q.db.Query(ctx, listOrganizationEvents, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationEvent
	for rows.Next() {
		var i OrganizationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventType,
			&i.UserID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWBSNodes = `-- name: ListWBSNodes :many
SELECT id, organization_id, project_id, parent_id, code, name, sort_order, is_active, created_at, updated_at FROM project_wbs_nodes WHERE project_id = $1 AND organization_id = $2
ORDER BY sort_order ASC, code ASC
`

type ListWBSNodesParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// TÜM düğümler (aktif+arşivlenmiş) döner -- ağaç yapısı korunur, arşivlenmiş
// düğümler istemci tarafında soluk gösterilir (spec: "kullanılan node
// hard-delete edilmemeli").
func (q *Queries) ListWBSNodes(ctx context.Context, arg ListWBSNodesParams) ([]ProjectWbsNode, error) {
	rows, err := q.db.Query(ctx, listWBSNodes, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectWbsNode
	for rows.Next() {
		var i ProjectWbsNode
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateOrganizationCostCode = `-- name: ReactivateOrganizationCostCode :execrows
UPDATE organization_cost_codes SET is_active = true WHERE id = $1 AND organization_id = $2
`

type ReactivateOrganizationCostCodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ReactivateOrganizationCostCode(ctx context.Context, arg ReactivateOrganizationCostCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateOrganizationCostCode, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectBudgetAdjustment = `-- name: RejectBudgetAdjustment :one
UPDATE project_budget_adjustments SET status = 'rejected', approved_by = $4, approved_at = now()
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'draft'
RETURNING id, organization_id, project_id, budget_id, budget_line_id, amount, reason, status, created_by, approved_by, approved_at, created_at, updated_at
`

type RejectBudgetAdjustmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	ApprovedBy     pgtype.UUID `json:"approved_by"`
}

func (q *Queries) RejectBudgetAdjustment(ctx context.Context, arg RejectBudgetAdjustmentParams) (ProjectBudgetAdjustment, error) {
	row := q.db.QueryRow(ctx, rejectBudgetAdjustment,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ApprovedBy,
	)
	var i ProjectBudgetAdjustment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.BudgetLineID,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudgetLine = `-- name: UpdateBudgetLine :one
UPDATE project_budget_lines
SET wbs_node_id = $4, cost_code_id = $5, description = $6, quantity = $7, unit = $8,
    unit_cost = $9, original_amount = $10, notes = $11
WHERE id = $1 AND organization_id = $2 AND project_id = $3
RETURNING id, organization_id, project_id, budget_id, wbs_node_id, cost_code_id, description, quantity, unit, unit_cost, original_amount, notes, created_at, updated_at
`

type UpdateBudgetLineParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	WbsNodeID      pgtype.UUID    `json:"wbs_node_id"`
	CostCodeID     pgtype.UUID    `json:"cost_code_id"`
	Description    string         `json:"description"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	UnitCost       pgtype.Numeric `json:"unit_cost"`
	OriginalAmount pgtype.Numeric `json:"original_amount"`
	Notes          string         `json:"notes"`
}

func (q *Queries) UpdateBudgetLine(ctx context.Context, arg UpdateBudgetLineParams) (ProjectBudgetLine, error) {
	row := q.db.QueryRow(ctx, updateBudgetLine,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.WbsNodeID,
		arg.CostCodeID,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitCost,
		arg.OriginalAmount,
		arg.Notes,
	)
	var i ProjectBudgetLine
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetID,
		&i.WbsNodeID,
		&i.CostCodeID,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitCost,
		&i.OriginalAmount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationCostCode = `-- name: UpdateOrganizationCostCode :one
UPDATE organization_cost_codes SET name = $3, description = $4, category = $5
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, code, name, description, category, is_active, created_at, updated_at
`

type UpdateOrganizationCostCodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	Category       string      `json:"category"`
}

func (q *Queries) UpdateOrganizationCostCode(ctx context.Context, arg UpdateOrganizationCostCodeParams) (OrganizationCostCode, error) {
	row := q.db.QueryRow(ctx, updateOrganizationCostCode,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	var i OrganizationCostCode
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWBSNode = `-- name: UpdateWBSNode :one
UPDATE project_wbs_nodes SET code = $4, name = $5, sort_order = $6
WHERE id = $1 AND organization_id = $2 AND project_id = $3
RETURNING id, organization_id, project_id, parent_id, code, name, sort_order, is_active, created_at, updated_at
`

type UpdateWBSNodeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	SortOrder      int32       `json:"sort_order"`
}

// Yalnızca rename/reorder -- bu sprintte re-parent (parent_id değişimi)
// YOKTUR (spec: "Complex drag/drop zorunlu değil"), bu yüzden döngü
// riski hiç oluşmaz.
func (q *Queries) UpdateWBSNode(ctx context.Context, arg UpdateWBSNodeParams) (ProjectWbsNode, error) {
	row := q.db.QueryRow(ctx, updateWBSNode,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Code,
		arg.Name,
		arg.SortOrder,
	)
	var i ProjectWbsNode
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertForecast = `-- name: UpsertForecast :one

INSERT INTO project_cost_forecasts (organization_id, project_id, budget_line_id, etc_amount, note, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (budget_line_id) DO UPDATE
    SET etc_amount = EXCLUDED.etc_amount, note = EXCLUDED.note, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING id, organization_id, project_id, budget_line_id, etc_amount, note, updated_by, updated_at
`

type UpsertForecastParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	BudgetLineID   pgtype.UUID    `json:"budget_line_id"`
	EtcAmount      pgtype.Numeric `json:"etc_amount"`
	Note           string         `json:"note"`
	UpdatedBy      pgtype.UUID    `json:"updated_by"`
}

// ============ Tahmin (Forecast / ETC) ============
func (q *Queries) UpsertForecast(ctx context.Context, arg UpsertForecastParams) (ProjectCostForecast, error) {
	row := q.db.QueryRow(ctx, upsertForecast,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BudgetLineID,
		arg.EtcAmount,
		arg.Note,
		arg.UpdatedBy,
	)
	var i ProjectCostForecast
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetLineID,
		&i.EtcAmount,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const voidCommitment = `-- name: VoidCommitment :one
UPDATE project_commitments SET status = 'voided', voided_at = now(), voided_by = $4, void_reason = $5
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'active' AND source_type = 'manual'
RETURNING id, organization_id, project_id, budget_line_id, cost_code_id, source_type, source_id, description, committed_amount, currency, status, committed_at, idempotency_key, created_by, voided_at, voided_by, void_reason, created_at, updated_at
`

type VoidCommitmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	VoidedBy       pgtype.UUID `json:"voided_by"`
	VoidReason     string      `json:"void_reason"`
}

// Elle iptal YALNIZCA manuel taahhütler içindir: satın alma siparişinden/
// taşeron sözleşmesinden doğan taahhüt kaynağının yaşam döngüsüyle
// (sipariş iptali, değişiklik onayı, fesih) senkron tutulur; elle
// voidlenirse kaynak hâlâ geçerliyken Cost Control'den sessizce düşerdi.
func (q *Queries) VoidCommitment(ctx context.Context, arg VoidCommitmentParams) (ProjectCommitment, error) {
	row := q.db.QueryRow(ctx, voidCommitment,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.VoidedBy,
		arg.VoidReason,
	)
	var i ProjectCommitment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.BudgetLineID,
		&i.CostCodeID,
		&i.SourceType,
		&i.SourceID,
		&i.Description,
		&i.CommittedAmount,
		&i.Currency,
		&i.Status,
		&i.CommittedAt,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidCommitmentsBySourcePOItems = `-- name: VoidCommitmentsBySourcePOItems :many
UPDATE project_commitments pc
SET status = 'voided', voided_at = now(), voided_by = $4, void_reason = $5
WHERE pc.organization_id = $1 AND pc.project_id = $2
  AND pc.source_type = 'purchase_order'
  AND pc.source_id IN (SELECT poi.id FROM purchase_order_items poi WHERE poi.purchase_order_id = $3)
  AND pc.status = 'active'
RETURNING pc.id, pc.organization_id, pc.project_id, pc.budget_line_id, pc.cost_code_id, pc.source_type, pc.source_id, pc.description, pc.committed_amount, pc.currency, pc.status, pc.committed_at, pc.idempotency_key, pc.created_by, pc.voided_at, pc.voided_by, pc.void_reason, pc.created_at, pc.updated_at
`

type VoidCommitmentsBySourcePOItemsParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	PurchaseOrderID pgtype.UUID `json:"purchase_order_id"`
	VoidedBy        pgtype.UUID `json:"voided_by"`
	VoidReason      string      `json:"void_reason"`
}

// PO iptalinde, o PO'nun kalemlerinden doğan TÜM aktif taahhütleri TEK
// sorguda voider (status='voided' koşulu idempotenttir -- zaten voided
// olanlar sonuçtan dışlanır, ikinci bir çağrı zararsızdır).
func (q *Queries) VoidCommitmentsBySourcePOItems(ctx context.Context, arg VoidCommitmentsBySourcePOItemsParams) ([]ProjectCommitment, error) {
	rows, err := q.db.Query(ctx, voidCommitmentsBySourcePOItems,
		arg.OrganizationID,
		arg.ProjectID,
		arg.PurchaseOrderID,
		arg.VoidedBy,
		arg.VoidReason,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCommitment
	for rows.Next() {
		var i ProjectCommitment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetLineID,
			&i.CostCodeID,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.CommittedAmount,
			&i.Currency,
			&i.Status,
			&i.CommittedAt,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidCommitmentsBySourceSubcontract = `-- name: VoidCommitmentsBySourceSubcontract :many

UPDATE project_commitments pc
SET status = 'voided', voided_at = now(), voided_by = $4, void_reason = $5
WHERE pc.organization_id = $1 AND pc.project_id = $2
  AND pc.source_type = 'subcontract' AND pc.source_id = $3
  AND pc.status = 'active'
RETURNING pc.id, pc.organization_id, pc.project_id, pc.budget_line_id, pc.cost_code_id, pc.source_type, pc.source_id, pc.description, pc.committed_amount, pc.currency, pc.status, pc.committed_at, pc.idempotency_key, pc.created_by, pc.voided_at, pc.voided_by, pc.void_reason, pc.created_at, pc.updated_at
`

type VoidCommitmentsBySourceSubcontractParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	SourceID       pgtype.UUID `json:"source_id"`
	VoidedBy       pgtype.UUID `json:"voided_by"`
	VoidReason     string      `json:"void_reason"`
}

// Sprint 5 -- Subcontract entegrasyonu. PO'nun İTEM-seviyesi (source_id =
// purchase_order_items.id, kalıcı/tek seferlik) modelinden BİLİNÇLİ SAPMA:
// bir Subcontract'ın taahhüdü değişiklik emirleri/fesihle YAŞAM BOYU
// DEĞİŞEBİLİR, bu yüzden source_id = project_subcontracts.id (SÖZLEŞME
// seviyesinde) kullanılır ve syncSubcontractCommitments HER ticari olayda
// (aktivasyon/değişiklik onayı/fesih) BÜTÜN aktif taahhütleri voidleyip
// maliyet-kodu bazında NETLENMİŞ satırlarla YENİDEN OLUŞTURUR -- bkz.
// docs/subcontracts.md §Commitment Entegrasyonu.
func (q *Queries) VoidCommitmentsBySourceSubcontract(ctx context.Context, arg VoidCommitmentsBySourceSubcontractParams) ([]ProjectCommitment, error) {
	rows, err := q.db.Query(ctx, voidCommitmentsBySourceSubcontract,
		arg.OrganizationID,
		arg.ProjectID,
		arg.SourceID,
		arg.VoidedBy,
		arg.VoidReason,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCommitment
	for rows.Next() {
		var i ProjectCommitment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.BudgetLineID,
			&i.CostCodeID,
			&i.SourceType,
			&i.SourceID,
			&i.Description,
			&i.CommittedAmount,
			&i.Currency,
			&i.Status,
			&i.CommittedAt,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
