// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCustomer = `-- name: ArchiveCustomer :execrows
UPDATE customers SET is_active = false WHERE id = $1 AND organization_id = $2
`

type ArchiveCustomerParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveCustomer(ctx context.Context, arg ArchiveCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCustomer, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (organization_id, name, phone, email, address, tax_office, tax_number, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, phone, email, address, tax_office, tax_number, notes, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
	Address        string      `json:"address"`
	TaxOffice      string      `json:"tax_office"`
	TaxNumber      string      `json:"tax_number"`
	Notes          string      `json:"notes"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.OrganizationID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.TaxOffice,
		arg.TaxNumber,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.TaxOffice,
		&i.TaxNumber,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, organization_id, name, phone, email, address, tax_office, tax_number, notes, is_active, created_at, updated_at FROM customers WHERE id = $1 AND organization_id = $2
`

type GetCustomerByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.OrganizationID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.TaxOffice,
		&i.TaxNumber,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, organization_id, name, phone, email, address, tax_office, tax_number, notes, is_active, created_at, updated_at FROM customers
WHERE organization_id = $1
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%')
ORDER BY name ASC
`

type ListCustomersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Column2        string      `json:"column_2"`
	IsActive       *bool       `json:"is_active"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.OrganizationID, arg.Column2, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.TaxOffice,
			&i.TaxNumber,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $3, phone = $4, email = $5, address = $6, tax_office = $7,
    tax_number = $8, notes = $9, is_active = $10
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, phone, email, address, tax_office, tax_number, notes, is_active, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Phone          string      `json:"phone"`
	Email          string      `json:"email"`
	Address        string      `json:"address"`
	TaxOffice      string      `json:"tax_office"`
	TaxNumber      string      `json:"tax_number"`
	Notes          string      `json:"notes"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.TaxOffice,
		arg.TaxNumber,
		arg.Notes,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.TaxOffice,
		&i.TaxNumber,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
