// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEmployee = `-- name: ArchiveEmployee :exec
UPDATE employees SET is_active = false, archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveEmployee(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveEmployee, id)
	return err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (full_name, phone, position, salary, daily_wage, start_date, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at
`

type CreateEmployeeParams struct {
	FullName    string         `json:"full_name"`
	Phone       string         `json:"phone"`
	Position    string         `json:"position"`
	Salary      pgtype.Numeric `json:"salary"`
	DailyWage   pgtype.Numeric `json:"daily_wage"`
	StartDate   pgtype.Date    `json:"start_date"`
	Description string         `json:"description"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Salary,
		arg.DailyWage,
		arg.StartDate,
		arg.Description,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at FROM employees WHERE id = $1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at FROM employees
WHERE ($1::boolean IS NULL OR is_active = $1::boolean)
ORDER BY full_name ASC
`

func (q *Queries) ListEmployees(ctx context.Context, isActive *bool) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Position,
			&i.Salary,
			&i.DailyWage,
			&i.StartDate,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET full_name = $2, phone = $3, position = $4, salary = $5, daily_wage = $6,
    start_date = $7, description = $8, is_active = $9
WHERE id = $1
RETURNING id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at
`

type UpdateEmployeeParams struct {
	ID          pgtype.UUID    `json:"id"`
	FullName    string         `json:"full_name"`
	Phone       string         `json:"phone"`
	Position    string         `json:"position"`
	Salary      pgtype.Numeric `json:"salary"`
	DailyWage   pgtype.Numeric `json:"daily_wage"`
	StartDate   pgtype.Date    `json:"start_date"`
	Description string         `json:"description"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Salary,
		arg.DailyWage,
		arg.StartDate,
		arg.Description,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
