// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_wage_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEmployeeWageIfNone = `-- name: InsertEmployeeWageIfNone :exec
INSERT INTO employee_wage_history (organization_id, employee_id, salary, daily_wage, effective_from)
SELECT e.organization_id, e.id, e.salary, e.daily_wage,
       LEAST(COALESCE(e.start_date, DATE '2000-01-01'), $1::date)
FROM employees e
WHERE e.id = $2 AND e.organization_id = $3
  AND NOT EXISTS (SELECT 1 FROM employee_wage_history h WHERE h.employee_id = e.id)
ON CONFLICT (employee_id, effective_from) DO NOTHING
`

type InsertEmployeeWageIfNoneParams struct {
	Today          pgtype.Date `json:"today"`
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Geçmişi hiç olmayan personel (ör. migration'dan sonra servisi atlayarak
// eklenmiş) için başlangıç satırı: ilk ücret değişikliğinden ÖNCE eski
// ücret kaydedilmezse, değişiklik geçmiş ayların tamamına yayılırdı.
// İleri tarihli işe giriş bugüne çekilir: geçmişte ileri tarihli bir satır
// kalırsa bugünkü değişiklik o aydan itibaren ESKİ ücrete yenik düşerdi.
func (q *Queries) InsertEmployeeWageIfNone(ctx context.Context, arg InsertEmployeeWageIfNoneParams) error {
	_, err := q.db.Exec(ctx, insertEmployeeWageIfNone, arg.Today, arg.ID, arg.OrganizationID)
	return err
}

const listEmployeeWageHistory = `-- name: ListEmployeeWageHistory :many
SELECT id, organization_id, employee_id, salary, daily_wage, effective_from, created_by, created_at FROM employee_wage_history
WHERE employee_id = $1 AND organization_id = $2
ORDER BY effective_from
`

type ListEmployeeWageHistoryParams struct {
	EmployeeID     pgtype.UUID `json:"employee_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListEmployeeWageHistory(ctx context.Context, arg ListEmployeeWageHistoryParams) ([]EmployeeWageHistory, error) {
	rows, err := q.db.Query(ctx, listEmployeeWageHistory, arg.EmployeeID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeWageHistory
	for rows.Next() {
		var i EmployeeWageHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EmployeeID,
			&i.Salary,
			&i.DailyWage,
			&i.EffectiveFrom,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeWageHistoryByOrganization = `-- name: ListEmployeeWageHistoryByOrganization :many
SELECT employee_id, salary, daily_wage, effective_from
FROM employee_wage_history
WHERE organization_id = $1
ORDER BY employee_id, effective_from
`

type ListEmployeeWageHistoryByOrganizationRow struct {
	EmployeeID    pgtype.UUID    `json:"employee_id"`
	Salary        pgtype.Numeric `json:"salary"`
	DailyWage     pgtype.Numeric `json:"daily_wage"`
	EffectiveFrom pgtype.Date    `json:"effective_from"`
}

func (q *Queries) ListEmployeeWageHistoryByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListEmployeeWageHistoryByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeWageHistoryByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeWageHistoryByOrganizationRow
	for rows.Next() {
		var i ListEmployeeWageHistoryByOrganizationRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Salary,
			&i.DailyWage,
			&i.EffectiveFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmployeeWage = `-- name: UpsertEmployeeWage :exec

INSERT INTO employee_wage_history (organization_id, employee_id, salary, daily_wage, effective_from, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (employee_id, effective_from) DO UPDATE
SET salary = EXCLUDED.salary,
    daily_wage = EXCLUDED.daily_wage,
    created_by = EXCLUDED.created_by,
    created_at = now()
`

type UpsertEmployeeWageParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	EmployeeID     pgtype.UUID    `json:"employee_id"`
	Salary         pgtype.Numeric `json:"salary"`
	DailyWage      pgtype.Numeric `json:"daily_wage"`
	EffectiveFrom  pgtype.Date    `json:"effective_from"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

// Ücret geçmişi (migration 0056). Maaş hesabı her ayı o ayda geçerli
// ücretle yapar (bkz. domain.WageForPeriod).
// Aynı gün ikinci değişiklik öncekinin yerine geçer.
func (q *Queries) UpsertEmployeeWage(ctx context.Context, arg UpsertEmployeeWageParams) error {
	_, err := q.db.Exec(ctx, upsertEmployeeWage,
		arg.OrganizationID,
		arg.EmployeeID,
		arg.Salary,
		arg.DailyWage,
		arg.EffectiveFrom,
		arg.CreatedBy,
	)
	return err
}
