// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEmployee = `-- name: ArchiveEmployee :exec
UPDATE employees SET is_active = false, archived_at = now() WHERE id = $1 AND organization_id = $2
`

type ArchiveEmployeeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveEmployee(ctx context.Context, arg ArchiveEmployeeParams) error {
	_, err := q.db.Exec(ctx, archiveEmployee, arg.ID, arg.OrganizationID)
	return err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (organization_id, full_name, phone, position, salary, daily_wage, start_date, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id
`

type CreateEmployeeParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	FullName       string         `json:"full_name"`
	Phone          string         `json:"phone"`
	Position       string         `json:"position"`
	Salary         pgtype.Numeric `json:"salary"`
	DailyWage      pgtype.Numeric `json:"daily_wage"`
	StartDate      pgtype.Date    `json:"start_date"`
	Description    string         `json:"description"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OrganizationID,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Salary,
		arg.DailyWage,
		arg.StartDate,
		arg.Description,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id FROM employees WHERE id = $1 AND organization_id = $2
`

type GetEmployeeByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, arg GetEmployeeByIDParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, arg.ID, arg.OrganizationID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id FROM employees
WHERE organization_id = $1
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
ORDER BY full_name ASC
`

type ListEmployeesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	IsActive       *bool       `json:"is_active"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.OrganizationID, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Position,
			&i.Salary,
			&i.DailyWage,
			&i.StartDate,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET full_name = $3, phone = $4, position = $5, salary = $6, daily_wage = $7,
    start_date = $8, description = $9, is_active = $10
WHERE id = $1 AND organization_id = $2
RETURNING id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id
`

type UpdateEmployeeParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	FullName       string         `json:"full_name"`
	Phone          string         `json:"phone"`
	Position       string         `json:"position"`
	Salary         pgtype.Numeric `json:"salary"`
	DailyWage      pgtype.Numeric `json:"daily_wage"`
	StartDate      pgtype.Date    `json:"start_date"`
	Description    string         `json:"description"`
	IsActive       bool           `json:"is_active"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.OrganizationID,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Salary,
		arg.DailyWage,
		arg.StartDate,
		arg.Description,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
	)
	return i, err
}
