// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveEmployee = `-- name: ArchiveEmployee :execrows
UPDATE employees SET is_active = false, archived_at = now() WHERE id = $1 AND organization_id = $2
`

type ArchiveEmployeeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ArchiveEmployee(ctx context.Context, arg ArchiveEmployeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveEmployee, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (organization_id, full_name, phone, position, salary, daily_wage, start_date, description, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id, user_id
`

type CreateEmployeeParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	FullName       string         `json:"full_name"`
	Phone          string         `json:"phone"`
	Position       string         `json:"position"`
	Salary         pgtype.Numeric `json:"salary"`
	DailyWage      pgtype.Numeric `json:"daily_wage"`
	StartDate      pgtype.Date    `json:"start_date"`
	Description    string         `json:"description"`
	UserID         pgtype.UUID    `json:"user_id"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OrganizationID,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Salary,
		arg.DailyWage,
		arg.StartDate,
		arg.Description,
		arg.UserID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.UserID,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id, user_id FROM employees WHERE id = $1 AND organization_id = $2
`

type GetEmployeeByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, arg GetEmployeeByIDParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, arg.ID, arg.OrganizationID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.UserID,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id, user_id FROM employees WHERE user_id = $1 AND organization_id = $2
`

type GetEmployeeByUserIDParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// GET /tasks/mine'ın "bana ATANAN görevler" çözümlemesinin TEK kaynağı --
// giriş yapan kullanıcının bağlı olduğu personel kaydını (varsa) bulur.
// Bağlantısız bir kullanıcı için 0 satır döner (pgx.ErrNoRows) -- çağıran
// bunu "hiç göreve atanmamış" olarak ele alır (boş liste, ASLA tüm
// projelerin görevlerine düşmez).
func (q *Queries) GetEmployeeByUserID(ctx context.Context, arg GetEmployeeByUserIDParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, arg.UserID, arg.OrganizationID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.UserID,
	)
	return i, err
}

const getEmployeeForUpdate = `-- name: GetEmployeeForUpdate :one
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id, user_id FROM employees WHERE id = $1 AND organization_id = $2 FOR UPDATE
`

type GetEmployeeForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Ücret değişikliğini (eski -> yeni) aynı transaction içinde güvenle
// karşılaştırmak için satırı kilitler (bkz. EmployeeService.Update).
func (q *Queries) GetEmployeeForUpdate(ctx context.Context, arg GetEmployeeForUpdateParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeForUpdate, arg.ID, arg.OrganizationID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.UserID,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id, user_id FROM employees
WHERE organization_id = $1
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
ORDER BY full_name ASC
`

type ListEmployeesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	IsActive       *bool       `json:"is_active"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.OrganizationID, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Position,
			&i.Salary,
			&i.DailyWage,
			&i.StartDate,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.OrganizationID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET full_name = $3, phone = $4, position = $5, salary = $6, daily_wage = $7,
    start_date = $8, description = $9, is_active = $10, user_id = $11,
    archived_at = CASE WHEN $10::boolean THEN NULL ELSE COALESCE(archived_at, now()) END
WHERE id = $1 AND organization_id = $2
RETURNING id, full_name, phone, position, salary, daily_wage, start_date, is_active, description, created_at, updated_at, archived_at, organization_id, user_id
`

type UpdateEmployeeParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	FullName       string         `json:"full_name"`
	Phone          string         `json:"phone"`
	Position       string         `json:"position"`
	Salary         pgtype.Numeric `json:"salary"`
	DailyWage      pgtype.Numeric `json:"daily_wage"`
	StartDate      pgtype.Date    `json:"start_date"`
	Description    string         `json:"description"`
	IsActive       bool           `json:"is_active"`
	UserID         pgtype.UUID    `json:"user_id"`
}

// archived_at, is_active ile TUTARLI tutulur: "Pasifleştir" (ArchiveEmployee)
// archived_at'i dolduruyordu ama formdan yeniden "Aktif" yapılan personelde
// temizlenmiyor, "Aktif" işareti kaldırılınca da hiç dolmuyordu -- ana sayfa
// archived_at'e baktığı için aktif bir personel orada arşivli görünüyordu.
// Pasife alınırken mevcut arşiv zamanı korunur (ilk pasifleştirme anı).
func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.OrganizationID,
		arg.FullName,
		arg.Phone,
		arg.Position,
		arg.Salary,
		arg.DailyWage,
		arg.StartDate,
		arg.Description,
		arg.IsActive,
		arg.UserID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Position,
		&i.Salary,
		&i.DailyWage,
		&i.StartDate,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.UserID,
	)
	return i, err
}
