// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeedbackMessages = `-- name: CountFeedbackMessages :one
SELECT count(*) AS total, count(*) FILTER (WHERE read_at IS NULL) AS unread FROM feedback_messages
`

type CountFeedbackMessagesRow struct {
	Total  int64 `json:"total"`
	Unread int64 `json:"unread"`
}

func (q *Queries) CountFeedbackMessages(ctx context.Context) (CountFeedbackMessagesRow, error) {
	row := q.db.QueryRow(ctx, countFeedbackMessages)
	var i CountFeedbackMessagesRow
	err := row.Scan(&i.Total, &i.Unread)
	return i, err
}

const createFeedbackMessage = `-- name: CreateFeedbackMessage :one
INSERT INTO feedback_messages (organization_id, user_id, user_name, category, body, app_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, user_id, user_name, category, body, app_version, read_at, created_at
`

type CreateFeedbackMessageParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	UserName       string      `json:"user_name"`
	Category       string      `json:"category"`
	Body           string      `json:"body"`
	AppVersion     string      `json:"app_version"`
}

func (q *Queries) CreateFeedbackMessage(ctx context.Context, arg CreateFeedbackMessageParams) (FeedbackMessage, error) {
	row := q.db.QueryRow(ctx, createFeedbackMessage,
		arg.OrganizationID,
		arg.UserID,
		arg.UserName,
		arg.Category,
		arg.Body,
		arg.AppVersion,
	)
	var i FeedbackMessage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.UserName,
		&i.Category,
		&i.Body,
		&i.AppVersion,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedbackMessages = `-- name: ListFeedbackMessages :many
SELECT f.id, f.organization_id, f.user_id, f.user_name, f.category, f.body, f.app_version, f.read_at, f.created_at, o.name AS organization_name
FROM feedback_messages f
JOIN organizations o ON o.id = f.organization_id
WHERE (NOT $1::bool OR f.read_at IS NULL)
ORDER BY f.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListFeedbackMessagesParams struct {
	OnlyUnread bool  `json:"only_unread"`
	SkipRows   int32 `json:"skip_rows"`
	MaxRows    int32 `json:"max_rows"`
}

type ListFeedbackMessagesRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	UserName         string             `json:"user_name"`
	Category         string             `json:"category"`
	Body             string             `json:"body"`
	AppVersion       string             `json:"app_version"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationName string             `json:"organization_name"`
}

// Super Admin listesi: en yeni önce; only_unread true ise yalnızca okunmamış.
func (q *Queries) ListFeedbackMessages(ctx context.Context, arg ListFeedbackMessagesParams) ([]ListFeedbackMessagesRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackMessages, arg.OnlyUnread, arg.SkipRows, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedbackMessagesRow
	for rows.Next() {
		var i ListFeedbackMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.UserName,
			&i.Category,
			&i.Body,
			&i.AppVersion,
			&i.ReadAt,
			&i.CreatedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedbackMessageRead = `-- name: MarkFeedbackMessageRead :execrows
UPDATE feedback_messages SET read_at = now() WHERE id = $1 AND read_at IS NULL
`

func (q *Queries) MarkFeedbackMessageRead(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markFeedbackMessageRead, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
