// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceLog struct {
	ID         pgtype.UUID        `json:"id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	Date       pgtype.Date        `json:"date"`
	CheckIn    string             `json:"check_in"`
	CheckOut   string             `json:"check_out"`
	WorkHours  pgtype.Numeric     `json:"work_hours"`
	Status     string             `json:"status"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Employee struct {
	ID          pgtype.UUID        `json:"id"`
	FullName    string             `json:"full_name"`
	Phone       string             `json:"phone"`
	Position    string             `json:"position"`
	Salary      pgtype.Numeric     `json:"salary"`
	DailyWage   pgtype.Numeric     `json:"daily_wage"`
	StartDate   pgtype.Date        `json:"start_date"`
	IsActive    bool               `json:"is_active"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type Offer struct {
	ID              pgtype.UUID        `json:"id"`
	OfferNo         string             `json:"offer_no"`
	CustomerName    string             `json:"customer_name"`
	CustomerPhone   string             `json:"customer_phone"`
	CustomerEmail   string             `json:"customer_email"`
	CustomerAddress string             `json:"customer_address"`
	OfferDate       pgtype.Date        `json:"offer_date"`
	ValidUntil      pgtype.Date        `json:"valid_until"`
	Subtotal        pgtype.Numeric     `json:"subtotal"`
	VatRate         pgtype.Numeric     `json:"vat_rate"`
	VatAmount       pgtype.Numeric     `json:"vat_amount"`
	GrandTotal      pgtype.Numeric     `json:"grand_total"`
	Notes           string             `json:"notes"`
	Status          string             `json:"status"`
	IsPassive       bool               `json:"is_passive"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OfferCounter struct {
	Year int32 `json:"year"`
	Seq  int32 `json:"seq"`
}

type OfferItem struct {
	ID          pgtype.UUID    `json:"id"`
	OfferID     pgtype.UUID    `json:"offer_id"`
	ProductID   pgtype.UUID    `json:"product_id"`
	ProductName string         `json:"product_name"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	LineTotal   pgtype.Numeric `json:"line_total"`
	SortOrder   int32          `json:"sort_order"`
}

type Product struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Description    string             `json:"description"`
	Category       string             `json:"category"`
	Source         *string            `json:"source"`
	SourcePrice    pgtype.Numeric     `json:"source_price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProductPriceHistory struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	OldPrice  pgtype.Numeric     `json:"old_price"`
	NewPrice  pgtype.Numeric     `json:"new_price"`
	Note      string             `json:"note"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}
