// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Description    string             `json:"description"`
	Category       string             `json:"category"`
	Source         *string            `json:"source"`
	SourcePrice    pgtype.Numeric     `json:"source_price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProductPriceHistory struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	OldPrice  pgtype.Numeric     `json:"old_price"`
	NewPrice  pgtype.Numeric     `json:"new_price"`
	Note      string             `json:"note"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}
