// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceLog struct {
	ID             pgtype.UUID        `json:"id"`
	EmployeeID     pgtype.UUID        `json:"employee_id"`
	Date           pgtype.Date        `json:"date"`
	CheckIn        string             `json:"check_in"`
	CheckOut       string             `json:"check_out"`
	WorkHours      pgtype.Numeric     `json:"work_hours"`
	Status         string             `json:"status"`
	Note           string             `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

type Customer struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Name           string             `json:"name"`
	Phone          string             `json:"phone"`
	Email          string             `json:"email"`
	Address        string             `json:"address"`
	TaxOffice      string             `json:"tax_office"`
	TaxNumber      string             `json:"tax_number"`
	Notes          string             `json:"notes"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID             pgtype.UUID        `json:"id"`
	FullName       string             `json:"full_name"`
	Phone          string             `json:"phone"`
	Position       string             `json:"position"`
	Salary         pgtype.Numeric     `json:"salary"`
	DailyWage      pgtype.Numeric     `json:"daily_wage"`
	StartDate      pgtype.Date        `json:"start_date"`
	IsActive       bool               `json:"is_active"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

type Offer struct {
	ID                pgtype.UUID        `json:"id"`
	OfferNo           string             `json:"offer_no"`
	OfferDate         pgtype.Date        `json:"offer_date"`
	Status            string             `json:"status"`
	IsPassive         bool               `json:"is_passive"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
}

type OfferCounter struct {
	Year           int32       `json:"year"`
	Seq            int32       `json:"seq"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type OfferEmailLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OfferID        pgtype.UUID        `json:"offer_id"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	ShareLinkID    pgtype.UUID        `json:"share_link_id"`
	Recipient      string             `json:"recipient"`
	Subject        string             `json:"subject"`
	Status         string             `json:"status"`
	ErrorMessage   string             `json:"error_message"`
	SentBy         pgtype.UUID        `json:"sent_by"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

type OfferEvent struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OfferID        pgtype.UUID        `json:"offer_id"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	EventType      string             `json:"event_type"`
	UserID         pgtype.UUID        `json:"user_id"`
	Metadata       []byte             `json:"metadata"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      string             `json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OfferRevision struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	OfferID         pgtype.UUID        `json:"offer_id"`
	RevisionNo      int32              `json:"revision_no"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	CustomerName    string             `json:"customer_name"`
	CustomerPhone   string             `json:"customer_phone"`
	CustomerEmail   string             `json:"customer_email"`
	CustomerAddress string             `json:"customer_address"`
	ValidUntil      pgtype.Date        `json:"valid_until"`
	Subtotal        pgtype.Numeric     `json:"subtotal"`
	DiscountType    string             `json:"discount_type"`
	DiscountValue   pgtype.Numeric     `json:"discount_value"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	VatRate         pgtype.Numeric     `json:"vat_rate"`
	VatAmount       pgtype.Numeric     `json:"vat_amount"`
	GrandTotal      pgtype.Numeric     `json:"grand_total"`
	Currency        string             `json:"currency"`
	Notes           string             `json:"notes"`
	Status          string             `json:"status"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type OfferRevisionItem struct {
	ID            pgtype.UUID    `json:"id"`
	RevisionID    pgtype.UUID    `json:"revision_id"`
	ProductID     pgtype.UUID    `json:"product_id"`
	ProductName   string         `json:"product_name"`
	Quantity      pgtype.Numeric `json:"quantity"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	DiscountType  string         `json:"discount_type"`
	DiscountValue pgtype.Numeric `json:"discount_value"`
	LineTotal     pgtype.Numeric `json:"line_total"`
	SortOrder     int32          `json:"sort_order"`
}

type OfferShareLink struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OfferID        pgtype.UUID        `json:"offer_id"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	Token          pgtype.UUID        `json:"token"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Description    string             `json:"description"`
	Category       string             `json:"category"`
	Source         *string            `json:"source"`
	SourcePrice    pgtype.Numeric     `json:"source_price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

type ProductPriceHistory struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	OldPrice  pgtype.Numeric     `json:"old_price"`
	NewPrice  pgtype.Numeric     `json:"new_price"`
	Note      string             `json:"note"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type Project struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	ProjectNo        string             `json:"project_no"`
	Name             string             `json:"name"`
	ProjectType      string             `json:"project_type"`
	SourceOfferID    pgtype.UUID        `json:"source_offer_id"`
	SourceRevisionID pgtype.UUID        `json:"source_revision_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	CustomerName     string             `json:"customer_name"`
	CustomerPhone    string             `json:"customer_phone"`
	CustomerEmail    string             `json:"customer_email"`
	CustomerAddress  string             `json:"customer_address"`
	ContractAmount   pgtype.Numeric     `json:"contract_amount"`
	Currency         string             `json:"currency"`
	Status           string             `json:"status"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Description      string             `json:"description"`
	InternalNotes    string             `json:"internal_notes"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProjectCounter struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
	Seq            int32       `json:"seq"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SmtpSetting struct {
	Host           string             `json:"host"`
	Port           int32              `json:"port"`
	Username       string             `json:"username"`
	PasswordEnc    string             `json:"password_enc"`
	FromEmail      string             `json:"from_email"`
	FromName       string             `json:"from_name"`
	UseTls         bool               `json:"use_tls"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Username       string             `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	FullName       string             `json:"full_name"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}
