// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOffers = `-- name: CountOffers :one
SELECT count(*) FROM offers WHERE organization_id = $1 AND is_passive = $2
`

type CountOffersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	IsPassive      bool        `json:"is_passive"`
}

func (q *Queries) CountOffers(ctx context.Context, arg CountOffersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOffers, arg.OrganizationID, arg.IsPassive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers (organization_id, offer_no, status, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, offer_no, offer_date, status, is_passive, created_by, created_at, updated_at, organization_id, current_revision_id
`

type CreateOfferParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	OfferNo        string      `json:"offer_no"`
	Status         string      `json:"status"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRow(ctx, createOffer,
		arg.OrganizationID,
		arg.OfferNo,
		arg.Status,
		arg.CreatedBy,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferNo,
		&i.OfferDate,
		&i.Status,
		&i.IsPassive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.CurrentRevisionID,
	)
	return i, err
}

const deleteOffer = `-- name: DeleteOffer :exec
DELETE FROM offers WHERE id = $1 AND organization_id = $2
`

type DeleteOfferParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteOffer(ctx context.Context, arg DeleteOfferParams) error {
	_, err := q.db.Exec(ctx, deleteOffer, arg.ID, arg.OrganizationID)
	return err
}

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, offer_no, offer_date, status, is_passive, created_by, created_at, updated_at, organization_id, current_revision_id FROM offers WHERE id = $1 AND organization_id = $2
`

type GetOfferByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetOfferByID(ctx context.Context, arg GetOfferByIDParams) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferByID, arg.ID, arg.OrganizationID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferNo,
		&i.OfferDate,
		&i.Status,
		&i.IsPassive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.CurrentRevisionID,
	)
	return i, err
}

const listOffers = `-- name: ListOffers :many
SELECT o.id, o.offer_no, o.offer_date, o.status, o.is_passive, o.created_by, o.created_at, o.updated_at, o.organization_id, o.current_revision_id, r.customer_name, r.grand_total, r.revision_no
FROM offers o
JOIN offer_revisions r ON r.id = o.current_revision_id
WHERE o.organization_id = $1 AND o.is_passive = $2
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $4
`

type ListOffersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	IsPassive      bool        `json:"is_passive"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListOffersRow struct {
	ID                pgtype.UUID        `json:"id"`
	OfferNo           string             `json:"offer_no"`
	OfferDate         pgtype.Date        `json:"offer_date"`
	Status            string             `json:"status"`
	IsPassive         bool               `json:"is_passive"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CustomerName      string             `json:"customer_name"`
	GrandTotal        pgtype.Numeric     `json:"grand_total"`
	RevisionNo        int32              `json:"revision_no"`
}

func (q *Queries) ListOffers(ctx context.Context, arg ListOffersParams) ([]ListOffersRow, error) {
	rows, err := q.db.Query(ctx, listOffers,
		arg.OrganizationID,
		arg.IsPassive,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersRow
	for rows.Next() {
		var i ListOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.OfferNo,
			&i.OfferDate,
			&i.Status,
			&i.IsPassive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.CurrentRevisionID,
			&i.CustomerName,
			&i.GrandTotal,
			&i.RevisionNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOfferSeq = `-- name: NextOfferSeq :one
INSERT INTO offer_counters (organization_id, year, seq) VALUES ($1, $2, 1)
ON CONFLICT (organization_id, year) DO UPDATE SET seq = offer_counters.seq + 1
RETURNING seq
`

type NextOfferSeqParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
}

func (q *Queries) NextOfferSeq(ctx context.Context, arg NextOfferSeqParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextOfferSeq, arg.OrganizationID, arg.Year)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const setOfferCurrentRevision = `-- name: SetOfferCurrentRevision :exec
UPDATE offers SET current_revision_id = $2, status = $3 WHERE id = $1
`

type SetOfferCurrentRevisionParams struct {
	ID                pgtype.UUID `json:"id"`
	CurrentRevisionID pgtype.UUID `json:"current_revision_id"`
	Status            string      `json:"status"`
}

func (q *Queries) SetOfferCurrentRevision(ctx context.Context, arg SetOfferCurrentRevisionParams) error {
	_, err := q.db.Exec(ctx, setOfferCurrentRevision, arg.ID, arg.CurrentRevisionID, arg.Status)
	return err
}

const setOfferPassive = `-- name: SetOfferPassive :exec
UPDATE offers SET is_passive = $3 WHERE id = $1 AND organization_id = $2
`

type SetOfferPassiveParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	IsPassive      bool        `json:"is_passive"`
}

func (q *Queries) SetOfferPassive(ctx context.Context, arg SetOfferPassiveParams) error {
	_, err := q.db.Exec(ctx, setOfferPassive, arg.ID, arg.OrganizationID, arg.IsPassive)
	return err
}
