// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offer_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOfferEvent = `-- name: CreateOfferEvent :one
INSERT INTO offer_events (organization_id, offer_id, revision_id, event_type, user_id, metadata, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, offer_id, revision_id, event_type, user_id, metadata, ip_address, user_agent, created_at
`

type CreateOfferEventParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	OfferID        pgtype.UUID `json:"offer_id"`
	RevisionID     pgtype.UUID `json:"revision_id"`
	EventType      string      `json:"event_type"`
	UserID         pgtype.UUID `json:"user_id"`
	Metadata       []byte      `json:"metadata"`
	IpAddress      string      `json:"ip_address"`
	UserAgent      string      `json:"user_agent"`
}

func (q *Queries) CreateOfferEvent(ctx context.Context, arg CreateOfferEventParams) (OfferEvent, error) {
	row := q.db.QueryRow(ctx, createOfferEvent,
		arg.OrganizationID,
		arg.OfferID,
		arg.RevisionID,
		arg.EventType,
		arg.UserID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i OfferEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OfferID,
		&i.RevisionID,
		&i.EventType,
		&i.UserID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listOfferEvents = `-- name: ListOfferEvents :many
SELECT id, organization_id, offer_id, revision_id, event_type, user_id, metadata, ip_address, user_agent, created_at FROM offer_events WHERE offer_id = $1 AND organization_id = $2 ORDER BY created_at ASC
`

type ListOfferEventsParams struct {
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListOfferEvents(ctx context.Context, arg ListOfferEventsParams) ([]OfferEvent, error) {
	rows, err := q.db.Query(ctx, listOfferEvents, arg.OfferID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferEvent
	for rows.Next() {
		var i OfferEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OfferID,
			&i.RevisionID,
			&i.EventType,
			&i.UserID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const offerRevisionFirstOpenLogged = `-- name: OfferRevisionFirstOpenLogged :one
SELECT EXISTS (
    SELECT 1 FROM offer_events
    WHERE offer_id = $1 AND revision_id = $2 AND event_type = 'customer_viewed'
      AND metadata @> '{"first_open": true}'::jsonb
)::boolean AS logged
`

type OfferRevisionFirstOpenLoggedParams struct {
	OfferID    pgtype.UUID `json:"offer_id"`
	RevisionID pgtype.UUID `json:"revision_id"`
}

// Müşterinin bu revizyonu karar beklerken İLK açışı zaten kaydedildi mi
// (first_open işaretli customer_viewed, bkz. OfferService.recordCustomerView).
// idx_offer_events_offer_id ile yalnızca teklifin kendi olayları taranır.
func (q *Queries) OfferRevisionFirstOpenLogged(ctx context.Context, arg OfferRevisionFirstOpenLoggedParams) (bool, error) {
	row := q.db.QueryRow(ctx, offerRevisionFirstOpenLogged, arg.OfferID, arg.RevisionID)
	var logged bool
	err := row.Scan(&logged)
	return logged, err
}
