// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offer_share_links.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO offer_share_links (organization_id, offer_id, revision_id, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, offer_id, revision_id, token, created_by, created_at, expires_at, revoked_at
`

type CreateShareLinkParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	OfferID        pgtype.UUID        `json:"offer_id"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (OfferShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.OrganizationID,
		arg.OfferID,
		arg.RevisionID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i OfferShareLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OfferID,
		&i.RevisionID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, organization_id, offer_id, revision_id, token, created_by, created_at, expires_at, revoked_at FROM offer_share_links WHERE token = $1
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token pgtype.UUID) (OfferShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByToken, token)
	var i OfferShareLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OfferID,
		&i.RevisionID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listShareLinksByOffer = `-- name: ListShareLinksByOffer :many
SELECT id, organization_id, offer_id, revision_id, token, created_by, created_at, expires_at, revoked_at FROM offer_share_links WHERE offer_id = $1 AND organization_id = $2 ORDER BY created_at DESC
`

type ListShareLinksByOfferParams struct {
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListShareLinksByOffer(ctx context.Context, arg ListShareLinksByOfferParams) ([]OfferShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinksByOffer, arg.OfferID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferShareLink
	for rows.Next() {
		var i OfferShareLink
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OfferID,
			&i.RevisionID,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShareLink = `-- name: RevokeShareLink :one
UPDATE offer_share_links SET revoked_at = now()
WHERE id = $1 AND organization_id = $2 AND revoked_at IS NULL
RETURNING id, organization_id, offer_id, revision_id, token, created_by, created_at, expires_at, revoked_at
`

type RevokeShareLinkParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) RevokeShareLink(ctx context.Context, arg RevokeShareLinkParams) (OfferShareLink, error) {
	row := q.db.QueryRow(ctx, revokeShareLink, arg.ID, arg.OrganizationID)
	var i OfferShareLink
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OfferID,
		&i.RevisionID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeShareLinksForOtherRevisions = `-- name: RevokeShareLinksForOtherRevisions :many
UPDATE offer_share_links SET revoked_at = now()
WHERE offer_id = $1 AND revision_id <> $2 AND revoked_at IS NULL
RETURNING id, organization_id, offer_id, revision_id, token, created_by, created_at, expires_at, revoked_at
`

type RevokeShareLinksForOtherRevisionsParams struct {
	OfferID    pgtype.UUID `json:"offer_id"`
	RevisionID pgtype.UUID `json:"revision_id"`
}

func (q *Queries) RevokeShareLinksForOtherRevisions(ctx context.Context, arg RevokeShareLinksForOtherRevisionsParams) ([]OfferShareLink, error) {
	rows, err := q.db.Query(ctx, revokeShareLinksForOtherRevisions, arg.OfferID, arg.RevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferShareLink
	for rows.Next() {
		var i OfferShareLink
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OfferID,
			&i.RevisionID,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
