// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offer_email_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailLog = `-- name: CreateEmailLog :one
INSERT INTO offer_email_logs (organization_id, offer_id, revision_id, share_link_id, recipient, subject, status, error_message, sent_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, offer_id, revision_id, share_link_id, recipient, subject, status, error_message, sent_by, sent_at
`

type CreateEmailLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	OfferID        pgtype.UUID `json:"offer_id"`
	RevisionID     pgtype.UUID `json:"revision_id"`
	ShareLinkID    pgtype.UUID `json:"share_link_id"`
	Recipient      string      `json:"recipient"`
	Subject        string      `json:"subject"`
	Status         string      `json:"status"`
	ErrorMessage   string      `json:"error_message"`
	SentBy         pgtype.UUID `json:"sent_by"`
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (OfferEmailLog, error) {
	row := q.db.QueryRow(ctx, createEmailLog,
		arg.OrganizationID,
		arg.OfferID,
		arg.RevisionID,
		arg.ShareLinkID,
		arg.Recipient,
		arg.Subject,
		arg.Status,
		arg.ErrorMessage,
		arg.SentBy,
	)
	var i OfferEmailLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OfferID,
		&i.RevisionID,
		&i.ShareLinkID,
		&i.Recipient,
		&i.Subject,
		&i.Status,
		&i.ErrorMessage,
		&i.SentBy,
		&i.SentAt,
	)
	return i, err
}

const listEmailLogsByOffer = `-- name: ListEmailLogsByOffer :many
SELECT id, organization_id, offer_id, revision_id, share_link_id, recipient, subject, status, error_message, sent_by, sent_at FROM offer_email_logs WHERE offer_id = $1 AND organization_id = $2 ORDER BY sent_at DESC
`

type ListEmailLogsByOfferParams struct {
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListEmailLogsByOffer(ctx context.Context, arg ListEmailLogsByOfferParams) ([]OfferEmailLog, error) {
	rows, err := q.db.Query(ctx, listEmailLogsByOffer, arg.OfferID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferEmailLog
	for rows.Next() {
		var i OfferEmailLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OfferID,
			&i.RevisionID,
			&i.ShareLinkID,
			&i.Recipient,
			&i.Subject,
			&i.Status,
			&i.ErrorMessage,
			&i.SentBy,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
