// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOffers = `-- name: CountOffers :one
SELECT count(*) FROM offers WHERE is_passive = $1
`

func (q *Queries) CountOffers(ctx context.Context, isPassive bool) (int64, error) {
	row := q.db.QueryRow(ctx, countOffers, isPassive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers (
    offer_no, customer_name, customer_phone, customer_email, customer_address,
    offer_date, valid_until, subtotal, vat_rate, vat_amount, grand_total,
    notes, status, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, offer_no, customer_name, customer_phone, customer_email, customer_address, offer_date, valid_until, subtotal, vat_rate, vat_amount, grand_total, notes, status, is_passive, created_by, created_at, updated_at, share_token
`

type CreateOfferParams struct {
	OfferNo         string         `json:"offer_no"`
	CustomerName    string         `json:"customer_name"`
	CustomerPhone   string         `json:"customer_phone"`
	CustomerEmail   string         `json:"customer_email"`
	CustomerAddress string         `json:"customer_address"`
	OfferDate       pgtype.Date    `json:"offer_date"`
	ValidUntil      pgtype.Date    `json:"valid_until"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	VatRate         pgtype.Numeric `json:"vat_rate"`
	VatAmount       pgtype.Numeric `json:"vat_amount"`
	GrandTotal      pgtype.Numeric `json:"grand_total"`
	Notes           string         `json:"notes"`
	Status          string         `json:"status"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRow(ctx, createOffer,
		arg.OfferNo,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerEmail,
		arg.CustomerAddress,
		arg.OfferDate,
		arg.ValidUntil,
		arg.Subtotal,
		arg.VatRate,
		arg.VatAmount,
		arg.GrandTotal,
		arg.Notes,
		arg.Status,
		arg.CreatedBy,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferNo,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.OfferDate,
		&i.ValidUntil,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.Notes,
		&i.Status,
		&i.IsPassive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const createOfferItem = `-- name: CreateOfferItem :one
INSERT INTO offer_items (offer_id, product_id, product_name, quantity, unit_price, line_total, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, offer_id, product_id, product_name, quantity, unit_price, line_total, sort_order
`

type CreateOfferItemParams struct {
	OfferID     pgtype.UUID    `json:"offer_id"`
	ProductID   pgtype.UUID    `json:"product_id"`
	ProductName string         `json:"product_name"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	LineTotal   pgtype.Numeric `json:"line_total"`
	SortOrder   int32          `json:"sort_order"`
}

func (q *Queries) CreateOfferItem(ctx context.Context, arg CreateOfferItemParams) (OfferItem, error) {
	row := q.db.QueryRow(ctx, createOfferItem,
		arg.OfferID,
		arg.ProductID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.SortOrder,
	)
	var i OfferItem
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.SortOrder,
	)
	return i, err
}

const deleteOffer = `-- name: DeleteOffer :exec
DELETE FROM offers WHERE id = $1
`

func (q *Queries) DeleteOffer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOffer, id)
	return err
}

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, offer_no, customer_name, customer_phone, customer_email, customer_address, offer_date, valid_until, subtotal, vat_rate, vat_amount, grand_total, notes, status, is_passive, created_by, created_at, updated_at, share_token FROM offers WHERE id = $1
`

func (q *Queries) GetOfferByID(ctx context.Context, id pgtype.UUID) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferByID, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferNo,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.OfferDate,
		&i.ValidUntil,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.Notes,
		&i.Status,
		&i.IsPassive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const getOfferByShareToken = `-- name: GetOfferByShareToken :one
SELECT id, offer_no, customer_name, customer_phone, customer_email, customer_address, offer_date, valid_until, subtotal, vat_rate, vat_amount, grand_total, notes, status, is_passive, created_by, created_at, updated_at, share_token FROM offers WHERE share_token = $1
`

func (q *Queries) GetOfferByShareToken(ctx context.Context, shareToken pgtype.UUID) (Offer, error) {
	row := q.db.QueryRow(ctx, getOfferByShareToken, shareToken)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferNo,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.OfferDate,
		&i.ValidUntil,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.Notes,
		&i.Status,
		&i.IsPassive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}

const listOfferItems = `-- name: ListOfferItems :many
SELECT id, offer_id, product_id, product_name, quantity, unit_price, line_total, sort_order FROM offer_items WHERE offer_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListOfferItems(ctx context.Context, offerID pgtype.UUID) ([]OfferItem, error) {
	rows, err := q.db.Query(ctx, listOfferItems, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferItem
	for rows.Next() {
		var i OfferItem
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffers = `-- name: ListOffers :many
SELECT id, offer_no, customer_name, customer_phone, customer_email, customer_address, offer_date, valid_until, subtotal, vat_rate, vat_amount, grand_total, notes, status, is_passive, created_by, created_at, updated_at, share_token FROM offers
WHERE is_passive = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOffersParams struct {
	IsPassive bool  `json:"is_passive"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListOffers(ctx context.Context, arg ListOffersParams) ([]Offer, error) {
	rows, err := q.db.Query(ctx, listOffers, arg.IsPassive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.OfferNo,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerEmail,
			&i.CustomerAddress,
			&i.OfferDate,
			&i.ValidUntil,
			&i.Subtotal,
			&i.VatRate,
			&i.VatAmount,
			&i.GrandTotal,
			&i.Notes,
			&i.Status,
			&i.IsPassive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShareToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOfferSeq = `-- name: NextOfferSeq :one
INSERT INTO offer_counters (year, seq) VALUES ($1, 1)
ON CONFLICT (year) DO UPDATE SET seq = offer_counters.seq + 1
RETURNING seq
`

func (q *Queries) NextOfferSeq(ctx context.Context, year int32) (int32, error) {
	row := q.db.QueryRow(ctx, nextOfferSeq, year)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const setOfferPassive = `-- name: SetOfferPassive :exec
UPDATE offers SET is_passive = $2 WHERE id = $1
`

type SetOfferPassiveParams struct {
	ID        pgtype.UUID `json:"id"`
	IsPassive bool        `json:"is_passive"`
}

func (q *Queries) SetOfferPassive(ctx context.Context, arg SetOfferPassiveParams) error {
	_, err := q.db.Exec(ctx, setOfferPassive, arg.ID, arg.IsPassive)
	return err
}

const updateOfferStatus = `-- name: UpdateOfferStatus :one
UPDATE offers SET status = $2 WHERE id = $1
RETURNING id, offer_no, customer_name, customer_phone, customer_email, customer_address, offer_date, valid_until, subtotal, vat_rate, vat_amount, grand_total, notes, status, is_passive, created_by, created_at, updated_at, share_token
`

type UpdateOfferStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOfferStatus(ctx context.Context, arg UpdateOfferStatusParams) (Offer, error) {
	row := q.db.QueryRow(ctx, updateOfferStatus, arg.ID, arg.Status)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferNo,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.OfferDate,
		&i.ValidUntil,
		&i.Subtotal,
		&i.VatRate,
		&i.VatAmount,
		&i.GrandTotal,
		&i.Notes,
		&i.Status,
		&i.IsPassive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareToken,
	)
	return i, err
}
