// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setSuperAdminPassword = `-- name: SetSuperAdminPassword :one
UPDATE users
SET password_hash = $2, must_change_password = false, updated_at = now()
WHERE username = $1 AND role = 'super_admin' AND organization_id IS NULL AND deleted_at IS NULL
RETURNING id
`

type SetSuperAdminPasswordParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

// Super Admin'in şifresi -- yalnızca sunucudaki CLI'dan (cmd/reset-platform-admin-password).
// Super Admin'in firması yok (organization_id NULL), bu yüzden firmaya bağlı
// UpdateUserPassword onu bulamaz; rol ve silinmemişlik burada ayrıca
// doğrulanır ki araç yanlışlıkla bir firma kullanıcısının şifresini
// değiştiremesin.
func (q *Queries) SetSuperAdminPassword(ctx context.Context, arg SetSuperAdminPasswordParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, setSuperAdminPassword, arg.Username, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
