// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_plans.sql

package sqlc

import (
	"context"
)

const getPlanByCode = `-- name: GetPlanByCode :one
SELECT code, name, is_active, max_users, max_projects, sort_order, created_at, updated_at FROM platform_plans WHERE code = $1
`

func (q *Queries) GetPlanByCode(ctx context.Context, code string) (PlatformPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByCode, code)
	var i PlatformPlan
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.MaxUsers,
		&i.MaxProjects,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT code, name, is_active, max_users, max_projects, sort_order, created_at, updated_at FROM platform_plans WHERE is_active = true ORDER BY sort_order
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]PlatformPlan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformPlan
	for rows.Next() {
		var i PlatformPlan
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.MaxUsers,
			&i.MaxProjects,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT code, name, is_active, max_users, max_projects, sort_order, created_at, updated_at FROM platform_plans ORDER BY sort_order
`

func (q *Queries) ListAllPlans(ctx context.Context) ([]PlatformPlan, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformPlan
	for rows.Next() {
		var i PlatformPlan
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.MaxUsers,
			&i.MaxProjects,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
