// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_audit_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO platform_audit_events (actor_user_id, action, target_organization_id, target_user_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor_user_id, action, target_organization_id, target_user_id, metadata, created_at
`

type InsertAuditEventParams struct {
	ActorUserID          pgtype.UUID `json:"actor_user_id"`
	Action               string      `json:"action"`
	TargetOrganizationID pgtype.UUID `json:"target_organization_id"`
	TargetUserID         pgtype.UUID `json:"target_user_id"`
	Metadata             []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (PlatformAuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ActorUserID,
		arg.Action,
		arg.TargetOrganizationID,
		arg.TargetUserID,
		arg.Metadata,
	)
	var i PlatformAuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetOrganizationID,
		&i.TargetUserID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, action, target_organization_id, target_user_id, metadata, created_at FROM platform_audit_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]PlatformAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAuditEvent
	for rows.Next() {
		var i PlatformAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetOrganizationID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsForOrganization = `-- name: ListAuditEventsForOrganization :many
SELECT id, actor_user_id, action, target_organization_id, target_user_id, metadata, created_at FROM platform_audit_events
WHERE target_organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsForOrganizationParams struct {
	TargetOrganizationID pgtype.UUID `json:"target_organization_id"`
	Limit                int32       `json:"limit"`
	Offset               int32       `json:"offset"`
}

func (q *Queries) ListAuditEventsForOrganization(ctx context.Context, arg ListAuditEventsForOrganizationParams) ([]PlatformAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsForOrganization, arg.TargetOrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAuditEvent
	for rows.Next() {
		var i PlatformAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetOrganizationID,
			&i.TargetUserID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
