// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_sources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSourceProductsNotSyncedNow = `-- name: CountSourceProductsNotSyncedNow :one
SELECT count(*) FROM products
WHERE organization_id = $1 AND source = $2::text
  AND (source_synced_at IS NULL OR source_synced_at < now())
`

type CountSourceProductsNotSyncedNowParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

// Senkron transaction'ı İÇİNDE: bu senkronda görülmeyen (source_synced_at
// now()'dan eski veya NULL) kaynak ürünleri = listeden düşenler.
func (q *Queries) CountSourceProductsNotSyncedNow(ctx context.Context, arg CountSourceProductsNotSyncedNowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSourceProductsNotSyncedNow, arg.OrganizationID, arg.Source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePriceSourceCategoryMarkups = `-- name: DeletePriceSourceCategoryMarkups :exec
DELETE FROM organization_price_source_category_markups
WHERE organization_id = $1 AND source = $2
`

type DeletePriceSourceCategoryMarkupsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

func (q *Queries) DeletePriceSourceCategoryMarkups(ctx context.Context, arg DeletePriceSourceCategoryMarkupsParams) error {
	_, err := q.db.Exec(ctx, deletePriceSourceCategoryMarkups, arg.OrganizationID, arg.Source)
	return err
}

const getOrganizationPriceSource = `-- name: GetOrganizationPriceSource :one

SELECT organization_id, source, markup_percent, auto_sync, last_synced_at, last_status, last_error, last_total, last_created, last_updated, last_unchanged, last_missing, updated_by, created_at, updated_at, last_list_label, last_list_as_of FROM organization_price_sources
WHERE organization_id = $1 AND source = $2
`

type GetOrganizationPriceSourceParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

// Tedarikçi fiyat listesi senkronu (migration 0045). Toplu yazmalar
// unnest(dizi) ile TEK ifadede yapılır -- ~600 ürünlük bir liste için
// satır başına ayrı UPDATE/INSERT gidip gelmesi olmasın. SELECT listesindeki
// birden çok unnest(...) PostgreSQL 10+'da eşzamanlı (satır satır eşleşerek)
// açılır; diziler servis katmanında hep AYNI uzunlukta kurulur. (sqlc çok
// argümanlı unnest(a, b) biçimini tanımadığı için bu biçim kullanılır.)
func (q *Queries) GetOrganizationPriceSource(ctx context.Context, arg GetOrganizationPriceSourceParams) (OrganizationPriceSource, error) {
	row := q.db.QueryRow(ctx, getOrganizationPriceSource, arg.OrganizationID, arg.Source)
	var i OrganizationPriceSource
	err := row.Scan(
		&i.OrganizationID,
		&i.Source,
		&i.MarkupPercent,
		&i.AutoSync,
		&i.LastSyncedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastTotal,
		&i.LastCreated,
		&i.LastUpdated,
		&i.LastUnchanged,
		&i.LastMissing,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastListLabel,
		&i.LastListAsOf,
	)
	return i, err
}

const getPriceSourceListAsOf = `-- name: GetPriceSourceListAsOf :one
SELECT COALESCE(last_list_as_of, last_synced_at)::timestamptz AS as_of
FROM organization_price_sources
WHERE organization_id = $1 AND source = $2
`

type GetPriceSourceListAsOfParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

// Firmanın bu kaynaktaki fiyatlarının VERİ tarihi (yoksa son başarılı
// senkron anı). Satır ya da başarılı senkron yoksa NULL.
func (q *Queries) GetPriceSourceListAsOf(ctx context.Context, arg GetPriceSourceListAsOfParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPriceSourceListAsOf, arg.OrganizationID, arg.Source)
	var as_of pgtype.Timestamptz
	err := row.Scan(&as_of)
	return as_of, err
}

const getPriceSourceSnapshot = `-- name: GetPriceSourceSnapshot :one
SELECT source, origin, as_of, label, items, item_count, saved_at FROM price_source_snapshots WHERE source = $1
`

// Kaynağın son başarılı listesi (bkz. migration 0049).
func (q *Queries) GetPriceSourceSnapshot(ctx context.Context, source string) (PriceSourceSnapshot, error) {
	row := q.db.QueryRow(ctx, getPriceSourceSnapshot, source)
	var i PriceSourceSnapshot
	err := row.Scan(
		&i.Source,
		&i.Origin,
		&i.AsOf,
		&i.Label,
		&i.Items,
		&i.ItemCount,
		&i.SavedAt,
	)
	return i, err
}

const getSyncPriceChangeStats = `-- name: GetSyncPriceChangeStats :one
SELECT (count(*) FILTER (WHERE h.new_price > h.old_price))::int AS increased,
       (count(*) FILTER (WHERE h.new_price < h.old_price))::int AS decreased,
       round(avg((h.new_price - h.old_price) / h.old_price * 100)
             FILTER (WHERE h.new_price > h.old_price AND h.old_price > 0), 2)::numeric AS avg_increase_percent
FROM product_price_history h
JOIN products p ON p.id = h.product_id
WHERE p.organization_id = $1
  AND h.source = $2::text
  AND h.reason = 'supplier'
  AND h.changed_at = $3::timestamptz
`

type GetSyncPriceChangeStatsParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Source         string             `json:"source"`
	ChangedAt      pgtype.Timestamptz `json:"changed_at"`
}

type GetSyncPriceChangeStatsRow struct {
	Increased          int32          `json:"increased"`
	Decreased          int32          `json:"decreased"`
	AvgIncreasePercent pgtype.Numeric `json:"avg_increase_percent"`
}

// Tek bir senkronun (changed_at = o senkronun last_synced_at'i) zam/indirim
// sayıları -- "Son güncellemede N ürüne zam geldi". Yüzdeler satış
// fiyatı (unit_price) üzerinden; eski fiyatı 0 olan satırlar ortalamaya girmez.
func (q *Queries) GetSyncPriceChangeStats(ctx context.Context, arg GetSyncPriceChangeStatsParams) (GetSyncPriceChangeStatsRow, error) {
	row := q.db.QueryRow(ctx, getSyncPriceChangeStats, arg.OrganizationID, arg.Source, arg.ChangedAt)
	var i GetSyncPriceChangeStatsRow
	err := row.Scan(&i.Increased, &i.Decreased, &i.AvgIncreasePercent)
	return i, err
}

const insertPriceHistoryBatch = `-- name: InsertPriceHistoryBatch :exec
INSERT INTO product_price_history (product_id, old_price, new_price, note, reason, source,
    old_source_price, new_source_price)
SELECT u.product_id, u.old_price, u.new_price, $1::text, $2::text,
    $3::text, u.old_source_price, u.new_source_price
FROM (
    SELECT unnest($4::uuid[])          AS product_id,
           unnest($5::numeric[])        AS old_price,
           unnest($6::numeric[])        AS new_price,
           unnest($7::numeric[]) AS old_source_price,
           unnest($8::numeric[]) AS new_source_price
) AS u
`

type InsertPriceHistoryBatchParams struct {
	Note            string           `json:"note"`
	Reason          string           `json:"reason"`
	Source          string           `json:"source"`
	ProductIds      []pgtype.UUID    `json:"product_ids"`
	OldPrices       []pgtype.Numeric `json:"old_prices"`
	NewPrices       []pgtype.Numeric `json:"new_prices"`
	OldSourcePrices []pgtype.Numeric `json:"old_source_prices"`
	NewSourcePrices []pgtype.Numeric `json:"new_source_prices"`
}

// Senkron (reason 'supplier') ve kâr oranı yeniden fiyatlaması ('markup')
// satırları. changed_at varsayılanı now(): aynı transaction'daki tüm
// satırlar aynı anı paylaşır -- zam geçmişi bir senkronu bu anla gruplar.
// Kaynak fiyatı dizilerinde NULL olabilir (hiç senkronlanmamış satır).
func (q *Queries) InsertPriceHistoryBatch(ctx context.Context, arg InsertPriceHistoryBatchParams) error {
	_, err := q.db.Exec(ctx, insertPriceHistoryBatch,
		arg.Note,
		arg.Reason,
		arg.Source,
		arg.ProductIds,
		arg.OldPrices,
		arg.NewPrices,
		arg.OldSourcePrices,
		arg.NewSourcePrices,
	)
	return err
}

const insertPriceSourceCategoryMarkups = `-- name: InsertPriceSourceCategoryMarkups :exec
INSERT INTO organization_price_source_category_markups (organization_id, source, category, markup_percent)
SELECT $1::uuid, $2::text, u.category, u.markup_percent
FROM (
    SELECT unnest($3::text[])         AS category,
           unnest($4::numeric[]) AS markup_percent
) AS u
`

type InsertPriceSourceCategoryMarkupsParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	Source         string           `json:"source"`
	Categories     []string         `json:"categories"`
	MarkupPercents []pgtype.Numeric `json:"markup_percents"`
}

func (q *Queries) InsertPriceSourceCategoryMarkups(ctx context.Context, arg InsertPriceSourceCategoryMarkupsParams) error {
	_, err := q.db.Exec(ctx, insertPriceSourceCategoryMarkups,
		arg.OrganizationID,
		arg.Source,
		arg.Categories,
		arg.MarkupPercents,
	)
	return err
}

const insertSourceProducts = `-- name: InsertSourceProducts :execrows
INSERT INTO products (organization_id, name, normalized_name, unit, unit_price, description,
    category, source, source_price, source_synced_at)
SELECT $1::uuid, u.name, u.normalized_name, u.unit, u.unit_price, u.description,
    u.category, $2::text, u.source_price, now()
FROM (
    SELECT unnest($3::text[])             AS name,
           unnest($4::text[])  AS normalized_name,
           unnest($5::text[])             AS unit,
           unnest($6::numeric[])    AS unit_price,
           unnest($7::numeric[])  AS source_price,
           unnest($8::text[])        AS category,
           unnest($9::text[])      AS description
) AS u
`

type InsertSourceProductsParams struct {
	OrganizationID  pgtype.UUID      `json:"organization_id"`
	Source          string           `json:"source"`
	Names           []string         `json:"names"`
	NormalizedNames []string         `json:"normalized_names"`
	Units           []string         `json:"units"`
	UnitPrices      []pgtype.Numeric `json:"unit_prices"`
	SourcePrices    []pgtype.Numeric `json:"source_prices"`
	Categories      []string         `json:"categories"`
	Descriptions    []string         `json:"descriptions"`
}

// Açıklama yalnızca YENİ satıra yazılır (ör. Demir Profil "6 m boy · 3,925
// kg/m"); eşleşen satırın açıklaması kullanıcıya aittir, dokunulmaz.
func (q *Queries) InsertSourceProducts(ctx context.Context, arg InsertSourceProductsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSourceProducts,
		arg.OrganizationID,
		arg.Source,
		arg.Names,
		arg.NormalizedNames,
		arg.Units,
		arg.UnitPrices,
		arg.SourcePrices,
		arg.Categories,
		arg.Descriptions,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAutoSyncOrganizations = `-- name: ListAutoSyncOrganizations :many
SELECT s.organization_id
FROM organization_price_sources s
JOIN organizations o ON o.id = s.organization_id
WHERE s.source = $1
  AND s.auto_sync
  AND o.status IN ('active', 'trial')
  AND o.deleted_at IS NULL
  AND (s.last_synced_at IS NULL OR s.last_synced_at < $2::timestamptz)
ORDER BY o.created_at, o.id
`

type ListAutoSyncOrganizationsParams struct {
	Source       string             `json:"source"`
	SyncedBefore pgtype.Timestamptz `json:"synced_before"`
}

// Gece işi: otomatik senkronu açık, erişimi olan (active/trial), silinmemiş
// firmalar. synced_before: bu çalıştırmanın planlandığı an -- başka bir API
// instance'ı aynı geceyi az önce işlediyse o firmalar tekrar alınmaz.
func (q *Queries) ListAutoSyncOrganizations(ctx context.Context, arg ListAutoSyncOrganizationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAutoSyncOrganizations, arg.Source, arg.SyncedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var organization_id pgtype.UUID
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceSourceCategoryMarkups = `-- name: ListPriceSourceCategoryMarkups :many
SELECT category, markup_percent FROM organization_price_source_category_markups
WHERE organization_id = $1 AND source = $2
ORDER BY category
`

type ListPriceSourceCategoryMarkupsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

type ListPriceSourceCategoryMarkupsRow struct {
	Category      string         `json:"category"`
	MarkupPercent pgtype.Numeric `json:"markup_percent"`
}

func (q *Queries) ListPriceSourceCategoryMarkups(ctx context.Context, arg ListPriceSourceCategoryMarkupsParams) ([]ListPriceSourceCategoryMarkupsRow, error) {
	rows, err := q.db.Query(ctx, listPriceSourceCategoryMarkups, arg.OrganizationID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceSourceCategoryMarkupsRow
	for rows.Next() {
		var i ListPriceSourceCategoryMarkupsRow
		if err := rows.Scan(&i.Category, &i.MarkupPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceProductCategories = `-- name: ListSourceProductCategories :many
SELECT category, count(*)::int AS product_count
FROM products
WHERE organization_id = $1 AND source = $2::text AND category <> ''
GROUP BY category
ORDER BY category
`

type ListSourceProductCategoriesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

type ListSourceProductCategoriesRow struct {
	Category     string `json:"category"`
	ProductCount int32  `json:"product_count"`
}

func (q *Queries) ListSourceProductCategories(ctx context.Context, arg ListSourceProductCategoriesParams) ([]ListSourceProductCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listSourceProductCategories, arg.OrganizationID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceProductCategoriesRow
	for rows.Next() {
		var i ListSourceProductCategoriesRow
		if err := rows.Scan(&i.Category, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceProductsForUpdate = `-- name: ListSourceProductsForUpdate :many
SELECT id, name, unit, unit_price, source_price, category, description, source_synced_at
FROM products
WHERE organization_id = $1 AND source = $2::text
ORDER BY created_at, id
FOR NO KEY UPDATE
`

type ListSourceProductsForUpdateParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

type ListSourceProductsForUpdateRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	SourcePrice    pgtype.Numeric     `json:"source_price"`
	Category       string             `json:"category"`
	Description    string             `json:"description"`
	SourceSyncedAt pgtype.Timestamptz `json:"source_synced_at"`
}

// Firmanın YALNIZCA bu kaynaktan gelen ürünleri; elle eklenen (source
// NULL/başka) ürünler aynı ada sahip olsa bile ASLA eşleşmez.
// description + source_synced_at: hiç senkronlanmamış (BYZ'den aktarılmış)
// satırlarda Ulaş kategorisi açıklamadadır (bkz. matchSourceRows).
// FOR NO KEY UPDATE (FOR UPDATE DEĞİL): senkron anahtar kolonlara
// dokunmaz; FOR UPDATE, teklif/reçete/değişiklik talebi kalemi eklerken
// FK kontrolünün aldığı FOR KEY SHARE ile çakışıp o kayıtları bekletir,
// satırları farklı sırayla kilitleyen bir teklif kaydıyla kilitlenmeye
// (deadlock) yol açardı. Eşzamanlı ürün UPDATE/DELETE'ine karşı yine
// sıralanır.
func (q *Queries) ListSourceProductsForUpdate(ctx context.Context, arg ListSourceProductsForUpdateParams) ([]ListSourceProductsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listSourceProductsForUpdate, arg.OrganizationID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceProductsForUpdateRow
	for rows.Next() {
		var i ListSourceProductsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.UnitPrice,
			&i.SourcePrice,
			&i.Category,
			&i.Description,
			&i.SourceSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priceSourceXactLock = `-- name: PriceSourceXactLock :exec
SELECT pg_advisory_xact_lock($1::int, hashtext($2::text))
`

type PriceSourceXactLockParams struct {
	LockClass int32  `json:"lock_class"`
	LockKey   string `json:"lock_key"`
}

func (q *Queries) PriceSourceXactLock(ctx context.Context, arg PriceSourceXactLockParams) error {
	_, err := q.db.Exec(ctx, priceSourceXactLock, arg.LockClass, arg.LockKey)
	return err
}

const recordPriceSourceSyncFailure = `-- name: RecordPriceSourceSyncFailure :exec
INSERT INTO organization_price_sources (organization_id, source, last_status, last_error)
VALUES ($1, $2, 'failed', $3)
ON CONFLICT (organization_id, source) DO UPDATE
SET last_status = 'failed',
    last_error  = EXCLUDED.last_error
`

type RecordPriceSourceSyncFailureParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
	LastError      string      `json:"last_error"`
}

// Başarısız deneme: last_synced_at ve son başarılı sayılar KORUNUR.
func (q *Queries) RecordPriceSourceSyncFailure(ctx context.Context, arg RecordPriceSourceSyncFailureParams) error {
	_, err := q.db.Exec(ctx, recordPriceSourceSyncFailure, arg.OrganizationID, arg.Source, arg.LastError)
	return err
}

const recordPriceSourceSyncSuccess = `-- name: RecordPriceSourceSyncSuccess :one
INSERT INTO organization_price_sources (
    organization_id, source, last_synced_at, last_status, last_error,
    last_total, last_created, last_updated, last_unchanged, last_missing, last_list_label, last_list_as_of)
VALUES ($1, $2, now(), 'success', '',
    $3, $4, $5, $6, $7,
    $8, COALESCE($9::timestamptz, now()))
ON CONFLICT (organization_id, source) DO UPDATE
SET last_synced_at  = now(),
    last_list_as_of = EXCLUDED.last_list_as_of,
    last_status     = 'success',
    last_error      = '',
    last_total      = EXCLUDED.last_total,
    last_created    = EXCLUDED.last_created,
    last_updated    = EXCLUDED.last_updated,
    last_unchanged  = EXCLUDED.last_unchanged,
    last_missing    = EXCLUDED.last_missing,
    last_list_label = EXCLUDED.last_list_label
RETURNING last_synced_at
`

type RecordPriceSourceSyncSuccessParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Source         string             `json:"source"`
	Total          int32              `json:"total"`
	Created        int32              `json:"created"`
	Updated        int32              `json:"updated"`
	Unchanged      int32              `json:"unchanged"`
	Missing        int32              `json:"missing"`
	ListLabel      string             `json:"list_label"`
	ListAsOf       pgtype.Timestamptz `json:"list_as_of"`
}

// last_synced_at = now(): aynı transaction'daki products.source_synced_at
// ve product_price_history.changed_at ile BİREBİR aynı an (eksik ürün
// hesabı ve "son senkronda zam gelen ürünler" bu eşitliğe dayanır).
// last_list_as_of: listenin VERİ tarihi (canlı listede senkron anı,
// arşiv kopyasında kopyanın tarihi -- bkz. migration 0049).
func (q *Queries) RecordPriceSourceSyncSuccess(ctx context.Context, arg RecordPriceSourceSyncSuccessParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, recordPriceSourceSyncSuccess,
		arg.OrganizationID,
		arg.Source,
		arg.Total,
		arg.Created,
		arg.Updated,
		arg.Unchanged,
		arg.Missing,
		arg.ListLabel,
		arg.ListAsOf,
	)
	var last_synced_at pgtype.Timestamptz
	err := row.Scan(&last_synced_at)
	return last_synced_at, err
}

const summarizeSourceProducts = `-- name: SummarizeSourceProducts :one
SELECT count(*)::int AS product_count,
       (count(*) FILTER (
            WHERE s.last_synced_at IS NOT NULL
              AND (p.source_synced_at IS NULL OR p.source_synced_at < s.last_synced_at)
       ))::int AS missing_count
FROM products p
LEFT JOIN organization_price_sources s
       ON s.organization_id = p.organization_id AND s.source = p.source
WHERE p.organization_id = $1 AND p.source = $2::text
`

type SummarizeSourceProductsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Source         string      `json:"source"`
}

type SummarizeSourceProductsRow struct {
	ProductCount int32 `json:"product_count"`
	MissingCount int32 `json:"missing_count"`
}

// missing yalnızca en az bir başarılı senkron olduysa anlamlıdır (hiç
// senkron yoksa BYZ'den aktarılan satırların hepsi "eksik" görünmesin).
func (q *Queries) SummarizeSourceProducts(ctx context.Context, arg SummarizeSourceProductsParams) (SummarizeSourceProductsRow, error) {
	row := q.db.QueryRow(ctx, summarizeSourceProducts, arg.OrganizationID, arg.Source)
	var i SummarizeSourceProductsRow
	err := row.Scan(&i.ProductCount, &i.MissingCount)
	return i, err
}

const tryPriceSourceXactLock = `-- name: TryPriceSourceXactLock :one
SELECT pg_try_advisory_xact_lock($1::int, hashtext($2::text))
`

type TryPriceSourceXactLockParams struct {
	LockClass int32  `json:"lock_class"`
	LockKey   string `json:"lock_key"`
}

func (q *Queries) TryPriceSourceXactLock(ctx context.Context, arg TryPriceSourceXactLockParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryPriceSourceXactLock, arg.LockClass, arg.LockKey)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}

const updateProductUnitPrices = `-- name: UpdateProductUnitPrices :execrows
UPDATE products AS p
SET unit_price = u.unit_price
FROM (
    SELECT unnest($3::uuid[])            AS id,
           unnest($4::numeric[]) AS unit_price
) AS u
WHERE p.id = u.id
  AND p.organization_id = $1
  AND p.source = $2::text
`

type UpdateProductUnitPricesParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	Source         string           `json:"source"`
	Ids            []pgtype.UUID    `json:"ids"`
	UnitPrices     []pgtype.Numeric `json:"unit_prices"`
}

func (q *Queries) UpdateProductUnitPrices(ctx context.Context, arg UpdateProductUnitPricesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProductUnitPrices,
		arg.OrganizationID,
		arg.Source,
		arg.Ids,
		arg.UnitPrices,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSourceProducts = `-- name: UpdateSourceProducts :execrows
UPDATE products AS p
SET unit_price       = u.unit_price,
    source_price     = u.source_price,
    category         = u.category,
    source_synced_at = now()
FROM (
    SELECT unnest($3::uuid[])              AS id,
           unnest($4::numeric[])   AS unit_price,
           unnest($5::numeric[]) AS source_price,
           unnest($6::text[])       AS category
) AS u
WHERE p.id = u.id
  AND p.organization_id = $1
  AND p.source = $2::text
`

type UpdateSourceProductsParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	Source         string           `json:"source"`
	Ids            []pgtype.UUID    `json:"ids"`
	UnitPrices     []pgtype.Numeric `json:"unit_prices"`
	SourcePrices   []pgtype.Numeric `json:"source_prices"`
	Categories     []string         `json:"categories"`
}

// Senkronun eşleşen satırları: ad/birim/açıklama/id KORUNUR (açıklama
// kullanıcıya aittir), yalnızca fiyatlar + kaynak kategorisi + görülme
// anı yazılır.
func (q *Queries) UpdateSourceProducts(ctx context.Context, arg UpdateSourceProductsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSourceProducts,
		arg.OrganizationID,
		arg.Source,
		arg.Ids,
		arg.UnitPrices,
		arg.SourcePrices,
		arg.Categories,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOrganizationPriceSourceSettings = `-- name: UpsertOrganizationPriceSourceSettings :one
INSERT INTO organization_price_sources (organization_id, source, markup_percent, auto_sync, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, source) DO UPDATE
SET markup_percent = EXCLUDED.markup_percent,
    auto_sync      = EXCLUDED.auto_sync,
    updated_by     = EXCLUDED.updated_by
RETURNING organization_id, source, markup_percent, auto_sync, last_synced_at, last_status, last_error, last_total, last_created, last_updated, last_unchanged, last_missing, updated_by, created_at, updated_at, last_list_label, last_list_as_of
`

type UpsertOrganizationPriceSourceSettingsParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Source         string         `json:"source"`
	MarkupPercent  pgtype.Numeric `json:"markup_percent"`
	AutoSync       bool           `json:"auto_sync"`
	UpdatedBy      pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpsertOrganizationPriceSourceSettings(ctx context.Context, arg UpsertOrganizationPriceSourceSettingsParams) (OrganizationPriceSource, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationPriceSourceSettings,
		arg.OrganizationID,
		arg.Source,
		arg.MarkupPercent,
		arg.AutoSync,
		arg.UpdatedBy,
	)
	var i OrganizationPriceSource
	err := row.Scan(
		&i.OrganizationID,
		&i.Source,
		&i.MarkupPercent,
		&i.AutoSync,
		&i.LastSyncedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastTotal,
		&i.LastCreated,
		&i.LastUpdated,
		&i.LastUnchanged,
		&i.LastMissing,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastListLabel,
		&i.LastListAsOf,
	)
	return i, err
}

const upsertPriceSourceSnapshot = `-- name: UpsertPriceSourceSnapshot :exec
INSERT INTO price_source_snapshots (source, origin, as_of, label, items, item_count, saved_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (source) DO UPDATE
SET origin     = EXCLUDED.origin,
    as_of      = EXCLUDED.as_of,
    label      = EXCLUDED.label,
    items      = EXCLUDED.items,
    item_count = EXCLUDED.item_count,
    saved_at   = now()
WHERE price_source_snapshots.as_of <= EXCLUDED.as_of
`

type UpsertPriceSourceSnapshotParams struct {
	Source    string             `json:"source"`
	Origin    string             `json:"origin"`
	AsOf      pgtype.Timestamptz `json:"as_of"`
	Label     string             `json:"label"`
	Items     []byte             `json:"items"`
	ItemCount int32              `json:"item_count"`
}

// Yalnızca daha YENİ (ya da aynı) tarihli liste eskisinin yerine geçer:
// canlı site düzelince arşivden okunan eski bir kopya, saklı yeni listeyi
// ezmesin.
func (q *Queries) UpsertPriceSourceSnapshot(ctx context.Context, arg UpsertPriceSourceSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertPriceSourceSnapshot,
		arg.Source,
		arg.Origin,
		arg.AsOf,
		arg.Label,
		arg.Items,
		arg.ItemCount,
	)
	return err
}
