// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_changes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPriceChanges = `-- name: CountPriceChanges :one
SELECT count(*)
FROM product_price_history h
JOIN products p ON p.id = h.product_id
WHERE p.organization_id = $1
  AND h.changed_at >= $2::timestamptz
  AND h.changed_at <  $3::timestamptz
  AND ($4::text = 'all'
       OR ($4::text = 'up'   AND h.new_price > h.old_price)
       OR ($4::text = 'down' AND h.new_price < h.old_price))
  AND ($5::text = 'all' OR h.reason = $5::text)
  AND ($6::text = '' OR h.source = $6::text)
  AND ($7::text = '' OR p.category = $7::text)
  AND ($8::text = '' OR p.normalized_name ILIKE '%' || $8::text || '%')
`

type CountPriceChangesParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	Direction      string             `json:"direction"`
	Reason         string             `json:"reason"`
	Source         string             `json:"source"`
	Category       string             `json:"category"`
	Search         string             `json:"search"`
}

func (q *Queries) CountPriceChanges(ctx context.Context, arg CountPriceChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceChanges,
		arg.OrganizationID,
		arg.FromTime,
		arg.ToTime,
		arg.Direction,
		arg.Reason,
		arg.Source,
		arg.Category,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMaxPriceIncrease = `-- name: GetMaxPriceIncrease :many
SELECT h.product_id, p.name AS product_name,
       round((h.new_price - h.old_price) / h.old_price * 100, 2)::numeric AS change_percent
FROM product_price_history h
JOIN products p ON p.id = h.product_id
WHERE p.organization_id = $1
  AND h.changed_at >= $2::timestamptz
  AND h.changed_at <  $3::timestamptz
  AND ($4::text = 'all' OR h.reason = $4::text)
  AND ($5::text = '' OR h.source = $5::text)
  AND h.new_price > h.old_price AND h.old_price > 0
ORDER BY (h.new_price - h.old_price) / h.old_price DESC, h.changed_at DESC, h.id
LIMIT 1
`

type GetMaxPriceIncreaseParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	Reason         string             `json:"reason"`
	Source         string             `json:"source"`
}

type GetMaxPriceIncreaseRow struct {
	ProductID     pgtype.UUID    `json:"product_id"`
	ProductName   string         `json:"product_name"`
	ChangePercent pgtype.Numeric `json:"change_percent"`
}

// En yüksek yüzdeli zam (en fazla 1 satır; hiç zam yoksa boş).
func (q *Queries) GetMaxPriceIncrease(ctx context.Context, arg GetMaxPriceIncreaseParams) ([]GetMaxPriceIncreaseRow, error) {
	rows, err := q.db.Query(ctx, getMaxPriceIncrease,
		arg.OrganizationID,
		arg.FromTime,
		arg.ToTime,
		arg.Reason,
		arg.Source,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaxPriceIncreaseRow
	for rows.Next() {
		var i GetMaxPriceIncreaseRow
		if err := rows.Scan(&i.ProductID, &i.ProductName, &i.ChangePercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceChangeEvents = `-- name: ListPriceChangeEvents :many
SELECT (CASE WHEN h.reason = 'manual'
             THEN date_trunc('day', h.changed_at AT TIME ZONE 'Europe/Istanbul') AT TIME ZONE 'Europe/Istanbul'
             ELSE h.changed_at END)::timestamptz AS event_at,
       h.source, h.reason,
       count(*)::int AS change_count,
       (count(*) FILTER (WHERE h.new_price > h.old_price))::int AS increased,
       (count(*) FILTER (WHERE h.new_price < h.old_price))::int AS decreased,
       round(avg((h.new_price - h.old_price) / h.old_price * 100)
             FILTER (WHERE h.old_price > 0), 2)::numeric AS avg_change_percent,
       round(max((h.new_price - h.old_price) / h.old_price * 100)
             FILTER (WHERE h.new_price > h.old_price AND h.old_price > 0), 2)::numeric AS max_increase_percent
FROM product_price_history h
JOIN products p ON p.id = h.product_id
WHERE p.organization_id = $1
  AND h.changed_at >= $2::timestamptz
  AND h.changed_at <  $3::timestamptz
  AND ($4::text = 'all' OR h.reason = $4::text)
  AND ($5::text = '' OR h.source = $5::text)
GROUP BY 1, h.source, h.reason
ORDER BY 1 DESC, h.source NULLS LAST, h.reason
LIMIT $6::int
`

type ListPriceChangeEventsParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	Reason         string             `json:"reason"`
	Source         string             `json:"source"`
	MaxEvents      int32              `json:"max_events"`
}

type ListPriceChangeEventsRow struct {
	EventAt            pgtype.Timestamptz `json:"event_at"`
	Source             *string            `json:"source"`
	Reason             string             `json:"reason"`
	ChangeCount        int32              `json:"change_count"`
	Increased          int32              `json:"increased"`
	Decreased          int32              `json:"decreased"`
	AvgChangePercent   pgtype.Numeric     `json:"avg_change_percent"`
	MaxIncreasePercent pgtype.Numeric     `json:"max_increase_percent"`
}

// Bir olay = aynı transaction'da yazılan satırlar: (changed_at, source,
// reason). Elle düzenlemeler tek tek değil, İstanbul günü başına gruplanır
// (event_at = o günün 00:00'ı). En yeni olay önce, en fazla max_events.
func (q *Queries) ListPriceChangeEvents(ctx context.Context, arg ListPriceChangeEventsParams) ([]ListPriceChangeEventsRow, error) {
	rows, err := q.db.Query(ctx, listPriceChangeEvents,
		arg.OrganizationID,
		arg.FromTime,
		arg.ToTime,
		arg.Reason,
		arg.Source,
		arg.MaxEvents,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceChangeEventsRow
	for rows.Next() {
		var i ListPriceChangeEventsRow
		if err := rows.Scan(
			&i.EventAt,
			&i.Source,
			&i.Reason,
			&i.ChangeCount,
			&i.Increased,
			&i.Decreased,
			&i.AvgChangePercent,
			&i.MaxIncreasePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceChanges = `-- name: ListPriceChanges :many

SELECT h.id, h.product_id, p.name AS product_name, p.unit, p.category,
       h.source, h.reason, h.note, h.old_price, h.new_price, h.changed_at,
       h.old_source_price, h.new_source_price
FROM product_price_history h
JOIN products p ON p.id = h.product_id
WHERE p.organization_id = $1
  AND h.changed_at >= $2::timestamptz
  AND h.changed_at <  $3::timestamptz
  AND ($4::text = 'all'
       OR ($4::text = 'up'   AND h.new_price > h.old_price)
       OR ($4::text = 'down' AND h.new_price < h.old_price))
  AND ($5::text = 'all' OR h.reason = $5::text)
  AND ($6::text = '' OR h.source = $6::text)
  AND ($7::text = '' OR p.category = $7::text)
  AND ($8::text = '' OR p.normalized_name ILIKE '%' || $8::text || '%')
ORDER BY
  CASE WHEN $9::text = 'largest_increase' AND h.old_price > 0
       THEN (h.new_price - h.old_price) / h.old_price END DESC NULLS LAST,
  CASE WHEN $9::text = 'largest_decrease' AND h.old_price > 0
       THEN (h.new_price - h.old_price) / h.old_price END ASC NULLS LAST,
  h.changed_at DESC, h.id
LIMIT $11::int OFFSET $10::bigint
`

type ListPriceChangesParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	Direction      string             `json:"direction"`
	Reason         string             `json:"reason"`
	Source         string             `json:"source"`
	Category       string             `json:"category"`
	Search         string             `json:"search"`
	Sort           string             `json:"sort"`
	PageOffset     int64              `json:"page_offset"`
	PageLimit      int32              `json:"page_limit"`
}

type ListPriceChangesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	ProductName    string             `json:"product_name"`
	Unit           string             `json:"unit"`
	Category       string             `json:"category"`
	Source         *string            `json:"source"`
	Reason         string             `json:"reason"`
	Note           string             `json:"note"`
	OldPrice       pgtype.Numeric     `json:"old_price"`
	NewPrice       pgtype.Numeric     `json:"new_price"`
	ChangedAt      pgtype.Timestamptz `json:"changed_at"`
	OldSourcePrice pgtype.Numeric     `json:"old_source_price"`
	NewSourcePrice pgtype.Numeric     `json:"new_source_price"`
}

// Zam geçmişi (migration 0046): firmanın ürün fiyat değişiklikleri.
// product_price_history'de organization_id yoktur -- firma izolasyonu HER
// sorguda products.organization_id üzerinden JOIN ile sağlanır.
//
// Ortak filtreler (liste + sayım + özet):
//
//	from_time <= changed_at < to_time (servis dahil/hariç sınırları çözer)
//	reason: 'all' ya da manual|supplier|markup
//	source: '' = hepsi, aksi hâlde kaynak kodu (elle düzenlemede source NULL)
//
// Yüzde = (yeni - eski) / eski x 100; eski fiyat 0 ise NULL (tanımsız).
// sort: newest | largest_increase (yüzde büyükten küçüğe) | largest_decrease
// (yüzde küçükten büyüğe, en çok düşen önce). Yüzdesi tanımsız satırlar
// (eski fiyat 0) sıralamada sona düşer; eşitlikte en yeni önce.
func (q *Queries) ListPriceChanges(ctx context.Context, arg ListPriceChangesParams) ([]ListPriceChangesRow, error) {
	rows, err := q.db.Query(ctx, listPriceChanges,
		arg.OrganizationID,
		arg.FromTime,
		arg.ToTime,
		arg.Direction,
		arg.Reason,
		arg.Source,
		arg.Category,
		arg.Search,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceChangesRow
	for rows.Next() {
		var i ListPriceChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.Unit,
			&i.Category,
			&i.Source,
			&i.Reason,
			&i.Note,
			&i.OldPrice,
			&i.NewPrice,
			&i.ChangedAt,
			&i.OldSourcePrice,
			&i.NewSourcePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizePriceChanges = `-- name: SummarizePriceChanges :one
SELECT (count(*) FILTER (WHERE h.new_price > h.old_price))::int AS increased_count,
       (count(*) FILTER (WHERE h.new_price < h.old_price))::int AS decreased_count,
       (count(DISTINCT h.product_id) FILTER (WHERE h.new_price > h.old_price))::int AS products_increased,
       round(avg((h.new_price - h.old_price) / h.old_price * 100)
             FILTER (WHERE h.new_price > h.old_price AND h.old_price > 0), 2)::numeric AS avg_increase_percent
FROM product_price_history h
JOIN products p ON p.id = h.product_id
WHERE p.organization_id = $1
  AND h.changed_at >= $2::timestamptz
  AND h.changed_at <  $3::timestamptz
  AND ($4::text = 'all' OR h.reason = $4::text)
  AND ($5::text = '' OR h.source = $5::text)
`

type SummarizePriceChangesParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	Reason         string             `json:"reason"`
	Source         string             `json:"source"`
}

type SummarizePriceChangesRow struct {
	IncreasedCount     int32          `json:"increased_count"`
	DecreasedCount     int32          `json:"decreased_count"`
	ProductsIncreased  int32          `json:"products_increased"`
	AvgIncreasePercent pgtype.Numeric `json:"avg_increase_percent"`
}

func (q *Queries) SummarizePriceChanges(ctx context.Context, arg SummarizePriceChangesParams) (SummarizePriceChangesRow, error) {
	row := q.db.QueryRow(ctx, summarizePriceChanges,
		arg.OrganizationID,
		arg.FromTime,
		arg.ToTime,
		arg.Reason,
		arg.Source,
	)
	var i SummarizePriceChangesRow
	err := row.Scan(
		&i.IncreasedCount,
		&i.DecreasedCount,
		&i.ProductsIncreased,
		&i.AvgIncreasePercent,
	)
	return i, err
}
