// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE organization_id = $1
  AND ($2::text = '' OR normalized_name ILIKE '%' || $2::text || '%')
`

type CountProductsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Column2        string      `json:"column_2"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.OrganizationID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPriceHistory = `-- name: CreatePriceHistory :exec
INSERT INTO product_price_history (product_id, old_price, new_price, note)
VALUES ($1, $2, $3, $4)
`

type CreatePriceHistoryParams struct {
	ProductID pgtype.UUID    `json:"product_id"`
	OldPrice  pgtype.Numeric `json:"old_price"`
	NewPrice  pgtype.Numeric `json:"new_price"`
	Note      string         `json:"note"`
}

func (q *Queries) CreatePriceHistory(ctx context.Context, arg CreatePriceHistoryParams) error {
	_, err := q.db.Exec(ctx, createPriceHistory,
		arg.ProductID,
		arg.OldPrice,
		arg.NewPrice,
		arg.Note,
	)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (organization_id, name, normalized_name, unit, unit_price, description, category, source, source_price)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at
`

type CreateProductParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Name           string         `json:"name"`
	NormalizedName string         `json:"normalized_name"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	Description    string         `json:"description"`
	Category       string         `json:"category"`
	Source         *string        `json:"source"`
	SourcePrice    pgtype.Numeric `json:"source_price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrganizationID,
		arg.Name,
		arg.NormalizedName,
		arg.Unit,
		arg.UnitPrice,
		arg.Description,
		arg.Category,
		arg.Source,
		arg.SourcePrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Unit,
		&i.UnitPrice,
		&i.Description,
		&i.Category,
		&i.Source,
		&i.SourcePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceSyncedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1 AND organization_id = $2
`

type DeleteProductParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at FROM products WHERE id = $1 AND organization_id = $2
`

type GetProductByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Unit,
		&i.UnitPrice,
		&i.Description,
		&i.Category,
		&i.Source,
		&i.SourcePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceSyncedAt,
	)
	return i, err
}

const listPriceHistory = `-- name: ListPriceHistory :many
SELECT id, product_id, old_price, new_price, note, changed_at FROM product_price_history
WHERE product_id = $1
ORDER BY changed_at DESC
`

func (q *Queries) ListPriceHistory(ctx context.Context, productID pgtype.UUID) ([]ProductPriceHistory, error) {
	rows, err := q.db.Query(ctx, listPriceHistory, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductPriceHistory
	for rows.Next() {
		var i ProductPriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OldPrice,
			&i.NewPrice,
			&i.Note,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at FROM products
WHERE organization_id = $1
  AND ($4::text = '' OR normalized_name ILIKE '%' || $4::text || '%')
ORDER BY name ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	Column4        string      `json:"column_4"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Unit,
			&i.UnitPrice,
			&i.Description,
			&i.Category,
			&i.Source,
			&i.SourcePrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.SourceSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3, normalized_name = $4, unit = $5, unit_price = $6,
    description = $7, category = $8
WHERE id = $1 AND organization_id = $2
RETURNING id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at
`

type UpdateProductParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Name           string         `json:"name"`
	NormalizedName string         `json:"normalized_name"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	Description    string         `json:"description"`
	Category       string         `json:"category"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.NormalizedName,
		arg.Unit,
		arg.UnitPrice,
		arg.Description,
		arg.Category,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Unit,
		&i.UnitPrice,
		&i.Description,
		&i.Category,
		&i.Source,
		&i.SourcePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceSyncedAt,
	)
	return i, err
}
