// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_usage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductUsage = `-- name: GetProductUsage :one

SELECT
    (SELECT count(*) FROM calc_recipe_items cri
      WHERE cri.product_id = $1 AND cri.organization_id = $2)::bigint AS recipe_items,
    (SELECT count(*) FROM project_change_order_items coi
      WHERE coi.product_id = $1 AND coi.organization_id = $2)::bigint AS change_order_items
`

type GetProductUsageParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetProductUsageRow struct {
	RecipeItems      int64 `json:"recipe_items"`
	ChangeOrderItems int64 `json:"change_order_items"`
}

// Ürün silme öncesi kullanım kontrolü (products.sql'deki CRUD'dan ayrı).
// recipe_items: ürüne bağlı metraj reçete kalemleri (pasifler dahil) --
// FK'leri ON DELETE SET NULL olduğu için silme onları SESSİZCE ürünsüz
// bırakıyordu (sonraki hesaplamalar 0 TL ile "product_missing" uyarısı
// üretir). change_order_items: ek iş kalemleri -- FK'leri kısıtlayıcıdır,
// silme ham bir Postgres hatasıyla düşüyordu. Teklif kalemleri SAYILMAZ:
// onlar ürün adı/fiyatının anlık görüntüsünü taşır ve bağın kopması
// tasarım gereğidir (bkz. migration 0017).
func (q *Queries) GetProductUsage(ctx context.Context, arg GetProductUsageParams) (GetProductUsageRow, error) {
	row := q.db.QueryRow(ctx, getProductUsage, arg.ID, arg.OrganizationID)
	var i GetProductUsageRow
	err := row.Scan(&i.RecipeItems, &i.ChangeOrderItems)
	return i, err
}
