// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE organization_id = $1
`

func (q *Queries) CountProducts(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (organization_id, name, normalized_name, unit, unit_price, description, category, source, source_price)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at
`

type CreateProductParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Name           string         `json:"name"`
	NormalizedName string         `json:"normalized_name"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	Description    string         `json:"description"`
	Category       string         `json:"category"`
	Source         *string        `json:"source"`
	SourcePrice    pgtype.Numeric `json:"source_price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrganizationID,
		arg.Name,
		arg.NormalizedName,
		arg.Unit,
		arg.UnitPrice,
		arg.Description,
		arg.Category,
		arg.Source,
		arg.SourcePrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Unit,
		&i.UnitPrice,
		&i.Description,
		&i.Category,
		&i.Source,
		&i.SourcePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceSyncedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1 AND organization_id = $2
`

type DeleteProductParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at FROM products WHERE id = $1 AND organization_id = $2
`

type GetProductByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Unit,
		&i.UnitPrice,
		&i.Description,
		&i.Category,
		&i.Source,
		&i.SourcePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceSyncedAt,
	)
	return i, err
}

const listPriceHistory = `-- name: ListPriceHistory :many
SELECT id, product_id, old_price, new_price, note, changed_at, reason, source, old_source_price, new_source_price FROM product_price_history
WHERE product_id = $1
ORDER BY changed_at DESC
`

func (q *Queries) ListPriceHistory(ctx context.Context, productID pgtype.UUID) ([]ProductPriceHistory, error) {
	rows, err := q.db.Query(ctx, listPriceHistory, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductPriceHistory
	for rows.Next() {
		var i ProductPriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OldPrice,
			&i.NewPrice,
			&i.Note,
			&i.ChangedAt,
			&i.Reason,
			&i.Source,
			&i.OldSourcePrice,
			&i.NewSourcePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at FROM products
WHERE organization_id = $1
ORDER BY name ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

// Aramasız katalog listesi (ad sırasıyla). Arama SearchProducts'tadır.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Unit,
			&i.UnitPrice,
			&i.Description,
			&i.Category,
			&i.Source,
			&i.SourcePrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.SourceSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
WITH category_folds AS MATERIALIZED (
    SELECT d.category,
           replace(replace(replace(
               CASE WHEN d.lowered ~ '[x×*] | [x×*]'
                    THEN regexp_replace(d.lowered, '(\d) *[x×*] *(?=\d)', '\1x', 'g') ELSE d.lowered END,
           '×', 'x'), '*', 'x'), ',', '.') AS category_f
    FROM (
        SELECT DISTINCT p.category, lower(translate(p.category, 'İIıŞşĞğÜüÖöÇç', 'iiissgguuoocc')) AS lowered
        FROM products AS p
        WHERE p.organization_id = $7
    ) AS d
), candidates AS MATERIALIZED (
    SELECT p.id, p.name, p.normalized_name, p.unit, p.unit_price, p.description, p.category, p.source, p.source_price, p.created_at, p.updated_at, p.organization_id, p.source_synced_at, n.name_f,
           n.name_f || ' ' || cf.category_f || ' ' ||
           coalesce(($8::text[])[array_position($9::text[], p.source::text)],
                    lower(p.source), '') AS haystack
    FROM products AS p
    JOIN category_folds AS cf ON cf.category = p.category
    CROSS JOIN LATERAL (
        SELECT replace(replace(replace(
                   CASE WHEN p.normalized_name ~ '[x×*] | [x×*]'
                        THEN regexp_replace(p.normalized_name, '(\d) *[x×*] *(?=\d)', '\1x', 'g') ELSE p.normalized_name END,
               '×', 'x'), '*', 'x'), ',', '.') AS name_f
    ) AS n
    WHERE p.organization_id = $7
)
SELECT c.id, c.name, c.normalized_name, c.unit, c.unit_price, c.description, c.category, c.source,
       c.source_price, c.created_at, c.updated_at, c.organization_id, c.source_synced_at,
       count(*) OVER () AS total
FROM candidates AS c
WHERE c.haystack LIKE ALL ($1::text[])
ORDER BY (c.name_f LIKE ALL ($1::text[])) DESC,
         (c.name_f LIKE ANY ($1::text[])) DESC,
         (' ' || c.name_f || ' ' || translate(c.name_f, 'ø(/-x', '     ')) LIKE ALL ($2::text[]) DESC,
         (strpos(c.name_f, $3::text) > 0) DESC,
         starts_with(c.name_f, $4::text) DESC,
         length(c.name) ASC,
         c.name ASC, c.id ASC
LIMIT $6 OFFSET $5
`

type SearchProductsParams struct {
	Patterns          []string    `json:"patterns"`
	WordStartPatterns []string    `json:"word_start_patterns"`
	Phrase            string      `json:"phrase"`
	FirstTerm         string      `json:"first_term"`
	RowOffset         int32       `json:"row_offset"`
	RowLimit          int32       `json:"row_limit"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
	SourceLabels      []string    `json:"source_labels"`
	SourceCodes       []string    `json:"source_codes"`
}

type SearchProductsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Description    string             `json:"description"`
	Category       string             `json:"category"`
	Source         *string            `json:"source"`
	SourcePrice    pgtype.Numeric     `json:"source_price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	SourceSyncedAt pgtype.Timestamptz `json:"source_synced_at"`
	Total          int64              `json:"total"`
}

// Kelime bazlı katalog araması (bkz. domain/product_search.go). Ürün, HER
// kelime adında YA DA kategorisinde YA DA tedarikçisinde geçiyorsa eşleşir:
// üç alan (kelimeler boşluk içermediği için hiçbir kelime iki alana taşamaz)
// boşlukla birleştirilip "LIKE ALL" ile aranır. Desenler Go'da kaçışlanır
// (ProductSearchPatterns): "_" ve "%" joker değildir.
//
// Katlama Go'daki ProductSearchFold ile BİREBİR aynı olmalı:
//
//	ad       normalized_name (Go NormalizeName ile yazılmış) + "40 x 40" ->
//	         "40x40" (regexp yalnızca x'in yanında boşluk varken çalışır) +
//	         × * , -> x x .
//	kategori Türkçe harf katlaması + lower (translate lower'dan ÖNCE:
//	         lower('İ') yerel ayara göre 'i̇' olur) + aynı ölçü katlaması.
//	         translate pahalıdır (çok baytlı küme): firmanın her FARKLI
//	         kategorisi için bir kez hesaplanır, satır başına değil.
//	tedarikçi kayıt defterinden gelen etiket (ProductSearchSources); defterde
//	         olmayan bir kaynak kodu kendi adıyla aranır.
//
// candidates MATERIALIZED: Postgres aksi hâlde ad katlamasını her
// kullanıldığı yere (filtre + beş sıralama anahtarı) kopyalayıp satır
// başına defalarca hesaplıyordu.
//
// Sıra:
//  1. tüm kelimeler adda; 2. en az bir kelime adda -- ad eşleşmesi
//     kategori/tedarikçi eşleşmesinden önce ("profil": Kutu Profil'ler,
//     Demir Profil'in borularından önce);
//  3. tüm kelimeler bir kelimenin BAŞINDA -- "kutu 40": 40×40 ve 30×40,
//     140×140'tan önce (ölçü ayracı x, Ø, parantez, /, - kelime başı sayılır);
//  4. sorgu adda yan yana geçiyor ("kutu profil"); 5. ad ilk kelimeyle başlıyor;
//  6. kısa ad önce (yazılana daha yakın), sonra ad, id.
//
// total: sayfalamadan önceki eşleşme sayısı (her satırda aynı).
func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.Patterns,
		arg.WordStartPatterns,
		arg.Phrase,
		arg.FirstTerm,
		arg.RowOffset,
		arg.RowLimit,
		arg.OrganizationID,
		arg.SourceLabels,
		arg.SourceCodes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Unit,
			&i.UnitPrice,
			&i.Description,
			&i.Category,
			&i.Source,
			&i.SourcePrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
			&i.SourceSyncedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductWithPriceHistory = `-- name: UpdateProductWithPriceHistory :one
WITH old AS MATERIALIZED (
    SELECT cur.id, cur.unit_price FROM products AS cur
    WHERE cur.id = $1 AND cur.organization_id = $2
    FOR NO KEY UPDATE
), upd AS (
    UPDATE products AS p
    SET name = $3, normalized_name = $4, unit = $5,
        unit_price = $6, description = $7, category = $8
    FROM old
    WHERE p.id = old.id
    RETURNING p.id, p.name, p.normalized_name, p.unit, p.unit_price, p.description, p.category, p.source, p.source_price, p.created_at, p.updated_at, p.organization_id, p.source_synced_at
), hist AS (
    INSERT INTO product_price_history (product_id, old_price, new_price, note, reason)
    SELECT upd.id, old.unit_price, upd.unit_price, '', 'manual'
    FROM upd JOIN old ON old.id = upd.id
    WHERE upd.unit_price <> old.unit_price
)
SELECT id, name, normalized_name, unit, unit_price, description, category, source, source_price, created_at, updated_at, organization_id, source_synced_at FROM upd
`

type UpdateProductWithPriceHistoryParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Name           string         `json:"name"`
	NormalizedName string         `json:"normalized_name"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	Description    string         `json:"description"`
	Category       string         `json:"category"`
}

type UpdateProductWithPriceHistoryRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Description    string             `json:"description"`
	Category       string             `json:"category"`
	Source         *string            `json:"source"`
	SourcePrice    pgtype.Numeric     `json:"source_price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	SourceSyncedAt pgtype.Timestamptz `json:"source_synced_at"`
}

// Elle ürün düzenleme TEK ifadede (tek transaction): satır kilitlenip
// (FOR NO KEY UPDATE) ESKİ fiyat okunur, ürün güncellenir ve fiyat
// değiştiyse fiyat geçmişi satırı (reason 'manual', kaynak yok) yazılır.
// Eşzamanlı bir senkron/kâr oranı güncellemesi satırı tutuyorsa kilit
// beklenir ve eski fiyat, onun YAZDIĞI fiyattır (READ COMMITTED'da kilitli
// okuma satırın en son hâlini döner) -- geçmiş satırları zincir kurar
// (100->110 senkron, 110->120 elle). Geçmiş yazılamazsa güncelleme de
// geri alınır. Satır yoksa (başka firma/silinmiş) sonuç boştur.
func (q *Queries) UpdateProductWithPriceHistory(ctx context.Context, arg UpdateProductWithPriceHistoryParams) (UpdateProductWithPriceHistoryRow, error) {
	row := q.db.QueryRow(ctx, updateProductWithPriceHistory,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.NormalizedName,
		arg.Unit,
		arg.UnitPrice,
		arg.Description,
		arg.Category,
	)
	var i UpdateProductWithPriceHistoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Unit,
		&i.UnitPrice,
		&i.Description,
		&i.Category,
		&i.Source,
		&i.SourcePrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
		&i.SourceSyncedAt,
	)
	return i, err
}
