// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_contract.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProjectContract = `-- name: ActivateProjectContract :one
UPDATE project_contracts
SET status = 'active', activated_at = now(), activated_by = $4
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'draft'
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type ActivateProjectContractParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	ActivatedBy    pgtype.UUID `json:"activated_by"`
}

func (q *Queries) ActivateProjectContract(ctx context.Context, arg ActivateProjectContractParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, activateProjectContract,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ActivatedBy,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const cancelProjectContract = `-- name: CancelProjectContract :one
UPDATE project_contracts
SET status = 'cancelled', cancelled_at = now(), cancelled_by = $4, cancel_reason = $5
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'draft'
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type CancelProjectContractParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	CancelledBy    pgtype.UUID `json:"cancelled_by"`
	CancelReason   string      `json:"cancel_reason"`
}

func (q *Queries) CancelProjectContract(ctx context.Context, arg CancelProjectContractParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, cancelProjectContract,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.CancelledBy,
		arg.CancelReason,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const completeProjectContract = `-- name: CompleteProjectContract :one
UPDATE project_contracts
SET status = 'completed', completed_at = now(), completed_by = $4
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'active'
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type CompleteProjectContractParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	CompletedBy    pgtype.UUID `json:"completed_by"`
}

func (q *Queries) CompleteProjectContract(ctx context.Context, arg CompleteProjectContractParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, completeProjectContract,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.CompletedBy,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const createProjectContract = `-- name: CreateProjectContract :one

INSERT INTO project_contracts (organization_id, project_id, currency, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type CreateProjectContractParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Currency       string      `json:"currency"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// ARVEND V2 -- Sprint 3: Proje Sözleşmesi (Contract). Durum makinesi:
// draft -> active -> completed; draft -> cancelled; active -> terminated.
// Tüm geçiş sorguları, project_change_orders'daki SendChangeOrder/
// RespondChangeOrderByShareLinkToken İLE AYNI "durum-korumalı UPDATE"
// desenini kullanır (WHERE status='<beklenen>') -- eşzamanlı çift geçiş
// Postgres satır kilidiyle serileşir, ikinci çağrı 0 satır alır.
func (q *Queries) CreateProjectContract(ctx context.Context, arg CreateProjectContractParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, createProjectContract,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Currency,
		arg.CreatedBy,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const getProjectContract = `-- name: GetProjectContract :one
SELECT id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason FROM project_contracts WHERE project_id = $1 AND organization_id = $2
`

type GetProjectContractParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProjectContract(ctx context.Context, arg GetProjectContractParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, getProjectContract, arg.ProjectID, arg.OrganizationID)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const getProjectContractForUpdate = `-- name: GetProjectContractForUpdate :one
SELECT id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason FROM project_contracts WHERE id = $1 AND organization_id = $2 AND project_id = $3 FOR UPDATE
`

type GetProjectContractForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetProjectContractForUpdate(ctx context.Context, arg GetProjectContractForUpdateParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, getProjectContractForUpdate, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const terminateProjectContract = `-- name: TerminateProjectContract :one
UPDATE project_contracts
SET status = 'terminated', terminated_at = now(), terminated_by = $4, termination_reason = $5
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'active'
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type TerminateProjectContractParams struct {
	ID                pgtype.UUID `json:"id"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ProjectID         pgtype.UUID `json:"project_id"`
	TerminatedBy      pgtype.UUID `json:"terminated_by"`
	TerminationReason string      `json:"termination_reason"`
}

func (q *Queries) TerminateProjectContract(ctx context.Context, arg TerminateProjectContractParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, terminateProjectContract,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.TerminatedBy,
		arg.TerminationReason,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const updateProjectContractDraftFields = `-- name: UpdateProjectContractDraftFields :one
UPDATE project_contracts
SET scope = $4, payment_terms = $5, retention_terms = $6, advance_terms = $7,
    effective_date = $8, planned_completion_date = $9
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status = 'draft'
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type UpdateProjectContractDraftFieldsParams struct {
	ID                    pgtype.UUID `json:"id"`
	OrganizationID        pgtype.UUID `json:"organization_id"`
	ProjectID             pgtype.UUID `json:"project_id"`
	Scope                 string      `json:"scope"`
	PaymentTerms          string      `json:"payment_terms"`
	RetentionTerms        string      `json:"retention_terms"`
	AdvanceTerms          string      `json:"advance_terms"`
	EffectiveDate         pgtype.Date `json:"effective_date"`
	PlannedCompletionDate pgtype.Date `json:"planned_completion_date"`
}

func (q *Queries) UpdateProjectContractDraftFields(ctx context.Context, arg UpdateProjectContractDraftFieldsParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, updateProjectContractDraftFields,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Scope,
		arg.PaymentTerms,
		arg.RetentionTerms,
		arg.AdvanceTerms,
		arg.EffectiveDate,
		arg.PlannedCompletionDate,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}

const updateProjectContractNotes = `-- name: UpdateProjectContractNotes :one
UPDATE project_contracts
SET internal_notes = $4
WHERE id = $1 AND organization_id = $2 AND project_id = $3 AND status IN ('draft', 'active')
RETURNING id, organization_id, project_id, currency, status, scope, payment_terms, retention_terms, advance_terms, effective_date, planned_completion_date, internal_notes, created_by, created_at, updated_at, activated_at, activated_by, completed_at, completed_by, cancelled_at, cancelled_by, cancel_reason, terminated_at, terminated_by, termination_reason
`

type UpdateProjectContractNotesParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	InternalNotes  string      `json:"internal_notes"`
}

func (q *Queries) UpdateProjectContractNotes(ctx context.Context, arg UpdateProjectContractNotesParams) (ProjectContract, error) {
	row := q.db.QueryRow(ctx, updateProjectContractNotes,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.InternalNotes,
	)
	var i ProjectContract
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Currency,
		&i.Status,
		&i.Scope,
		&i.PaymentTerms,
		&i.RetentionTerms,
		&i.AdvanceTerms,
		&i.EffectiveDate,
		&i.PlannedCompletionDate,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ActivatedBy,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.TerminatedAt,
		&i.TerminatedBy,
		&i.TerminationReason,
	)
	return i, err
}
