// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects p
WHERE p.organization_id = $1
  AND ($2::varchar IS NULL OR p.status = $2::varchar)
  AND ($3::uuid IS NULL OR p.customer_id = $3::uuid)
  AND ($4::varchar IS NULL OR p.project_type = $4::varchar)
  AND ($5::varchar IS NULL OR p.currency = $5::varchar)
  AND ($6::date IS NULL OR p.start_date >= $6::date)
  AND ($7::varchar IS NULL
       OR p.name ILIKE '%' || $7::varchar || '%'
       OR p.project_no ILIKE '%' || $7::varchar || '%'
       OR p.customer_name ILIKE '%' || $7::varchar || '%')
  AND ($8::uuid IS NULL OR EXISTS (
      SELECT 1 FROM project_users pu
      WHERE pu.project_id = p.id AND pu.user_id = $8::uuid
  ))
`

type CountProjectsParams struct {
	OrganizationID   pgtype.UUID `json:"organization_id"`
	Status           *string     `json:"status"`
	CustomerID       pgtype.UUID `json:"customer_id"`
	ProjectType      *string     `json:"project_type"`
	Currency         *string     `json:"currency"`
	StartFrom        pgtype.Date `json:"start_from"`
	Search           *string     `json:"search"`
	RestrictToUserID pgtype.UUID `json:"restrict_to_user_id"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects,
		arg.OrganizationID,
		arg.Status,
		arg.CustomerID,
		arg.ProjectType,
		arg.Currency,
		arg.StartFrom,
		arg.Search,
		arg.RestrictToUserID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    organization_id, project_no, name, project_type, source_offer_id, source_revision_id,
    customer_id, customer_name, customer_phone, customer_email, customer_address,
    contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
RETURNING id, organization_id, project_no, name, project_type, source_offer_id, source_revision_id, customer_id, customer_name, customer_phone, customer_email, customer_address, contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	OrganizationID   pgtype.UUID    `json:"organization_id"`
	ProjectNo        string         `json:"project_no"`
	Name             string         `json:"name"`
	ProjectType      string         `json:"project_type"`
	SourceOfferID    pgtype.UUID    `json:"source_offer_id"`
	SourceRevisionID pgtype.UUID    `json:"source_revision_id"`
	CustomerID       pgtype.UUID    `json:"customer_id"`
	CustomerName     string         `json:"customer_name"`
	CustomerPhone    string         `json:"customer_phone"`
	CustomerEmail    string         `json:"customer_email"`
	CustomerAddress  string         `json:"customer_address"`
	ContractAmount   pgtype.Numeric `json:"contract_amount"`
	Currency         string         `json:"currency"`
	Status           string         `json:"status"`
	StartDate        pgtype.Date    `json:"start_date"`
	EndDate          pgtype.Date    `json:"end_date"`
	Description      string         `json:"description"`
	InternalNotes    string         `json:"internal_notes"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.ProjectNo,
		arg.Name,
		arg.ProjectType,
		arg.SourceOfferID,
		arg.SourceRevisionID,
		arg.CustomerID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerEmail,
		arg.CustomerAddress,
		arg.ContractAmount,
		arg.Currency,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.InternalNotes,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectNo,
		&i.Name,
		&i.ProjectType,
		&i.SourceOfferID,
		&i.SourceRevisionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.ContractAmount,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, project_no, name, project_type, source_offer_id, source_revision_id, customer_id, customer_name, customer_phone, customer_email, customer_address, contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by, created_at, updated_at FROM projects WHERE id = $1 AND organization_id = $2
`

type GetProjectByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectNo,
		&i.Name,
		&i.ProjectType,
		&i.SourceOfferID,
		&i.SourceRevisionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.ContractAmount,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIDForUpdate = `-- name: GetProjectByIDForUpdate :one
SELECT id, organization_id, project_no, name, project_type, source_offer_id, source_revision_id, customer_id, customer_name, customer_phone, customer_email, customer_address, contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by, created_at, updated_at FROM projects WHERE id = $1 AND organization_id = $2 FOR UPDATE
`

type GetProjectByIDForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// GetProjectByIDForUpdate, projects satırını KİLİT ALTINDA okur. Finans
// hareketi oluşturan her uç bunu kullanır: aksi halde bir "proje
// tamamlandı/iptal edildi" güncellemesi ile bir "yeni hareket ekle"
// isteği aynı anda çakışırsa, kilit kontrolü (requireOpenProject) eski
// (kilitlenmemiş) durumu görüp hareketin geçmesine izin verebilirdi
// (bkz. denetim bulgusu -- TOCTOU).
func (q *Queries) GetProjectByIDForUpdate(ctx context.Context, arg GetProjectByIDForUpdateParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDForUpdate, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectNo,
		&i.Name,
		&i.ProjectType,
		&i.SourceOfferID,
		&i.SourceRevisionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.ContractAmount,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySourceOffer = `-- name: GetProjectBySourceOffer :one
SELECT id, organization_id, project_no, name, project_type, source_offer_id, source_revision_id, customer_id, customer_name, customer_phone, customer_email, customer_address, contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by, created_at, updated_at FROM projects WHERE source_offer_id = $1 AND organization_id = $2
ORDER BY created_at DESC LIMIT 1
`

type GetProjectBySourceOfferParams struct {
	SourceOfferID  pgtype.UUID `json:"source_offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProjectBySourceOffer(ctx context.Context, arg GetProjectBySourceOfferParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySourceOffer, arg.SourceOfferID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectNo,
		&i.Name,
		&i.ProjectType,
		&i.SourceOfferID,
		&i.SourceRevisionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.ContractAmount,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySourceRevision = `-- name: GetProjectBySourceRevision :one
SELECT id, organization_id, project_no, name, project_type, source_offer_id, source_revision_id, customer_id, customer_name, customer_phone, customer_email, customer_address, contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by, created_at, updated_at FROM projects WHERE source_revision_id = $1 AND organization_id = $2
`

type GetProjectBySourceRevisionParams struct {
	SourceRevisionID pgtype.UUID `json:"source_revision_id"`
	OrganizationID   pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetProjectBySourceRevision(ctx context.Context, arg GetProjectBySourceRevisionParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySourceRevision, arg.SourceRevisionID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectNo,
		&i.Name,
		&i.ProjectType,
		&i.SourceOfferID,
		&i.SourceRevisionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.ContractAmount,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.organization_id, p.project_no, p.name, p.project_type, p.source_offer_id, p.source_revision_id, p.customer_id, p.customer_name, p.customer_phone, p.customer_email, p.customer_address, p.contract_amount, p.currency, p.status, p.start_date, p.end_date, p.description, p.internal_notes, p.created_by, p.created_at, p.updated_at, o.offer_no, r.revision_no,
    COALESCE((SELECT sum(c.amount) FROM project_collections c
              WHERE c.project_id = p.id AND c.voided_at IS NULL), 0)::numeric(18,2) AS collected_amount,
    COALESCE((SELECT sum(e.amount) FROM project_expenses e
              WHERE e.project_id = p.id AND e.voided_at IS NULL), 0)::numeric(18,2) AS total_expenses,
    COALESCE((SELECT sum(sp.amount) FROM project_subcontractor_payments sp
              WHERE sp.project_id = p.id AND sp.voided_at IS NULL), 0)::numeric(18,2) AS subcontractor_paid,
    COALESCE((SELECT sum(GREATEST(s.contract_amount - COALESCE((
                  SELECT sum(sp2.amount) FROM project_subcontractor_payments sp2
                  WHERE sp2.subcontractor_id = s.id AND sp2.voided_at IS NULL), 0), 0))
              FROM project_subcontractors s
              WHERE s.project_id = p.id AND s.status <> 'cancelled'), 0)::numeric(18,2) AS subcontractor_remaining,
    COALESCE((SELECT count(*) FROM project_invoices i
              WHERE i.project_id = p.id AND i.invoice_type = 'sales' AND i.status <> 'cancelled'), 0)::bigint AS invoice_count,
    COALESCE((SELECT count(*) FROM project_invoices i
              WHERE i.project_id = p.id AND i.invoice_type = 'sales' AND i.status = 'paid'), 0)::bigint AS paid_invoice_count,
    -- Faz 8: onaylı ek işler/eksiltmelerin İŞARETLİ net etkisi
    -- (contract_amount'a eklenip "güncel proje bedeli"ni türetir; kolon
    -- olarak TUTULMAZ, bkz. GetProjectFinancialSummary).
    COALESCE((SELECT sum(CASE WHEN co.change_type = 'addition' THEN co.grand_total ELSE -co.grand_total END)
              FROM project_change_orders co
              WHERE co.project_id = p.id AND co.status = 'approved'), 0)::numeric(18,2) AS change_order_net
FROM projects p
JOIN offers o ON o.id = p.source_offer_id
JOIN offer_revisions r ON r.id = p.source_revision_id
WHERE p.organization_id = $1
  AND ($4::varchar IS NULL OR p.status = $4::varchar)
  AND ($5::uuid IS NULL OR p.customer_id = $5::uuid)
  AND ($6::varchar IS NULL OR p.project_type = $6::varchar)
  AND ($7::varchar IS NULL OR p.currency = $7::varchar)
  AND ($8::date IS NULL OR p.start_date >= $8::date)
  AND ($9::varchar IS NULL
       OR p.name ILIKE '%' || $9::varchar || '%'
       OR p.project_no ILIKE '%' || $9::varchar || '%'
       OR p.customer_name ILIKE '%' || $9::varchar || '%')
  -- restrict_to_user_id: RBAC/Project Membership sprint'i. NULL ise (owner/
  -- admin/legacy_user -- proje üyeliğinden MUAF roller) hiçbir filtre
  -- uygulanmaz; dolu ise (project_manager/finance/field) yalnızca
  -- kullanıcının project_users'ta üye olduğu projeler döner. EXISTS alt
  -- sorgusu SQL/repository seviyesinde çalışır -- Go'da fetch-all-then-
  -- filter YOKTUR (N+1'siz, spec §11 gereği).
  AND ($10::uuid IS NULL OR EXISTS (
      SELECT 1 FROM project_users pu
      WHERE pu.project_id = p.id AND pu.user_id = $10::uuid
  ))
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	OrganizationID   pgtype.UUID `json:"organization_id"`
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	Status           *string     `json:"status"`
	CustomerID       pgtype.UUID `json:"customer_id"`
	ProjectType      *string     `json:"project_type"`
	Currency         *string     `json:"currency"`
	StartFrom        pgtype.Date `json:"start_from"`
	Search           *string     `json:"search"`
	RestrictToUserID pgtype.UUID `json:"restrict_to_user_id"`
}

type ListProjectsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	ProjectNo              string             `json:"project_no"`
	Name                   string             `json:"name"`
	ProjectType            string             `json:"project_type"`
	SourceOfferID          pgtype.UUID        `json:"source_offer_id"`
	SourceRevisionID       pgtype.UUID        `json:"source_revision_id"`
	CustomerID             pgtype.UUID        `json:"customer_id"`
	CustomerName           string             `json:"customer_name"`
	CustomerPhone          string             `json:"customer_phone"`
	CustomerEmail          string             `json:"customer_email"`
	CustomerAddress        string             `json:"customer_address"`
	ContractAmount         pgtype.Numeric     `json:"contract_amount"`
	Currency               string             `json:"currency"`
	Status                 string             `json:"status"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	Description            string             `json:"description"`
	InternalNotes          string             `json:"internal_notes"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OfferNo                string             `json:"offer_no"`
	RevisionNo             int32              `json:"revision_no"`
	CollectedAmount        pgtype.Numeric     `json:"collected_amount"`
	TotalExpenses          pgtype.Numeric     `json:"total_expenses"`
	SubcontractorPaid      pgtype.Numeric     `json:"subcontractor_paid"`
	SubcontractorRemaining pgtype.Numeric     `json:"subcontractor_remaining"`
	InvoiceCount           int64              `json:"invoice_count"`
	PaidInvoiceCount       int64              `json:"paid_invoice_count"`
	ChangeOrderNet         pgtype.Numeric     `json:"change_order_net"`
}

// ListProjects, liste ekranının finans kolonlarını (tahsilat/masraf/
// taşeron/kâr) AYNI sorguda toplar. Her satır için ayrı sorgu açmak
// (N+1) proje sayısı büyüdüğünde listeyi kullanılamaz hale getirirdi;
// toplamlar numeric üzerinde SQL tarafında hesaplanır.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.CustomerID,
		arg.ProjectType,
		arg.Currency,
		arg.StartFrom,
		arg.Search,
		arg.RestrictToUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectNo,
			&i.Name,
			&i.ProjectType,
			&i.SourceOfferID,
			&i.SourceRevisionID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerEmail,
			&i.CustomerAddress,
			&i.ContractAmount,
			&i.Currency,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
			&i.InternalNotes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfferNo,
			&i.RevisionNo,
			&i.CollectedAmount,
			&i.TotalExpenses,
			&i.SubcontractorPaid,
			&i.SubcontractorRemaining,
			&i.InvoiceCount,
			&i.PaidInvoiceCount,
			&i.ChangeOrderNet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextProjectSeq = `-- name: NextProjectSeq :one
INSERT INTO project_counters (organization_id, year, seq) VALUES ($1, $2, 1)
ON CONFLICT (organization_id, year) DO UPDATE SET seq = project_counters.seq + 1
RETURNING seq
`

type NextProjectSeqParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Year           int32       `json:"year"`
}

func (q *Queries) NextProjectSeq(ctx context.Context, arg NextProjectSeqParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextProjectSeq, arg.OrganizationID, arg.Year)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, project_type = $4, status = $5, start_date = $6, end_date = $7,
    description = $8, internal_notes = $9
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, project_no, name, project_type, source_offer_id, source_revision_id, customer_id, customer_name, customer_phone, customer_email, customer_address, contract_amount, currency, status, start_date, end_date, description, internal_notes, created_by, created_at, updated_at
`

type UpdateProjectParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	ProjectType    string      `json:"project_type"`
	Status         string      `json:"status"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	Description    string      `json:"description"`
	InternalNotes  string      `json:"internal_notes"`
}

// UpdateProject, YALNIZCA kullanıcı tarafından değiştirilebilen alanları
// günceller. project_no, source_offer_id, source_revision_id,
// contract_amount, currency ve müşteri snapshot'ı bilinçli olarak burada
// YOKTUR -- bunlar kaynak teklife ait dondurulmuş verilerdir.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.ProjectType,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.InternalNotes,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectNo,
		&i.Name,
		&i.ProjectType,
		&i.SourceOfferID,
		&i.SourceRevisionID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerAddress,
		&i.ContractAmount,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
		&i.InternalNotes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
