// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_finance.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPaymentPlanItem = `-- name: CancelPaymentPlanItem :one
UPDATE project_payment_plan_items SET status = 'cancelled'
WHERE id = $1 AND organization_id = $2 AND status <> 'cancelled' AND project_id = $3
RETURNING id, organization_id, project_id, sort_order, name, percentage, planned_amount, due_date, status, notes, created_by, created_at, updated_at
`

type CancelPaymentPlanItemParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) CancelPaymentPlanItem(ctx context.Context, arg CancelPaymentPlanItemParams) (ProjectPaymentPlanItem, error) {
	row := q.db.QueryRow(ctx, cancelPaymentPlanItem, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectPaymentPlanItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SortOrder,
		&i.Name,
		&i.Percentage,
		&i.PlannedAmount,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one

INSERT INTO project_collections (
    organization_id, project_id, payment_plan_item_id, amount, currency,
    received_date, payment_method, description, reference_no, idempotency_key, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
RETURNING id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id
`

type CreateCollectionParams struct {
	OrganizationID    pgtype.UUID    `json:"organization_id"`
	ProjectID         pgtype.UUID    `json:"project_id"`
	PaymentPlanItemID pgtype.UUID    `json:"payment_plan_item_id"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          string         `json:"currency"`
	ReceivedDate      pgtype.Date    `json:"received_date"`
	PaymentMethod     string         `json:"payment_method"`
	Description       string         `json:"description"`
	ReferenceNo       string         `json:"reference_no"`
	IdempotencyKey    *string        `json:"idempotency_key"`
	CreatedBy         pgtype.UUID    `json:"created_by"`
}

// ============ Tahsilatlar ============
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (ProjectCollection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.OrganizationID,
		arg.ProjectID,
		arg.PaymentPlanItemID,
		arg.Amount,
		arg.Currency,
		arg.ReceivedDate,
		arg.PaymentMethod,
		arg.Description,
		arg.ReferenceNo,
		arg.IdempotencyKey,
		arg.CreatedBy,
	)
	var i ProjectCollection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.PaymentPlanItemID,
		&i.Amount,
		&i.Currency,
		&i.ReceivedDate,
		&i.PaymentMethod,
		&i.Description,
		&i.ReferenceNo,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.InvoiceID,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO project_expenses (
    organization_id, project_id, category, description, amount, currency,
    expense_date, supplier_name, invoice_no, notes, idempotency_key, created_by, change_order_id,
    cost_code_id, budget_line_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
RETURNING id, organization_id, project_id, category, description, amount, currency, expense_date, supplier_name, invoice_no, notes, created_by, created_at, updated_at, voided_at, voided_by, void_reason, idempotency_key, change_order_id, cost_code_id, budget_line_id
`

type CreateExpenseParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	Category       string         `json:"category"`
	Description    string         `json:"description"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	ExpenseDate    pgtype.Date    `json:"expense_date"`
	SupplierName   string         `json:"supplier_name"`
	InvoiceNo      string         `json:"invoice_no"`
	Notes          string         `json:"notes"`
	IdempotencyKey *string        `json:"idempotency_key"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
	ChangeOrderID  pgtype.UUID    `json:"change_order_id"`
	CostCodeID     pgtype.UUID    `json:"cost_code_id"`
	BudgetLineID   pgtype.UUID    `json:"budget_line_id"`
}

// ============ Masraflar ============
// change_order_id OPSİYONELDİR: bir masrafı bir ek işe etiketler. Bu
// SADECE proje toplamının filtrelenmiş bir görünümü içindir (bkz.
// project_change_orders.sql ListChangeOrders notu) -- masraf, NULL
// olsun ya da olmasın, proje toplamına yalnızca BİR KEZ girer.
// cost_code_id/budget_line_id de OPSİYONELDİR (Cost Control sprint'i,
// migration 0035) -- ikisi de NULL bırakılabilir (bkz. o migration'ın
// geriye dönük uyumluluk notu); servis katmanı budget_line_id verilmişse
// cost_code_id'yi o kalemden DOĞRULAR/TÜRETİR (bkz. ExpenseService notu).
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (ProjectExpense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.ExpenseDate,
		arg.SupplierName,
		arg.InvoiceNo,
		arg.Notes,
		arg.IdempotencyKey,
		arg.CreatedBy,
		arg.ChangeOrderID,
		arg.CostCodeID,
		arg.BudgetLineID,
	)
	var i ProjectExpense
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.ExpenseDate,
		&i.SupplierName,
		&i.InvoiceNo,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.ChangeOrderID,
		&i.CostCodeID,
		&i.BudgetLineID,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one

INSERT INTO project_invoices (
    organization_id, project_id, invoice_no, invoice_type, invoice_date,
    due_date, amount, currency, status, customer_name, notes, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, organization_id, project_id, invoice_no, invoice_type, invoice_date, due_date, amount, currency, status, customer_name, notes, created_by, created_at, updated_at
`

type CreateInvoiceParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	InvoiceNo      string         `json:"invoice_no"`
	InvoiceType    string         `json:"invoice_type"`
	InvoiceDate    pgtype.Date    `json:"invoice_date"`
	DueDate        pgtype.Date    `json:"due_date"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	CustomerName   string         `json:"customer_name"`
	Notes          string         `json:"notes"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

// ============ Faturalar ============
func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (ProjectInvoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrganizationID,
		arg.ProjectID,
		arg.InvoiceNo,
		arg.InvoiceType,
		arg.InvoiceDate,
		arg.DueDate,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.CustomerName,
		arg.Notes,
		arg.CreatedBy,
	)
	var i ProjectInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.InvoiceNo,
		&i.InvoiceType,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CustomerName,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceCollection = `-- name: CreateInvoiceCollection :one
INSERT INTO project_collections (
    organization_id, project_id, amount, currency, received_date,
    payment_method, description, reference_no, created_by, invoice_id
) VALUES (
    $1, $2, $3, $4, $5,
    '', $6, $7, $8, $9
)
RETURNING id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id
`

type CreateInvoiceCollectionParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	Amount         pgtype.Numeric `json:"amount"`
	Currency       string         `json:"currency"`
	ReceivedDate   pgtype.Date    `json:"received_date"`
	Description    string         `json:"description"`
	ReferenceNo    string         `json:"reference_no"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
	InvoiceID      pgtype.UUID    `json:"invoice_id"`
}

// Satış faturası "ödendi" yapılınca oluşturulan, faturaya BAĞLI tahsilat
// (bkz. migration 0050). Fatura başına tek geçerli bağlı tahsilatı kısmi
// UNIQUE indeks zorlar.
func (q *Queries) CreateInvoiceCollection(ctx context.Context, arg CreateInvoiceCollectionParams) (ProjectCollection, error) {
	row := q.db.QueryRow(ctx, createInvoiceCollection,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Amount,
		arg.Currency,
		arg.ReceivedDate,
		arg.Description,
		arg.ReferenceNo,
		arg.CreatedBy,
		arg.InvoiceID,
	)
	var i ProjectCollection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.PaymentPlanItemID,
		&i.Amount,
		&i.Currency,
		&i.ReceivedDate,
		&i.PaymentMethod,
		&i.Description,
		&i.ReferenceNo,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.InvoiceID,
	)
	return i, err
}

const createPaymentPlanItem = `-- name: CreatePaymentPlanItem :one

INSERT INTO project_payment_plan_items (
    organization_id, project_id, sort_order, name, percentage, planned_amount, due_date, notes, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, organization_id, project_id, sort_order, name, percentage, planned_amount, due_date, status, notes, created_by, created_at, updated_at
`

type CreatePaymentPlanItemParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	SortOrder      int32          `json:"sort_order"`
	Name           string         `json:"name"`
	Percentage     pgtype.Numeric `json:"percentage"`
	PlannedAmount  pgtype.Numeric `json:"planned_amount"`
	DueDate        pgtype.Date    `json:"due_date"`
	Notes          string         `json:"notes"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

// ============ Ödeme Planı ============
func (q *Queries) CreatePaymentPlanItem(ctx context.Context, arg CreatePaymentPlanItemParams) (ProjectPaymentPlanItem, error) {
	row := q.db.QueryRow(ctx, createPaymentPlanItem,
		arg.OrganizationID,
		arg.ProjectID,
		arg.SortOrder,
		arg.Name,
		arg.Percentage,
		arg.PlannedAmount,
		arg.DueDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i ProjectPaymentPlanItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SortOrder,
		&i.Name,
		&i.Percentage,
		&i.PlannedAmount,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectEvent = `-- name: CreateProjectEvent :one

INSERT INTO project_events (organization_id, project_id, event_type, user_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, project_id, event_type, user_id, metadata, created_at
`

type CreateProjectEventParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	EventType      string      `json:"event_type"`
	UserID         pgtype.UUID `json:"user_id"`
	Metadata       []byte      `json:"metadata"`
}

// ============ Proje Olayları (audit) ============
func (q *Queries) CreateProjectEvent(ctx context.Context, arg CreateProjectEventParams) (ProjectEvent, error) {
	row := q.db.QueryRow(ctx, createProjectEvent,
		arg.OrganizationID,
		arg.ProjectID,
		arg.EventType,
		arg.UserID,
		arg.Metadata,
	)
	var i ProjectEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EventType,
		&i.UserID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createSubcontractor = `-- name: CreateSubcontractor :one

INSERT INTO project_subcontractors (
    organization_id, project_id, name, company_name, phone, email, work_description,
    contract_amount, currency, start_date, end_date, status, notes, created_by, change_order_id,
    cost_code_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
RETURNING id, organization_id, project_id, name, company_name, phone, email, work_description, contract_amount, currency, start_date, end_date, status, notes, created_by, created_at, updated_at, change_order_id, cost_code_id
`

type CreateSubcontractorParams struct {
	OrganizationID  pgtype.UUID    `json:"organization_id"`
	ProjectID       pgtype.UUID    `json:"project_id"`
	Name            string         `json:"name"`
	CompanyName     string         `json:"company_name"`
	Phone           string         `json:"phone"`
	Email           string         `json:"email"`
	WorkDescription string         `json:"work_description"`
	ContractAmount  pgtype.Numeric `json:"contract_amount"`
	Currency        string         `json:"currency"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	Status          string         `json:"status"`
	Notes           string         `json:"notes"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
	ChangeOrderID   pgtype.UUID    `json:"change_order_id"`
	CostCodeID      pgtype.UUID    `json:"cost_code_id"`
}

// ============ Taşeronlar ============
// change_order_id OPSİYONELDİR (bkz. CreateExpense notu). cost_code_id
// de OPSİYONELDİR (Cost Control sprint'i, migration 0035) -- taşeron
// sözleşmesi bir cost code'a etiketlenirse Cost Control'ün "committed
// cost" kırılımına (project_commitments İLE BİRLİKTE, bkz.
// docs/cost-control.md) dahil olur.
func (q *Queries) CreateSubcontractor(ctx context.Context, arg CreateSubcontractorParams) (ProjectSubcontractor, error) {
	row := q.db.QueryRow(ctx, createSubcontractor,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Name,
		arg.CompanyName,
		arg.Phone,
		arg.Email,
		arg.WorkDescription,
		arg.ContractAmount,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
		arg.ChangeOrderID,
		arg.CostCodeID,
	)
	var i ProjectSubcontractor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.Email,
		&i.WorkDescription,
		&i.ContractAmount,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChangeOrderID,
		&i.CostCodeID,
	)
	return i, err
}

const createSubcontractorPayment = `-- name: CreateSubcontractorPayment :one

INSERT INTO project_subcontractor_payments (
    organization_id, project_id, subcontractor_id, amount, currency,
    paid_date, description, idempotency_key, created_by
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, organization_id, project_id, subcontractor_id, amount, currency, paid_date, description, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason
`

type CreateSubcontractorPaymentParams struct {
	OrganizationID  pgtype.UUID    `json:"organization_id"`
	ProjectID       pgtype.UUID    `json:"project_id"`
	SubcontractorID pgtype.UUID    `json:"subcontractor_id"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	PaidDate        pgtype.Date    `json:"paid_date"`
	Description     string         `json:"description"`
	IdempotencyKey  *string        `json:"idempotency_key"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

// ============ Taşeron Ödemeleri ============
func (q *Queries) CreateSubcontractorPayment(ctx context.Context, arg CreateSubcontractorPaymentParams) (ProjectSubcontractorPayment, error) {
	row := q.db.QueryRow(ctx, createSubcontractorPayment,
		arg.OrganizationID,
		arg.ProjectID,
		arg.SubcontractorID,
		arg.Amount,
		arg.Currency,
		arg.PaidDate,
		arg.Description,
		arg.IdempotencyKey,
		arg.CreatedBy,
	)
	var i ProjectSubcontractorPayment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SubcontractorID,
		&i.Amount,
		&i.Currency,
		&i.PaidDate,
		&i.Description,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
	)
	return i, err
}

const getActiveInvoiceCollection = `-- name: GetActiveInvoiceCollection :one
SELECT id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id FROM project_collections
WHERE invoice_id = $1 AND organization_id = $2 AND voided_at IS NULL
`

type GetActiveInvoiceCollectionParams struct {
	InvoiceID      pgtype.UUID `json:"invoice_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetActiveInvoiceCollection(ctx context.Context, arg GetActiveInvoiceCollectionParams) (ProjectCollection, error) {
	row := q.db.QueryRow(ctx, getActiveInvoiceCollection, arg.InvoiceID, arg.OrganizationID)
	var i ProjectCollection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.PaymentPlanItemID,
		&i.Amount,
		&i.Currency,
		&i.ReceivedDate,
		&i.PaymentMethod,
		&i.Description,
		&i.ReferenceNo,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.InvoiceID,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id FROM project_collections WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetCollectionParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// GetCollection, void durumundan BAĞIMSIZ okur. VoidCollection'ın
// "bulunamadı" ile "zaten iptal edilmiş" durumlarını ayırt etmesi için
// kullanılır (bkz. denetim bulgusu: ikisi de yanlışlıkla 404 dönüyordu).
// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (ProjectCollection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectCollection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.PaymentPlanItemID,
		&i.Amount,
		&i.Currency,
		&i.ReceivedDate,
		&i.PaymentMethod,
		&i.Description,
		&i.ReferenceNo,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.InvoiceID,
	)
	return i, err
}

const getCollectionByIdempotencyKey = `-- name: GetCollectionByIdempotencyKey :one
SELECT id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id FROM project_collections
WHERE project_id = $1 AND idempotency_key = $2
`

type GetCollectionByIdempotencyKeyParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

func (q *Queries) GetCollectionByIdempotencyKey(ctx context.Context, arg GetCollectionByIdempotencyKeyParams) (ProjectCollection, error) {
	row := q.db.QueryRow(ctx, getCollectionByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i ProjectCollection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.PaymentPlanItemID,
		&i.Amount,
		&i.Currency,
		&i.ReceivedDate,
		&i.PaymentMethod,
		&i.Description,
		&i.ReferenceNo,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.InvoiceID,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT id, organization_id, project_id, category, description, amount, currency, expense_date, supplier_name, invoice_no, notes, created_by, created_at, updated_at, voided_at, voided_by, void_reason, idempotency_key, change_order_id, cost_code_id, budget_line_id FROM project_expenses WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetExpenseParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// GetExpense, void durumundan BAĞIMSIZ okur (bkz. GetCollection notu).
// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (ProjectExpense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectExpense
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.ExpenseDate,
		&i.SupplierName,
		&i.InvoiceNo,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.ChangeOrderID,
		&i.CostCodeID,
		&i.BudgetLineID,
	)
	return i, err
}

const getExpenseByIdempotencyKey = `-- name: GetExpenseByIdempotencyKey :one
SELECT id, organization_id, project_id, category, description, amount, currency, expense_date, supplier_name, invoice_no, notes, created_by, created_at, updated_at, voided_at, voided_by, void_reason, idempotency_key, change_order_id, cost_code_id, budget_line_id FROM project_expenses
WHERE project_id = $1 AND idempotency_key = $2
`

type GetExpenseByIdempotencyKeyParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

func (q *Queries) GetExpenseByIdempotencyKey(ctx context.Context, arg GetExpenseByIdempotencyKeyParams) (ProjectExpense, error) {
	row := q.db.QueryRow(ctx, getExpenseByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i ProjectExpense
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.ExpenseDate,
		&i.SupplierName,
		&i.InvoiceNo,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.ChangeOrderID,
		&i.CostCodeID,
		&i.BudgetLineID,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, organization_id, project_id, invoice_no, invoice_type, invoice_date, due_date, amount, currency, status, customer_name, notes, created_by, created_at, updated_at FROM project_invoices WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetInvoiceParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (ProjectInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.InvoiceNo,
		&i.InvoiceType,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CustomerName,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentPlanItem = `-- name: GetPaymentPlanItem :one
SELECT id, organization_id, project_id, sort_order, name, percentage, planned_amount, due_date, status, notes, created_by, created_at, updated_at FROM project_payment_plan_items WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetPaymentPlanItemParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ: başka bir projenin kalem UUID'si, aynı organizasyon
// içinde bile olsa buradan görüntülenemez (bkz. IDOR denetim bulgusu --
// child-resource sorguları yalnızca organization_id ile değil, ebeveyn
// project_id ile de sınırlanmalı).
func (q *Queries) GetPaymentPlanItem(ctx context.Context, arg GetPaymentPlanItemParams) (ProjectPaymentPlanItem, error) {
	row := q.db.QueryRow(ctx, getPaymentPlanItem, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectPaymentPlanItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SortOrder,
		&i.Name,
		&i.Percentage,
		&i.PlannedAmount,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentPlanTotal = `-- name: GetPaymentPlanTotal :one
SELECT COALESCE(sum(planned_amount), 0)::numeric(18,2) AS total
FROM project_payment_plan_items
WHERE project_id = $1 AND organization_id = $2 AND status <> 'cancelled'
`

type GetPaymentPlanTotalParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// GetPaymentPlanTotal, planlanan toplamı SQL/numeric üzerinde hesaplar.
// Bu değer daha önce Go'da float64 ile satır satır toplanıyordu; aynı
// kalemlerin financial-summary'deki "planned_collections" alanıyla ikili
// birleştirme sırasında ikili (float) yuvarlama farkından ötürü
// ayrışabiliyordu (bkz. denetim bulgusu).
func (q *Queries) GetPaymentPlanTotal(ctx context.Context, arg GetPaymentPlanTotalParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getPaymentPlanTotal, arg.ProjectID, arg.OrganizationID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getProjectFinancialSummary = `-- name: GetProjectFinancialSummary :one

WITH proj AS (
    SELECT pr.contract_amount, pr.currency FROM projects pr
    WHERE pr.id = $1 AND pr.organization_id = $2
),
coll AS (
    SELECT COALESCE(sum(amount), 0)::numeric(18,2) AS total
    FROM project_collections WHERE project_id = $1 AND voided_at IS NULL
),
planned AS (
    SELECT COALESCE(sum(planned_amount), 0)::numeric(18,2) AS total
    FROM project_payment_plan_items WHERE project_id = $1 AND status <> 'cancelled'
),
expense_total AS (
    SELECT COALESCE(sum(amount), 0)::numeric(18,2) AS total
    FROM project_expenses WHERE project_id = $1 AND voided_at IS NULL
),
subpay AS (
    SELECT COALESCE(sum(amount), 0)::numeric(18,2) AS total
    FROM project_subcontractor_payments WHERE project_id = $1 AND voided_at IS NULL
),
subcommit AS (
    -- İptal edilmiş taşeron sözleşmeleri taahhüde dahil edilmez.
    SELECT COALESCE(sum(contract_amount), 0)::numeric(18,2) AS total
    FROM project_subcontractors WHERE project_id = $1 AND status <> 'cancelled'
),
subremaining AS (
    -- Kalan taahhüt taşeron BAŞINA hesaplanır ve negatife düşürülmez:
    -- fazla ödenmiş bir taşeron, diğerlerinin kalan taahhüdünü azaltmamalı.
    SELECT COALESCE(sum(GREATEST(s.contract_amount - COALESCE(p.paid, 0), 0)), 0)::numeric(18,2) AS total
    FROM project_subcontractors s
    LEFT JOIN (
        SELECT subcontractor_id, sum(amount) AS paid
        FROM project_subcontractor_payments WHERE project_id = $1 AND voided_at IS NULL
        GROUP BY subcontractor_id
    ) p ON p.subcontractor_id = s.id
    WHERE s.project_id = $1 AND s.status <> 'cancelled'
),
inv AS (
    SELECT
        COALESCE(sum(amount) FILTER (WHERE status IN ('issued','sent','paid')), 0)::numeric(18,2) AS issued_total,
        COALESCE(sum(amount) FILTER (WHERE status = 'paid'), 0)::numeric(18,2) AS paid_total
    FROM project_invoices WHERE project_id = $1 AND invoice_type = 'sales'
),
certified_by_sc AS (
    -- Sözleşme başına sertifikalı tutar: SOV kalemi başına en son
    -- sertifikalı kümülatifin toplamı (tanım subcontracts.sql
    -- GetSubcontractCertifiedToDate İLE BİREBİR AYNI).
    SELECT lc.subcontract_id, sum(lc.cumulative)::numeric(18,2) AS total
    FROM (
        SELECT DISTINCT ON (cl.subcontract_item_id) cl.subcontract_id, cl.cumulative
        FROM (
            SELECT pc.subcontract_id, pci.subcontract_item_id, pc.id AS claim_id, pc.certified_at,
                (max(pci.previous_progress_amount) + sum(pci.current_progress_amount))::numeric(18,2) AS cumulative
            FROM subcontract_progress_claim_items pci
            JOIN subcontract_progress_claims pc ON pc.id = pci.progress_claim_id
            WHERE pc.project_id = $1 AND pc.organization_id = $2 AND pc.status = 'certified'
            GROUP BY pc.subcontract_id, pci.subcontract_item_id, pc.id, pc.certified_at
        ) cl
        ORDER BY cl.subcontract_item_id, cl.certified_at DESC, cl.claim_id DESC
    ) lc
    GROUP BY lc.subcontract_id
),
new_sc_value AS (
    -- Sprint 5 sözleşmelerinin TAAHHÜT tabanı, proje İÇİNDEKİ TÜM
    -- sözleşmeler için TEK sorguda: güncel değer (GetSubcontractCurrentValue
    -- İLE AYNI formül: original + onaylı ekler - onaylı eksiltmeler).
    -- FESHEDİLMİŞ sözleşmede ise yalnızca sertifikalı tutar -- fesih kalan
    -- (yapılmamış) işi serbest bırakır; Cost Control'ün fesih taahhüdü
    -- (GetSubcontractTerminationTargets) İLE AYNI. Aksi halde Finans
    -- sekmesi serbest bırakılan kısmı hâlâ "kalan taahhüt" sayıyordu.
    SELECT sc.id,
        (CASE WHEN sc.status = 'terminated' THEN COALESCE(cert.total, 0)
              ELSE sc.original_amount + COALESCE(coe.approved_additions, 0) - COALESCE(coe.approved_deductions, 0)
         END)::numeric(18,2) AS current_value
    FROM project_subcontracts sc
    LEFT JOIN certified_by_sc cert ON cert.subcontract_id = sc.id
    LEFT JOIN (
        SELECT subcontract_id,
            COALESCE(sum(amount) FILTER (WHERE change_type = 'addition' AND status = 'approved'), 0)::numeric(18,2)
                AS approved_additions,
            COALESCE(sum(amount) FILTER (WHERE change_type = 'deduction' AND status = 'approved'), 0)::numeric(18,2)
                AS approved_deductions
        FROM subcontract_change_orders WHERE project_id = $1 AND organization_id = $2
        GROUP BY subcontract_id
    ) coe ON coe.subcontract_id = sc.id
    WHERE sc.project_id = $1 AND sc.organization_id = $2 AND sc.status NOT IN ('draft', 'cancelled')
),
newsubpay AS (
    SELECT COALESCE(sum(amount), 0)::numeric(18,2) AS total
    FROM subcontract_payments WHERE project_id = $1 AND organization_id = $2 AND voided_at IS NULL
),
newsubremaining AS (
    -- subremaining İLE AYNI ilke: kalan taahhüt sözleşme BAŞINA hesaplanır
    -- ve negatife düşürülmez (fazla ödenmiş bir sözleşme diğerlerinin
    -- kalan taahhüdünü azaltmamalı).
    SELECT COALESCE(sum(GREATEST(v.current_value - COALESCE(p.paid, 0), 0)), 0)::numeric(18,2) AS total
    FROM new_sc_value v
    LEFT JOIN (
        SELECT subcontract_id, sum(amount) AS paid
        FROM subcontract_payments WHERE project_id = $1 AND organization_id = $2 AND voided_at IS NULL
        GROUP BY subcontract_id
    ) p ON p.subcontract_id = v.id
),
co_effect AS (
    SELECT
        COALESCE(sum(grand_total) FILTER (WHERE change_type = 'addition' AND status = 'approved'), 0)::numeric(18,2)
            AS approved_additions,
        COALESCE(sum(grand_total) FILTER (WHERE change_type = 'deduction' AND status = 'approved'), 0)::numeric(18,2)
            AS approved_deductions,
        COALESCE(sum(grand_total) FILTER (WHERE change_type = 'addition' AND status IN ('draft','sent')), 0)::numeric(18,2)
            AS pending_additions,
        COALESCE(sum(grand_total) FILTER (WHERE change_type = 'deduction' AND status IN ('draft','sent')), 0)::numeric(18,2)
            AS pending_deductions
    FROM project_change_orders WHERE project_id = $1 AND organization_id = $2
),
current_value AS (
    SELECT (proj.contract_amount + co_effect.approved_additions - co_effect.approved_deductions)::numeric(18,2) AS total
    FROM proj, co_effect
)
SELECT
    proj.contract_amount AS base_contract_amount,
    proj.contract_amount,
    proj.currency,
    co_effect.approved_additions,
    co_effect.approved_deductions,
    current_value.total AS current_contract_value,
    co_effect.pending_additions,
    co_effect.pending_deductions,
    (current_value.total + co_effect.pending_additions - co_effect.pending_deductions)::numeric(18,2)
        AS potential_contract_value,
    planned.total AS planned_collections,
    coll.total    AS collected_amount,
    (current_value.total - coll.total)::numeric(18,2) AS remaining_receivable,
    expense_total.total     AS total_expenses,
    subcommit.total    AS total_subcontractor_commitment,
    subpay.total       AS subcontractor_paid,
    subremaining.total AS subcontractor_remaining,
    newsubpay.total       AS new_subcontract_paid,
    newsubremaining.total AS new_subcontract_remaining,
    inv.issued_total   AS issued_invoice_total,
    inv.paid_total     AS paid_invoice_total,
    (expense_total.total + subpay.total + newsubpay.total)::numeric(18,2) AS realized_cost,
    (expense_total.total + subpay.total + newsubpay.total + subremaining.total + newsubremaining.total)::numeric(18,2)
        AS committed_cost,
    (current_value.total - (expense_total.total + subpay.total + newsubpay.total))::numeric(18,2) AS realized_gross_profit,
    (current_value.total - (expense_total.total + subpay.total + newsubpay.total + subremaining.total + newsubremaining.total))::numeric(18,2)
        AS estimated_gross_profit,
    -- Marj yüzdesi matematiksel olarak SINIRSIZDIR (küçük bir sözleşme
    -- bedeline karşı çok büyük bir maliyet girilirse oran patlar). Cast
    -- overflow'la 500 üretmek yerine GREATEST/LEAST ile makul ama geniş
    -- bir bant içine (±99.999.999,99%) kelepçelenir -- gerçek/gerçekçi
    -- hiçbir proje bu bandı zorlamaz, yalnızca veri girişi hatalarında
    -- doygunlaşır (bkz. denetim bulgusu: eski numeric(7,2) taşıyordu).
    -- current_contract_value <= 0 (henüz nadir, ama onaylı eksiltmeler
    -- ana sözleşmeyi sıfıra kadar düşürebilir) durumunda marj güvenle 0
    -- döner -- sıfıra bölme yoktur.
    CASE WHEN current_value.total > 0
         THEN GREATEST(-99999999.99, LEAST(99999999.99,
              round((current_value.total - (expense_total.total + subpay.total + newsubpay.total)) * 100 / current_value.total, 2)))
         ELSE 0 END::numeric(10,2) AS realized_margin_percent,
    CASE WHEN current_value.total > 0
         THEN GREATEST(-99999999.99, LEAST(99999999.99,
              round((current_value.total - (expense_total.total + subpay.total + newsubpay.total + subremaining.total + newsubremaining.total)) * 100 / current_value.total, 2)))
         ELSE 0 END::numeric(10,2) AS estimated_margin_percent
FROM proj, coll, planned, expense_total, subpay, subcommit, subremaining, newsubpay, newsubremaining, inv, co_effect, current_value
`

type GetProjectFinancialSummaryParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetProjectFinancialSummaryRow struct {
	BaseContractAmount           pgtype.Numeric `json:"base_contract_amount"`
	ContractAmount               pgtype.Numeric `json:"contract_amount"`
	Currency                     string         `json:"currency"`
	ApprovedAdditions            pgtype.Numeric `json:"approved_additions"`
	ApprovedDeductions           pgtype.Numeric `json:"approved_deductions"`
	CurrentContractValue         pgtype.Numeric `json:"current_contract_value"`
	PendingAdditions             pgtype.Numeric `json:"pending_additions"`
	PendingDeductions            pgtype.Numeric `json:"pending_deductions"`
	PotentialContractValue       pgtype.Numeric `json:"potential_contract_value"`
	PlannedCollections           pgtype.Numeric `json:"planned_collections"`
	CollectedAmount              pgtype.Numeric `json:"collected_amount"`
	RemainingReceivable          pgtype.Numeric `json:"remaining_receivable"`
	TotalExpenses                pgtype.Numeric `json:"total_expenses"`
	TotalSubcontractorCommitment pgtype.Numeric `json:"total_subcontractor_commitment"`
	SubcontractorPaid            pgtype.Numeric `json:"subcontractor_paid"`
	SubcontractorRemaining       pgtype.Numeric `json:"subcontractor_remaining"`
	NewSubcontractPaid           pgtype.Numeric `json:"new_subcontract_paid"`
	NewSubcontractRemaining      pgtype.Numeric `json:"new_subcontract_remaining"`
	IssuedInvoiceTotal           pgtype.Numeric `json:"issued_invoice_total"`
	PaidInvoiceTotal             pgtype.Numeric `json:"paid_invoice_total"`
	RealizedCost                 pgtype.Numeric `json:"realized_cost"`
	CommittedCost                pgtype.Numeric `json:"committed_cost"`
	RealizedGrossProfit          pgtype.Numeric `json:"realized_gross_profit"`
	EstimatedGrossProfit         pgtype.Numeric `json:"estimated_gross_profit"`
	RealizedMarginPercent        pgtype.Numeric `json:"realized_margin_percent"`
	EstimatedMarginPercent       pgtype.Numeric `json:"estimated_margin_percent"`
}

// ============ Finans Özeti ============
// GetProjectFinancialSummary, projenin TÜM finans özetini TEK sorguda
// üretir. Bütün toplama/çıkarma işlemleri burada numeric üzerinde yapılır
// -- Go tarafında hiçbir para aritmetiği yoktur (float64 yalnızca taşıma
// tipidir), böylece kuruş hassasiyeti korunur.
//
// İki maliyet/kâr kavramı bilinçli olarak ayrı tutulur:
//
//	realized_cost  = gerçekleşen masraflar + taşerona GERÇEKTEN ödenen
//	committed_cost = realized_cost + taşeron sözleşmelerinin KALAN taahhüdü
//
// Sprint 5 follow-up: "taşerona GERÇEKTEN ödenen" artık İKİ AYRI kaynaktan
// TOPLANIR -- legacy project_subcontractor_payments (subpay/subremaining,
// YUKARIDAKİ notta anlatılan orijinal mekanizma) VE yeni Sprint 5
// subcontract_payments (newsubpay/newsubremaining). Bu iki kaynak FİZİKSEL
// OLARAK AYRI tablolara, AYRI sözleşme kayıtlarına (project_subcontractors
// vs project_subcontracts) bağlıdır -- bir proje HER İKİSİNİ de kullansa
// bile aynı ödeme iki kez sayılamaz, saf toplama güvenlidir (bkz.
// docs/subcontracts.md, migration 0039 gerekçesi). new_sc_value, draft/
// cancelled sözleşmeleri HARİÇ TUTAR -- taslağın henüz hiçbir taahhüdü/
// ödemesi anlamlı değildir (GetSubcontractCurrentValue İLE AYNI ilke).
// Faz 8: projects.contract_amount ASLA değişmez (ana sözleşme). "Güncel
// proje bedeli", onaylı ek işler/eksiltmelerden HER SEFERİNDE aggregate
// edilir -- bir kolon olarak TUTULMAZ (bkz. 0027 migration notu).
func (q *Queries) GetProjectFinancialSummary(ctx context.Context, arg GetProjectFinancialSummaryParams) (GetProjectFinancialSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProjectFinancialSummary, arg.ID, arg.OrganizationID)
	var i GetProjectFinancialSummaryRow
	err := row.Scan(
		&i.BaseContractAmount,
		&i.ContractAmount,
		&i.Currency,
		&i.ApprovedAdditions,
		&i.ApprovedDeductions,
		&i.CurrentContractValue,
		&i.PendingAdditions,
		&i.PendingDeductions,
		&i.PotentialContractValue,
		&i.PlannedCollections,
		&i.CollectedAmount,
		&i.RemainingReceivable,
		&i.TotalExpenses,
		&i.TotalSubcontractorCommitment,
		&i.SubcontractorPaid,
		&i.SubcontractorRemaining,
		&i.NewSubcontractPaid,
		&i.NewSubcontractRemaining,
		&i.IssuedInvoiceTotal,
		&i.PaidInvoiceTotal,
		&i.RealizedCost,
		&i.CommittedCost,
		&i.RealizedGrossProfit,
		&i.EstimatedGrossProfit,
		&i.RealizedMarginPercent,
		&i.EstimatedMarginPercent,
	)
	return i, err
}

const getSubcontractor = `-- name: GetSubcontractor :one
SELECT id, organization_id, project_id, name, company_name, phone, email, work_description, contract_amount, currency, start_date, end_date, status, notes, created_by, created_at, updated_at, change_order_id, cost_code_id FROM project_subcontractors WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetSubcontractorParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ: CreateSubcontractorPayment'ın taşeronu URL'deki
// projeye ait olduğunu doğrulaması için (bkz. GetPaymentPlanItem notu --
// aksi halde Proje A'ya yetkili biri, Proje B'nin taşeron UUID'sini
// bilerek Proje A URL'si üzerinden ona ödeme kaydedebilirdi).
func (q *Queries) GetSubcontractor(ctx context.Context, arg GetSubcontractorParams) (ProjectSubcontractor, error) {
	row := q.db.QueryRow(ctx, getSubcontractor, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectSubcontractor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.Email,
		&i.WorkDescription,
		&i.ContractAmount,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChangeOrderID,
		&i.CostCodeID,
	)
	return i, err
}

const getSubcontractorPayment = `-- name: GetSubcontractorPayment :one
SELECT id, organization_id, project_id, subcontractor_id, amount, currency, paid_date, description, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason FROM project_subcontractor_payments WHERE id = $1 AND organization_id = $2 AND project_id = $3
`

type GetSubcontractorPaymentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// GetSubcontractorPayment, void durumundan BAĞIMSIZ okur (bkz.
// GetCollection notu). project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) GetSubcontractorPayment(ctx context.Context, arg GetSubcontractorPaymentParams) (ProjectSubcontractorPayment, error) {
	row := q.db.QueryRow(ctx, getSubcontractorPayment, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i ProjectSubcontractorPayment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SubcontractorID,
		&i.Amount,
		&i.Currency,
		&i.PaidDate,
		&i.Description,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
	)
	return i, err
}

const getSubcontractorPaymentByIdempotencyKey = `-- name: GetSubcontractorPaymentByIdempotencyKey :one
SELECT id, organization_id, project_id, subcontractor_id, amount, currency, paid_date, description, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason FROM project_subcontractor_payments
WHERE subcontractor_id = $1 AND idempotency_key = $2
`

type GetSubcontractorPaymentByIdempotencyKeyParams struct {
	SubcontractorID pgtype.UUID `json:"subcontractor_id"`
	IdempotencyKey  *string     `json:"idempotency_key"`
}

// GetSubcontractorPaymentByIdempotencyKey, anahtarı TAŞERON bazında
// arar (proje bazında DEĞİL) -- aksi halde aynı projede iki farklı
// taşerona aynı anahtarla girilen ödemelerden biri diğerinin kaydı
// sanılıp sessizce kaybolurdu (bkz. 0026 migration notu).
func (q *Queries) GetSubcontractorPaymentByIdempotencyKey(ctx context.Context, arg GetSubcontractorPaymentByIdempotencyKeyParams) (ProjectSubcontractorPayment, error) {
	row := q.db.QueryRow(ctx, getSubcontractorPaymentByIdempotencyKey, arg.SubcontractorID, arg.IdempotencyKey)
	var i ProjectSubcontractorPayment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SubcontractorID,
		&i.Amount,
		&i.Currency,
		&i.PaidDate,
		&i.Description,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id FROM project_collections
WHERE project_id = $1 AND organization_id = $2
ORDER BY received_date DESC, created_at DESC
`

type ListCollectionsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ProjectCollection, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCollection
	for rows.Next() {
		var i ProjectCollection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.PaymentPlanItemID,
			&i.Amount,
			&i.Currency,
			&i.ReceivedDate,
			&i.PaymentMethod,
			&i.Description,
			&i.ReferenceNo,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.InvoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, organization_id, project_id, category, description, amount, currency, expense_date, supplier_name, invoice_no, notes, created_by, created_at, updated_at, voided_at, voided_by, void_reason, idempotency_key, change_order_id, cost_code_id, budget_line_id FROM project_expenses
WHERE project_id = $1 AND organization_id = $2
ORDER BY expense_date DESC, created_at DESC
`

type ListExpensesParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ProjectExpense, error) {
	rows, err := q.db.Query(ctx, listExpenses, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectExpense
	for rows.Next() {
		var i ProjectExpense
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Category,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.ExpenseDate,
			&i.SupplierName,
			&i.InvoiceNo,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.IdempotencyKey,
			&i.ChangeOrderID,
			&i.CostCodeID,
			&i.BudgetLineID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, organization_id, project_id, invoice_no, invoice_type, invoice_date, due_date, amount, currency, status, customer_name, notes, created_by, created_at, updated_at FROM project_invoices
WHERE project_id = $1 AND organization_id = $2
ORDER BY invoice_date DESC, created_at DESC
`

type ListInvoicesParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ProjectInvoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectInvoice
	for rows.Next() {
		var i ProjectInvoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.InvoiceNo,
			&i.InvoiceType,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CustomerName,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentPlanItems = `-- name: ListPaymentPlanItems :many
SELECT p.id, p.organization_id, p.project_id, p.sort_order, p.name, p.percentage, p.planned_amount, p.due_date, p.status, p.notes, p.created_by, p.created_at, p.updated_at,
       COALESCE((SELECT sum(c.amount) FROM project_collections c
                 WHERE c.payment_plan_item_id = p.id AND c.voided_at IS NULL), 0)::numeric(18,2) AS collected_amount
FROM project_payment_plan_items p
WHERE p.project_id = $1 AND p.organization_id = $2
ORDER BY p.sort_order ASC, p.created_at ASC
`

type ListPaymentPlanItemsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListPaymentPlanItemsRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	SortOrder       int32              `json:"sort_order"`
	Name            string             `json:"name"`
	Percentage      pgtype.Numeric     `json:"percentage"`
	PlannedAmount   pgtype.Numeric     `json:"planned_amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	Status          string             `json:"status"`
	Notes           string             `json:"notes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CollectedAmount pgtype.Numeric     `json:"collected_amount"`
}

// ListPaymentPlanItems, her kalemin o kaleme bağlı GEÇERLİ (void
// edilmemiş) tahsilat toplamını da getirir -- böylece partial/paid
// durumu ve kalan tutar, kalem başına ayrı sorgu açmadan (N+1 yok)
// okuma anında türetilebilir.
func (q *Queries) ListPaymentPlanItems(ctx context.Context, arg ListPaymentPlanItemsParams) ([]ListPaymentPlanItemsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentPlanItems, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentPlanItemsRow
	for rows.Next() {
		var i ListPaymentPlanItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.SortOrder,
			&i.Name,
			&i.Percentage,
			&i.PlannedAmount,
			&i.DueDate,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectEvents = `-- name: ListProjectEvents :many
SELECT id, organization_id, project_id, event_type, user_id, metadata, created_at FROM project_events
WHERE project_id = $1 AND organization_id = $2
ORDER BY created_at ASC
`

type ListProjectEventsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListProjectEvents(ctx context.Context, arg ListProjectEventsParams) ([]ProjectEvent, error) {
	rows, err := q.db.Query(ctx, listProjectEvents, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectEvent
	for rows.Next() {
		var i ProjectEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.EventType,
			&i.UserID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcontractorPayments = `-- name: ListSubcontractorPayments :many
SELECT id, organization_id, project_id, subcontractor_id, amount, currency, paid_date, description, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason FROM project_subcontractor_payments
WHERE project_id = $1 AND organization_id = $2
ORDER BY paid_date DESC, created_at DESC
`

type ListSubcontractorPaymentsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListSubcontractorPayments(ctx context.Context, arg ListSubcontractorPaymentsParams) ([]ProjectSubcontractorPayment, error) {
	rows, err := q.db.Query(ctx, listSubcontractorPayments, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSubcontractorPayment
	for rows.Next() {
		var i ProjectSubcontractorPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.SubcontractorID,
			&i.Amount,
			&i.Currency,
			&i.PaidDate,
			&i.Description,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcontractors = `-- name: ListSubcontractors :many
SELECT s.id, s.organization_id, s.project_id, s.name, s.company_name, s.phone, s.email, s.work_description, s.contract_amount, s.currency, s.start_date, s.end_date, s.status, s.notes, s.created_by, s.created_at, s.updated_at, s.change_order_id, s.cost_code_id,
       COALESCE((SELECT sum(p.amount) FROM project_subcontractor_payments p
                 WHERE p.subcontractor_id = s.id AND p.voided_at IS NULL), 0)::numeric(18,2) AS paid_amount
FROM project_subcontractors s
WHERE s.project_id = $1 AND s.organization_id = $2
ORDER BY s.created_at ASC
`

type ListSubcontractorsParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListSubcontractorsRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Name            string             `json:"name"`
	CompanyName     string             `json:"company_name"`
	Phone           string             `json:"phone"`
	Email           string             `json:"email"`
	WorkDescription string             `json:"work_description"`
	ContractAmount  pgtype.Numeric     `json:"contract_amount"`
	Currency        string             `json:"currency"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Status          string             `json:"status"`
	Notes           string             `json:"notes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ChangeOrderID   pgtype.UUID        `json:"change_order_id"`
	CostCodeID      pgtype.UUID        `json:"cost_code_id"`
	PaidAmount      pgtype.Numeric     `json:"paid_amount"`
}

// ListSubcontractors, her taşeronun GEÇERLİ ödeme toplamını da getirir
// (kalan = contract_amount - paid, kart başına ayrı sorgu yok).
func (q *Queries) ListSubcontractors(ctx context.Context, arg ListSubcontractorsParams) ([]ListSubcontractorsRow, error) {
	rows, err := q.db.Query(ctx, listSubcontractors, arg.ProjectID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubcontractorsRow
	for rows.Next() {
		var i ListSubcontractorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Name,
			&i.CompanyName,
			&i.Phone,
			&i.Email,
			&i.WorkDescription,
			&i.ContractAmount,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangeOrderID,
			&i.CostCodeID,
			&i.PaidAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubcontractorForPayment = `-- name: LockSubcontractorForPayment :one
SELECT s.contract_amount,
       COALESCE((SELECT sum(p.amount) FROM project_subcontractor_payments p
                 WHERE p.subcontractor_id = s.id AND p.voided_at IS NULL), 0)::numeric(18,2) AS paid_amount
FROM project_subcontractors s
WHERE s.id = $1 AND s.organization_id = $2 AND s.project_id = $3
FOR UPDATE OF s
`

type LockSubcontractorForPaymentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

type LockSubcontractorForPaymentRow struct {
	ContractAmount pgtype.Numeric `json:"contract_amount"`
	PaidAmount     pgtype.Numeric `json:"paid_amount"`
}

// Ödeme girişinde taşeron satırı KİLİTLENİR ve sözleşme bedeli ile geçerli
// (iptal edilmemiş) ödeme toplamı okunur: toplam ödeme sözleşme bedelini
// aşamaz (sahada 2026-10: 1.000 TL'lik sözleşmeye 21.000 TL ödeme
// girilebilmişti). Kilit, aynı anda girilen iki ödemenin sınırı birlikte
// delmesini önler.
func (q *Queries) LockSubcontractorForPayment(ctx context.Context, arg LockSubcontractorForPaymentParams) (LockSubcontractorForPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockSubcontractorForPayment, arg.ID, arg.OrganizationID, arg.ProjectID)
	var i LockSubcontractorForPaymentRow
	err := row.Scan(&i.ContractAmount, &i.PaidAmount)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE project_expenses
SET category = $3, description = $4, amount = $5, expense_date = $6,
    supplier_name = $7, invoice_no = $8, notes = $9, cost_code_id = $11, budget_line_id = $12
WHERE id = $1 AND organization_id = $2 AND voided_at IS NULL AND project_id = $10
RETURNING id, organization_id, project_id, category, description, amount, currency, expense_date, supplier_name, invoice_no, notes, created_by, created_at, updated_at, voided_at, voided_by, void_reason, idempotency_key, change_order_id, cost_code_id, budget_line_id
`

type UpdateExpenseParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Category       string         `json:"category"`
	Description    string         `json:"description"`
	Amount         pgtype.Numeric `json:"amount"`
	ExpenseDate    pgtype.Date    `json:"expense_date"`
	SupplierName   string         `json:"supplier_name"`
	InvoiceNo      string         `json:"invoice_no"`
	Notes          string         `json:"notes"`
	ProjectID      pgtype.UUID    `json:"project_id"`
	CostCodeID     pgtype.UUID    `json:"cost_code_id"`
	BudgetLineID   pgtype.UUID    `json:"budget_line_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu). cost_code_id/
// budget_line_id, Cost Control sprint'i (migration 0035) -- opsiyonel.
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (ProjectExpense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.OrganizationID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.ExpenseDate,
		arg.SupplierName,
		arg.InvoiceNo,
		arg.Notes,
		arg.ProjectID,
		arg.CostCodeID,
		arg.BudgetLineID,
	)
	var i ProjectExpense
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.ExpenseDate,
		&i.SupplierName,
		&i.InvoiceNo,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.ChangeOrderID,
		&i.CostCodeID,
		&i.BudgetLineID,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE project_invoices SET status = $3
WHERE id = $1 AND organization_id = $2 AND project_id = $4
RETURNING id, organization_id, project_id, invoice_no, invoice_type, invoice_date, due_date, amount, currency, status, customer_name, notes, created_by, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Status         string      `json:"status"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (ProjectInvoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus,
		arg.ID,
		arg.OrganizationID,
		arg.Status,
		arg.ProjectID,
	)
	var i ProjectInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.InvoiceNo,
		&i.InvoiceType,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CustomerName,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentPlanItem = `-- name: UpdatePaymentPlanItem :one
UPDATE project_payment_plan_items
SET sort_order = $3, name = $4, percentage = $5, planned_amount = $6, due_date = $7, notes = $8
WHERE id = $1 AND organization_id = $2 AND status <> 'cancelled' AND project_id = $9
RETURNING id, organization_id, project_id, sort_order, name, percentage, planned_amount, due_date, status, notes, created_by, created_at, updated_at
`

type UpdatePaymentPlanItemParams struct {
	ID             pgtype.UUID    `json:"id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	SortOrder      int32          `json:"sort_order"`
	Name           string         `json:"name"`
	Percentage     pgtype.Numeric `json:"percentage"`
	PlannedAmount  pgtype.Numeric `json:"planned_amount"`
	DueDate        pgtype.Date    `json:"due_date"`
	Notes          string         `json:"notes"`
	ProjectID      pgtype.UUID    `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) UpdatePaymentPlanItem(ctx context.Context, arg UpdatePaymentPlanItemParams) (ProjectPaymentPlanItem, error) {
	row := q.db.QueryRow(ctx, updatePaymentPlanItem,
		arg.ID,
		arg.OrganizationID,
		arg.SortOrder,
		arg.Name,
		arg.Percentage,
		arg.PlannedAmount,
		arg.DueDate,
		arg.Notes,
		arg.ProjectID,
	)
	var i ProjectPaymentPlanItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SortOrder,
		&i.Name,
		&i.Percentage,
		&i.PlannedAmount,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubcontractor = `-- name: UpdateSubcontractor :one
UPDATE project_subcontractors
SET name = $3, company_name = $4, phone = $5, email = $6, work_description = $7,
    contract_amount = $8, start_date = $9, end_date = $10, status = $11, notes = $12, cost_code_id = $14
WHERE id = $1 AND organization_id = $2 AND project_id = $13
RETURNING id, organization_id, project_id, name, company_name, phone, email, work_description, contract_amount, currency, start_date, end_date, status, notes, created_by, created_at, updated_at, change_order_id, cost_code_id
`

type UpdateSubcontractorParams struct {
	ID              pgtype.UUID    `json:"id"`
	OrganizationID  pgtype.UUID    `json:"organization_id"`
	Name            string         `json:"name"`
	CompanyName     string         `json:"company_name"`
	Phone           string         `json:"phone"`
	Email           string         `json:"email"`
	WorkDescription string         `json:"work_description"`
	ContractAmount  pgtype.Numeric `json:"contract_amount"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	Status          string         `json:"status"`
	Notes           string         `json:"notes"`
	ProjectID       pgtype.UUID    `json:"project_id"`
	CostCodeID      pgtype.UUID    `json:"cost_code_id"`
}

// project_id EKLENDİ (bkz. GetSubcontractor notu). cost_code_id, Cost
// Control sprint'i (migration 0035) -- opsiyonel.
func (q *Queries) UpdateSubcontractor(ctx context.Context, arg UpdateSubcontractorParams) (ProjectSubcontractor, error) {
	row := q.db.QueryRow(ctx, updateSubcontractor,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.CompanyName,
		arg.Phone,
		arg.Email,
		arg.WorkDescription,
		arg.ContractAmount,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.Notes,
		arg.ProjectID,
		arg.CostCodeID,
	)
	var i ProjectSubcontractor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyName,
		&i.Phone,
		&i.Email,
		&i.WorkDescription,
		&i.ContractAmount,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChangeOrderID,
		&i.CostCodeID,
	)
	return i, err
}

const voidCollection = `-- name: VoidCollection :one
UPDATE project_collections
SET voided_at = now(), voided_by = $3, void_reason = $4
WHERE id = $1 AND organization_id = $2 AND voided_at IS NULL AND project_id = $5
RETURNING id, organization_id, project_id, payment_plan_item_id, amount, currency, received_date, payment_method, description, reference_no, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason, invoice_id
`

type VoidCollectionParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	VoidedBy       pgtype.UUID `json:"voided_by"`
	VoidReason     string      `json:"void_reason"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) VoidCollection(ctx context.Context, arg VoidCollectionParams) (ProjectCollection, error) {
	row := q.db.QueryRow(ctx, voidCollection,
		arg.ID,
		arg.OrganizationID,
		arg.VoidedBy,
		arg.VoidReason,
		arg.ProjectID,
	)
	var i ProjectCollection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.PaymentPlanItemID,
		&i.Amount,
		&i.Currency,
		&i.ReceivedDate,
		&i.PaymentMethod,
		&i.Description,
		&i.ReferenceNo,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.InvoiceID,
	)
	return i, err
}

const voidExpense = `-- name: VoidExpense :one
UPDATE project_expenses
SET voided_at = now(), voided_by = $3, void_reason = $4
WHERE id = $1 AND organization_id = $2 AND voided_at IS NULL AND project_id = $5
RETURNING id, organization_id, project_id, category, description, amount, currency, expense_date, supplier_name, invoice_no, notes, created_by, created_at, updated_at, voided_at, voided_by, void_reason, idempotency_key, change_order_id, cost_code_id, budget_line_id
`

type VoidExpenseParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	VoidedBy       pgtype.UUID `json:"voided_by"`
	VoidReason     string      `json:"void_reason"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) VoidExpense(ctx context.Context, arg VoidExpenseParams) (ProjectExpense, error) {
	row := q.db.QueryRow(ctx, voidExpense,
		arg.ID,
		arg.OrganizationID,
		arg.VoidedBy,
		arg.VoidReason,
		arg.ProjectID,
	)
	var i ProjectExpense
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.ExpenseDate,
		&i.SupplierName,
		&i.InvoiceNo,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.ChangeOrderID,
		&i.CostCodeID,
		&i.BudgetLineID,
	)
	return i, err
}

const voidInvoiceCollections = `-- name: VoidInvoiceCollections :many
UPDATE project_collections
SET voided_at = now(), voided_by = $1, void_reason = $2
WHERE invoice_id = $3 AND organization_id = $4 AND voided_at IS NULL
RETURNING id, amount
`

type VoidInvoiceCollectionsParams struct {
	VoidedBy       pgtype.UUID `json:"voided_by"`
	VoidReason     string      `json:"void_reason"`
	InvoiceID      pgtype.UUID `json:"invoice_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type VoidInvoiceCollectionsRow struct {
	ID     pgtype.UUID    `json:"id"`
	Amount pgtype.Numeric `json:"amount"`
}

// Fatura "ödendi"den çıkınca bağlı tahsilat(lar) iptal edilir (silinmez,
// VoidCollection ile aynı iz).
func (q *Queries) VoidInvoiceCollections(ctx context.Context, arg VoidInvoiceCollectionsParams) ([]VoidInvoiceCollectionsRow, error) {
	rows, err := q.db.Query(ctx, voidInvoiceCollections,
		arg.VoidedBy,
		arg.VoidReason,
		arg.InvoiceID,
		arg.OrganizationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoidInvoiceCollectionsRow
	for rows.Next() {
		var i VoidInvoiceCollectionsRow
		if err := rows.Scan(&i.ID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidSubcontractorPayment = `-- name: VoidSubcontractorPayment :one
UPDATE project_subcontractor_payments
SET voided_at = now(), voided_by = $3, void_reason = $4
WHERE id = $1 AND organization_id = $2 AND voided_at IS NULL AND project_id = $5
RETURNING id, organization_id, project_id, subcontractor_id, amount, currency, paid_date, description, idempotency_key, created_by, created_at, updated_at, voided_at, voided_by, void_reason
`

type VoidSubcontractorPaymentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	VoidedBy       pgtype.UUID `json:"voided_by"`
	VoidReason     string      `json:"void_reason"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

// project_id EKLENDİ (bkz. GetPaymentPlanItem notu).
func (q *Queries) VoidSubcontractorPayment(ctx context.Context, arg VoidSubcontractorPaymentParams) (ProjectSubcontractorPayment, error) {
	row := q.db.QueryRow(ctx, voidSubcontractorPayment,
		arg.ID,
		arg.OrganizationID,
		arg.VoidedBy,
		arg.VoidReason,
		arg.ProjectID,
	)
	var i ProjectSubcontractorPayment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SubcontractorID,
		&i.Amount,
		&i.Currency,
		&i.PaidDate,
		&i.Description,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
	)
	return i, err
}
