// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingPushNotifications = `-- name: ClaimPendingPushNotifications :many
UPDATE notifications SET pushed_at = now()
WHERE id IN (
    SELECT n.id FROM notifications n
    WHERE n.pushed_at IS NULL AND n.created_at > $1::timestamptz
    ORDER BY n.created_at
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
RETURNING id, organization_id, user_id, type, title, body, entity_type, entity_id, project_id, action_target, read_at, created_at, group_count, pushed_at
`

type ClaimPendingPushNotificationsParams struct {
	Since   pgtype.Timestamptz `json:"since"`
	MaxRows int32              `json:"max_rows"`
}

// Gönderilecek bildirimleri alır ve aynı anda işaretler (iki gönderici
// aynı satırı almasın). En fazla bir kez gönderim: telefona ulaşmadıysa
// bildirim zilde yine durur.
func (q *Queries) ClaimPendingPushNotifications(ctx context.Context, arg ClaimPendingPushNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, claimPendingPushNotifications, arg.Since, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.EntityType,
			&i.EntityID,
			&i.ProjectID,
			&i.ActionTarget,
			&i.ReadAt,
			&i.CreatedAt,
			&i.GroupCount,
			&i.PushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllUserPushDevices = `-- name: DeleteAllUserPushDevices :exec
DELETE FROM push_devices WHERE user_id = $1
`

// Pasifleştirilen/silinen kullanıcının telefonları silinir: bildirim
// almaya devam etmesin (bkz. user_lifecycle.go deactivateUser/deleteUser).
func (q *Queries) DeleteAllUserPushDevices(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserPushDevices, userID)
	return err
}

const deletePushDeviceByToken = `-- name: DeletePushDeviceByToken :execrows
DELETE FROM push_devices WHERE token = $1
`

func (q *Queries) DeletePushDeviceByToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushDeviceByToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserPushDevice = `-- name: DeleteUserPushDevice :execrows
DELETE FROM push_devices WHERE token = $1 AND user_id = $2
`

type DeleteUserPushDeviceParams struct {
	Token  string      `json:"token"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserPushDevice(ctx context.Context, arg DeleteUserPushDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserPushDevice, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPushTokensForUser = `-- name: ListPushTokensForUser :many
SELECT d.token
FROM push_devices d
JOIN users u ON u.id = d.user_id
WHERE d.user_id = $1 AND u.is_active AND u.deleted_at IS NULL
ORDER BY d.last_seen_at DESC
`

// Yalnızca aktif, silinmemiş kullanıcının cihazları: pasifleştirme cihaz
// kayıtlarını da siler, ama ondan önce yazılmış bir bildirim ya da başka
// bir yoldan kalmış bir kayıt engellenen kişinin telefonuna gitmesin.
func (q *Queries) ListPushTokensForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPushTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipStalePushNotifications = `-- name: SkipStalePushNotifications :execrows
UPDATE notifications SET pushed_at = now()
WHERE pushed_at IS NULL AND created_at <= $1::timestamptz
`

// Push kapalıyken biriken eski bildirimler telefona sonradan yağmasın.
func (q *Queries) SkipStalePushNotifications(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, skipStalePushNotifications, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPushDevice = `-- name: UpsertPushDevice :one
INSERT INTO push_devices (organization_id, user_id, token, platform, app_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (token) DO UPDATE
SET organization_id = EXCLUDED.organization_id,
    user_id         = EXCLUDED.user_id,
    platform        = EXCLUDED.platform,
    app_version     = EXCLUDED.app_version,
    last_seen_at    = now()
RETURNING id, organization_id, user_id, token, platform, app_version, created_at, last_seen_at
`

type UpsertPushDeviceParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Token          string      `json:"token"`
	Platform       string      `json:"platform"`
	AppVersion     string      `json:"app_version"`
}

// Aynı token başka bir kullanıcıya geçebilir (telefonda hesap değişti).
func (q *Queries) UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) (PushDevice, error) {
	row := q.db.QueryRow(ctx, upsertPushDevice,
		arg.OrganizationID,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.AppVersion,
	)
	var i PushDevice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.AppVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
