// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: salary_payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSalaryPayment = `-- name: CreateSalaryPayment :one
INSERT INTO salary_payments (organization_id, employee_id, period, payment_type, amount, paid_date, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, employee_id, period, payment_type, amount, paid_date, description, created_by, created_at, updated_at
`

type CreateSalaryPaymentParams struct {
	OrganizationID pgtype.UUID    `json:"organization_id"`
	EmployeeID     pgtype.UUID    `json:"employee_id"`
	Period         string         `json:"period"`
	PaymentType    string         `json:"payment_type"`
	Amount         pgtype.Numeric `json:"amount"`
	PaidDate       pgtype.Date    `json:"paid_date"`
	Description    string         `json:"description"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateSalaryPayment(ctx context.Context, arg CreateSalaryPaymentParams) (SalaryPayment, error) {
	row := q.db.QueryRow(ctx, createSalaryPayment,
		arg.OrganizationID,
		arg.EmployeeID,
		arg.Period,
		arg.PaymentType,
		arg.Amount,
		arg.PaidDate,
		arg.Description,
		arg.CreatedBy,
	)
	var i SalaryPayment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EmployeeID,
		&i.Period,
		&i.PaymentType,
		&i.Amount,
		&i.PaidDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSalaryPayment = `-- name: DeleteSalaryPayment :execrows
DELETE FROM salary_payments WHERE id = $1 AND organization_id = $2
`

type DeleteSalaryPaymentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteSalaryPayment(ctx context.Context, arg DeleteSalaryPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSalaryPayment, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSalaryPaymentsByPeriod = `-- name: ListSalaryPaymentsByPeriod :many
SELECT p.id, p.organization_id, p.employee_id, p.period, p.payment_type, p.amount, p.paid_date, p.description, p.created_by, p.created_at, p.updated_at, e.full_name AS employee_name
FROM salary_payments p
JOIN employees e ON e.id = p.employee_id
WHERE p.organization_id = $1
  AND p.period = $2
ORDER BY p.paid_date DESC, p.created_at DESC
`

type ListSalaryPaymentsByPeriodParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Period         string      `json:"period"`
}

type ListSalaryPaymentsByPeriodRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	EmployeeID     pgtype.UUID        `json:"employee_id"`
	Period         string             `json:"period"`
	PaymentType    string             `json:"payment_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaidDate       pgtype.Date        `json:"paid_date"`
	Description    string             `json:"description"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EmployeeName   string             `json:"employee_name"`
}

func (q *Queries) ListSalaryPaymentsByPeriod(ctx context.Context, arg ListSalaryPaymentsByPeriodParams) ([]ListSalaryPaymentsByPeriodRow, error) {
	rows, err := q.db.Query(ctx, listSalaryPaymentsByPeriod, arg.OrganizationID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalaryPaymentsByPeriodRow
	for rows.Next() {
		var i ListSalaryPaymentsByPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EmployeeID,
			&i.Period,
			&i.PaymentType,
			&i.Amount,
			&i.PaidDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payrollSummaryByPeriod = `-- name: PayrollSummaryByPeriod :many
WITH att AS (
    SELECT employee_id,
           SUM(CASE status WHEN 'geldi' THEN 1 WHEN 'yarım gün' THEN 0.5 ELSE 0 END)::numeric(8,1) AS worked_days,
           SUM(work_hours)::numeric(10,2) AS work_hours
    FROM attendance_logs
    WHERE organization_id = $1
      AND date_trunc('month', date) = to_date($2::text, 'YYYY-MM')
    GROUP BY employee_id
), pay AS (
    SELECT employee_id,
           SUM(amount)::numeric(18,2) AS paid_total,
           COUNT(*)::int AS payment_count
    FROM salary_payments
    WHERE organization_id = $1
      AND period = $2::text
    GROUP BY employee_id
)
SELECT e.id AS employee_id,
       e.full_name,
       e.position,
       e.salary,
       e.daily_wage,
       e.is_active,
       COALESCE(att.worked_days, 0)::numeric(8,1)  AS worked_days,
       COALESCE(att.work_hours, 0)::numeric(10,2)  AS work_hours,
       COALESCE(pay.paid_total, 0)::numeric(18,2)  AS paid_total,
       COALESCE(pay.payment_count, 0)::int         AS payment_count
FROM employees e
LEFT JOIN att ON att.employee_id = e.id
LEFT JOIN pay ON pay.employee_id = e.id
WHERE e.organization_id = $1
  AND (e.is_active OR att.employee_id IS NOT NULL OR pay.employee_id IS NOT NULL)
ORDER BY e.full_name
`

type PayrollSummaryByPeriodParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Period         string      `json:"period"`
}

type PayrollSummaryByPeriodRow struct {
	EmployeeID   pgtype.UUID    `json:"employee_id"`
	FullName     string         `json:"full_name"`
	Position     string         `json:"position"`
	Salary       pgtype.Numeric `json:"salary"`
	DailyWage    pgtype.Numeric `json:"daily_wage"`
	IsActive     bool           `json:"is_active"`
	WorkedDays   pgtype.Numeric `json:"worked_days"`
	WorkHours    pgtype.Numeric `json:"work_hours"`
	PaidTotal    pgtype.Numeric `json:"paid_total"`
	PaymentCount int32          `json:"payment_count"`
}

// PayrollSummaryByPeriod: ayın ödeme tablosu, personel başına bir satır.
// Çalışılan gün puantajdan gelir: 'geldi' = 1, 'yarım gün' = 0.5,
// 'gelmedi'/'izinli' = 0. Kalan borç HESAPLANMAZ -- aylık maaş mı yevmiye mi
// esas alınacağı firmadan firmaya değişiyor (BYZ verisinde her personelin
// ikisi de dolu); yanlış bir "kalan" rakamı göstermektense ham sayılar verilir.
// Satırda olanlar: aktif personel + (pasif/arşivli de olsa) o ay puantajı
// ya da ödemesi bulunan herkes -- işten ayrılanın son maaşı kaybolmasın.
func (q *Queries) PayrollSummaryByPeriod(ctx context.Context, arg PayrollSummaryByPeriodParams) ([]PayrollSummaryByPeriodRow, error) {
	rows, err := q.db.Query(ctx, payrollSummaryByPeriod, arg.OrganizationID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollSummaryByPeriodRow
	for rows.Next() {
		var i PayrollSummaryByPeriodRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.FullName,
			&i.Position,
			&i.Salary,
			&i.DailyWage,
			&i.IsActive,
			&i.WorkedDays,
			&i.WorkHours,
			&i.PaidTotal,
			&i.PaymentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
