// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT count(*) FROM users WHERE organization_id = $1 AND is_active = true
`

func (q *Queries) CountActiveUsers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE organization_id = $1
`

func (q *Queries) CountUsers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (organization_id, username, password_hash, full_name, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password
`

type CreateUserParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Username       string      `json:"username"`
	PasswordHash   string      `json:"password_hash"`
	FullName       string      `json:"full_name"`
	Role           string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrganizationID,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
	)
	return i, err
}

const createUserWithOptions = `-- name: CreateUserWithOptions :one
INSERT INTO users (organization_id, username, password_hash, full_name, role, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password
`

type CreateUserWithOptionsParams struct {
	OrganizationID     pgtype.UUID `json:"organization_id"`
	Username           string      `json:"username"`
	PasswordHash       string      `json:"password_hash"`
	FullName           string      `json:"full_name"`
	Role               string      `json:"role"`
	MustChangePassword bool        `json:"must_change_password"`
}

// Platform seviyesi kullanıcı oluşturma (Super Admin CLI: organization_id
// NULL, role='super_admin') VE Super Admin'in yeni firma için provision
// ettiği ilk Owner (organization_id dolu, must_change_password=true) --
// CreateUser'ın aksine her iki alan da parametreli.
func (q *Queries) CreateUserWithOptions(ctx context.Context, arg CreateUserWithOptionsParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithOptions,
		arg.OrganizationID,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :execrows
UPDATE users SET is_active = false WHERE id = $1 AND organization_id = $2
`

type DeactivateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateUser, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOnboardingGateStatus = `-- name: GetOnboardingGateStatus :one
SELECT u.must_change_password, o.onboarding_completed
FROM users u
JOIN organizations o ON o.id = u.organization_id
WHERE u.id = $1
`

type GetOnboardingGateStatusRow struct {
	MustChangePassword  bool `json:"must_change_password"`
	OnboardingCompleted bool `json:"onboarding_completed"`
}

// middleware.RequireOnboarded'ın her "business" istekte çağırdığı hafif
// sorgu -- must_change_password (users) VE onboarding_completed
// (organizations) TEK JOIN'le, iki ayrı PK üzerinden (hızlı). Yalnızca
// organization_id dolu (super_admin olmayan) kullanıcılar için çağrılır --
// super_admin bu JOIN'e hiç girmeden, rol kontrolüyle daha önce muaf
// tutulur.
func (q *Queries) GetOnboardingGateStatus(ctx context.Context, id pgtype.UUID) (GetOnboardingGateStatusRow, error) {
	row := q.db.QueryRow(ctx, getOnboardingGateStatus, id)
	var i GetOnboardingGateStatusRow
	err := row.Scan(&i.MustChangePassword, &i.OnboardingCompleted)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByIDInOrg = `-- name: GetUserByIDInOrg :one
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password FROM users WHERE id = $1 AND organization_id = $2
`

type GetUserByIDInOrgParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByIDInOrg(ctx context.Context, arg GetUserByIDInOrgParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDInOrg, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password FROM users
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.OrganizationID,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPasswordAndClearMustChange = `-- name: SetPasswordAndClearMustChange :execrows
UPDATE users SET password_hash = $3, must_change_password = false
WHERE id = $1 AND organization_id = $2
`

type SetPasswordAndClearMustChangeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PasswordHash   string      `json:"password_hash"`
}

// İlk giriş "şifre belirle" akışı: parolayı değiştirir VE
// must_change_password bayrağını temizler, tek sorguda.
func (q *Queries) SetPasswordAndClearMustChange(ctx context.Context, arg SetPasswordAndClearMustChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPasswordAndClearMustChange, arg.ID, arg.OrganizationID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $3, role = $4, is_active = $5
WHERE id = $1 AND organization_id = $2
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password
`

type UpdateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	FullName       string      `json:"full_name"`
	Role           string      `json:"role"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.OrganizationID,
		arg.FullName,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $3 WHERE id = $1 AND organization_id = $2
`

type UpdateUserPasswordParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PasswordHash   string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.OrganizationID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
