// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT count(*) FROM users WHERE organization_id = $1 AND is_active = true AND deleted_at IS NULL
`

func (q *Queries) CountActiveUsers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeletedUsers = `-- name: CountDeletedUsers :one
SELECT count(*) FROM users WHERE organization_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) CountDeletedUsers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDeletedUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE organization_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (organization_id, username, password_hash, full_name, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by
`

type CreateUserParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Username       string      `json:"username"`
	PasswordHash   string      `json:"password_hash"`
	FullName       string      `json:"full_name"`
	Role           string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrganizationID,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createUserWithOptions = `-- name: CreateUserWithOptions :one
INSERT INTO users (organization_id, username, password_hash, full_name, role, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by
`

type CreateUserWithOptionsParams struct {
	OrganizationID     pgtype.UUID `json:"organization_id"`
	Username           string      `json:"username"`
	PasswordHash       string      `json:"password_hash"`
	FullName           string      `json:"full_name"`
	Role               string      `json:"role"`
	MustChangePassword bool        `json:"must_change_password"`
}

// Platform seviyesi kullanıcı oluşturma (Super Admin CLI: organization_id
// NULL, role='super_admin') VE Super Admin'in yeni firma için provision
// ettiği ilk Owner (organization_id dolu, must_change_password=true) --
// CreateUser'ın aksine her iki alan da parametreli.
func (q *Queries) CreateUserWithOptions(ctx context.Context, arg CreateUserWithOptionsParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithOptions,
		arg.OrganizationID,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :execrows
UPDATE users SET is_active = false WHERE id = $1 AND organization_id = $2
`

type DeactivateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateUser, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOnboardingGateStatus = `-- name: GetOnboardingGateStatus :one
SELECT u.must_change_password, o.onboarding_completed,
       u.is_active, (u.deleted_at IS NOT NULL)::boolean AS user_deleted,
       u.role, u.organization_id
FROM users u
JOIN organizations o ON o.id = u.organization_id
WHERE u.id = $1
`

type GetOnboardingGateStatusRow struct {
	MustChangePassword  bool        `json:"must_change_password"`
	OnboardingCompleted bool        `json:"onboarding_completed"`
	IsActive            bool        `json:"is_active"`
	UserDeleted         bool        `json:"user_deleted"`
	Role                string      `json:"role"`
	OrganizationID      pgtype.UUID `json:"organization_id"`
}

// middleware.RequireOnboarded'ın her "business" istekte çağırdığı hafif
// sorgu -- must_change_password (users) VE onboarding_completed
// (organizations) TEK JOIN'le, iki ayrı PK üzerinden (hızlı). Yalnızca
// organization_id dolu (super_admin olmayan) kullanıcılar için çağrılır --
// super_admin bu JOIN'e hiç girmeden, rol kontrolüyle daha önce muaf
// tutulur.
//
// Aynı satırdan kullanıcının GÜNCEL durumu da okunur (is_active, silinme,
// kaba rol): access token 15 dakika geçerli ve rolü içinde taşıyor --
// pasifleştirilen ya da yetkisi düşürülen biri token'ın ömrü boyunca
// çalışmaya devam ediyordu. Ek sorgu yok, zaten okunan satır.
func (q *Queries) GetOnboardingGateStatus(ctx context.Context, id pgtype.UUID) (GetOnboardingGateStatusRow, error) {
	row := q.db.QueryRow(ctx, getOnboardingGateStatus, id)
	var i GetOnboardingGateStatusRow
	err := row.Scan(
		&i.MustChangePassword,
		&i.OnboardingCompleted,
		&i.IsActive,
		&i.UserDeleted,
		&i.Role,
		&i.OrganizationID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByIDInOrg = `-- name: GetUserByIDInOrg :one
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by FROM users WHERE id = $1 AND organization_id = $2
`

type GetUserByIDInOrgParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByIDInOrg(ctx context.Context, arg GetUserByIDInOrgParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDInOrg, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserGateStatus = `-- name: GetUserGateStatus :one
SELECT u.is_active, (u.deleted_at IS NOT NULL)::boolean AS user_deleted,
       u.role, u.organization_id
FROM users u
WHERE u.id = $1
`

type GetUserGateStatusRow struct {
	IsActive       bool        `json:"is_active"`
	UserDeleted    bool        `json:"user_deleted"`
	Role           string      `json:"role"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// RequireActiveUser'ın hafif okuması: requireOnboarded ALMAYAN uçlarda
// (onboarding, firma ayarları, ilk şifre, cihaz kaydı...) aynı "kullanıcı
// hâlâ aktif mi, rolü ne" kontrolü.
func (q *Queries) GetUserGateStatus(ctx context.Context, id pgtype.UUID) (GetUserGateStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserGateStatus, id)
	var i GetUserGateStatusRow
	err := row.Scan(
		&i.IsActive,
		&i.UserDeleted,
		&i.Role,
		&i.OrganizationID,
	)
	return i, err
}

const getUserWithOrganizationRole = `-- name: GetUserWithOrganizationRole :one
SELECT u.id, u.username, u.password_hash, u.full_name, u.role, u.is_active, u.created_at, u.updated_at, u.last_login_at, u.organization_id, u.must_change_password, u.organization_role_id, u.deleted_at, u.deleted_by, orole.code AS organization_role_code, orole.name AS organization_role_name,
       emp.id AS employee_id, emp.full_name AS employee_full_name, emp.is_active AS employee_is_active
FROM users u
LEFT JOIN organization_roles orole ON orole.id = u.organization_role_id
LEFT JOIN employees emp ON emp.user_id = u.id AND emp.organization_id = u.organization_id
WHERE u.id = $1 AND u.organization_id = $2
`

type GetUserWithOrganizationRoleParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetUserWithOrganizationRoleRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Username             string             `json:"username"`
	PasswordHash         string             `json:"password_hash"`
	FullName             string             `json:"full_name"`
	Role                 string             `json:"role"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	MustChangePassword   bool               `json:"must_change_password"`
	OrganizationRoleID   pgtype.UUID        `json:"organization_role_id"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy            pgtype.UUID        `json:"deleted_by"`
	OrganizationRoleCode *string            `json:"organization_role_code"`
	OrganizationRoleName *string            `json:"organization_role_name"`
	EmployeeID           pgtype.UUID        `json:"employee_id"`
	EmployeeFullName     *string            `json:"employee_full_name"`
	EmployeeIsActive     *bool              `json:"employee_is_active"`
}

// Bağlı personel kaydı ListUsersWithOrganizationRole ile aynı gerekçeyle.
func (q *Queries) GetUserWithOrganizationRole(ctx context.Context, arg GetUserWithOrganizationRoleParams) (GetUserWithOrganizationRoleRow, error) {
	row := q.db.QueryRow(ctx, getUserWithOrganizationRole, arg.ID, arg.OrganizationID)
	var i GetUserWithOrganizationRoleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.OrganizationRoleCode,
		&i.OrganizationRoleName,
		&i.EmployeeID,
		&i.EmployeeFullName,
		&i.EmployeeIsActive,
	)
	return i, err
}

const listDeletedUsersWithOrganizationRole = `-- name: ListDeletedUsersWithOrganizationRole :many
SELECT u.id, u.username, u.password_hash, u.full_name, u.role, u.is_active, u.created_at, u.updated_at, u.last_login_at, u.organization_id, u.must_change_password, u.organization_role_id, u.deleted_at, u.deleted_by, orole.code AS organization_role_code, orole.name AS organization_role_name
FROM users u
LEFT JOIN organization_roles orole ON orole.id = u.organization_role_id
WHERE u.organization_id = $1 AND u.deleted_at IS NOT NULL
ORDER BY u.deleted_at DESC
LIMIT $2 OFFSET $3
`

type ListDeletedUsersWithOrganizationRoleParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListDeletedUsersWithOrganizationRoleRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Username             string             `json:"username"`
	PasswordHash         string             `json:"password_hash"`
	FullName             string             `json:"full_name"`
	Role                 string             `json:"role"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	MustChangePassword   bool               `json:"must_change_password"`
	OrganizationRoleID   pgtype.UUID        `json:"organization_role_id"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy            pgtype.UUID        `json:"deleted_by"`
	OrganizationRoleCode *string            `json:"organization_role_code"`
	OrganizationRoleName *string            `json:"organization_role_name"`
}

// Süper Admin'in "Silinenler" (Arşiv) görünümü -- ListUsersWithOrganizationRole
// İLE AYNI şekil, yalnızca WHERE koşulu ters (deleted_at DOLU).
func (q *Queries) ListDeletedUsersWithOrganizationRole(ctx context.Context, arg ListDeletedUsersWithOrganizationRoleParams) ([]ListDeletedUsersWithOrganizationRoleRow, error) {
	rows, err := q.db.Query(ctx, listDeletedUsersWithOrganizationRole, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedUsersWithOrganizationRoleRow
	for rows.Next() {
		var i ListDeletedUsersWithOrganizationRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.OrganizationID,
			&i.MustChangePassword,
			&i.OrganizationRoleID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.OrganizationRoleCode,
			&i.OrganizationRoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by FROM users
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

// Silinmiş kullanıcılar normal listeden HER ZAMAN dışarıda kalır (bkz.
// migration 0043 başlık notu) -- ayrı bir "Silinenler" görünümü için
// ListDeletedUsersWithOrganizationRole kullanılır.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.OrganizationID,
			&i.MustChangePassword,
			&i.OrganizationRoleID,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithOrganizationRole = `-- name: ListUsersWithOrganizationRole :many
SELECT u.id, u.username, u.password_hash, u.full_name, u.role, u.is_active, u.created_at, u.updated_at, u.last_login_at, u.organization_id, u.must_change_password, u.organization_role_id, u.deleted_at, u.deleted_by, orole.code AS organization_role_code, orole.name AS organization_role_name,
       emp.id AS employee_id, emp.full_name AS employee_full_name, emp.is_active AS employee_is_active
FROM users u
LEFT JOIN organization_roles orole ON orole.id = u.organization_role_id
LEFT JOIN employees emp ON emp.user_id = u.id AND emp.organization_id = u.organization_id
WHERE u.organization_id = $1 AND u.deleted_at IS NULL
ORDER BY u.created_at DESC, u.id
LIMIT $2 OFFSET $3
`

type ListUsersWithOrganizationRoleParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListUsersWithOrganizationRoleRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Username             string             `json:"username"`
	PasswordHash         string             `json:"password_hash"`
	FullName             string             `json:"full_name"`
	Role                 string             `json:"role"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	MustChangePassword   bool               `json:"must_change_password"`
	OrganizationRoleID   pgtype.UUID        `json:"organization_role_id"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy            pgtype.UUID        `json:"deleted_by"`
	OrganizationRoleCode *string            `json:"organization_role_code"`
	OrganizationRoleName *string            `json:"organization_role_name"`
	EmployeeID           pgtype.UUID        `json:"employee_id"`
	EmployeeFullName     *string            `json:"employee_full_name"`
	EmployeeIsActive     *bool              `json:"employee_is_active"`
}

// "Kullanıcılar" ekranının RBAC/Project Membership sprint'iyle
// genişletilmiş listesi -- her kullanıcının organizasyon rol kodu/adı da
// AYNI sorguda (N+1 yok). super_admin bu listede HİÇ görünmez zaten
// (organization_id filtresiyle doğal olarak dışarıda kalır). Silinmiş
// kullanıcılar HER ZAMAN dışarıda -- bkz. ListDeletedUsersWithOrganizationRole.
//
// Bağlı personel kaydı (varsa) da aynı satırda: "kişi = tek kayıt"
// (bkz. queries/employees.sql) -- kullanıcı ekranı hesabın hangi
// personele bağlı olduğunu (ya da hiç bağlı olmadığını) gösterir. Bir hesap
// en fazla bir personele bağlanabildiği için (idx_employees_user_id) JOIN
// satır çoğaltmaz.
// id ikincil sıralama: aynı anda oluşturulmuş kullanıcılar (ör. toplu
// aktarım) sayfa sınırında iki sayfada birden görünmesin / kaybolmasın.
func (q *Queries) ListUsersWithOrganizationRole(ctx context.Context, arg ListUsersWithOrganizationRoleParams) ([]ListUsersWithOrganizationRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithOrganizationRole, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithOrganizationRoleRow
	for rows.Next() {
		var i ListUsersWithOrganizationRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.OrganizationID,
			&i.MustChangePassword,
			&i.OrganizationRoleID,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.OrganizationRoleCode,
			&i.OrganizationRoleName,
			&i.EmployeeID,
			&i.EmployeeFullName,
			&i.EmployeeIsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateUser = `-- name: ReactivateUser :execrows
UPDATE users SET is_active = true WHERE id = $1 AND organization_id = $2
`

type ReactivateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ReactivateUser(ctx context.Context, arg ReactivateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateUser, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetPasswordRequireChange = `-- name: ResetPasswordRequireChange :execrows
UPDATE users SET password_hash = $3, must_change_password = true
WHERE id = $1 AND organization_id = $2
`

type ResetPasswordRequireChangeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PasswordHash   string      `json:"password_hash"`
}

// Süper Admin'in geçici şifre yeniden vermesi: parola + must_change_password
// =true tek sorguda -- kullanıcı ilk girişte yeniden şifre belirlemek zorunda.
func (q *Queries) ResetPasswordRequireChange(ctx context.Context, arg ResetPasswordRequireChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetPasswordRequireChange, arg.ID, arg.OrganizationID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreUser = `-- name: RestoreUser :execrows
UPDATE users
SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NOT NULL
`

type RestoreUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Yalnızca silme durumunu geri alır -- is_active BİLİNÇLİ OLARAK
// dokunulmadan false kalır (bkz. service/user_lifecycle.go restoreUser
// yorumu): geri yüklenen kullanıcı "Pasif" olarak listeye döner, giriş
// erişimi AYRI ve açık bir "Aktifleştir" eylemiyle verilir.
func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreUser, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPasswordAndClearMustChange = `-- name: SetPasswordAndClearMustChange :execrows
UPDATE users SET password_hash = $3, must_change_password = false
WHERE id = $1 AND organization_id = $2 AND must_change_password = true
`

type SetPasswordAndClearMustChangeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PasswordHash   string      `json:"password_hash"`
}

// İlk giriş "şifre belirle" akışı: parolayı değiştirir VE
// must_change_password bayrağını temizler, tek sorguda. YALNIZCA bayrak
// açıkken: bu uç mevcut şifreyi sormaz -- bayrak koşulu olmasaydı açık
// oturumu olan herkes (ör. kilitlenmemiş bir telefon) şifreyi bilmeden
// değiştirebilirdi. 0 satır = bayrak kapalı (ya da kullanıcı yok).
func (q *Queries) SetPasswordAndClearMustChange(ctx context.Context, arg SetPasswordAndClearMustChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPasswordAndClearMustChange, arg.ID, arg.OrganizationID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserCoarseRole = `-- name: SetUserCoarseRole :exec
UPDATE users SET role = $3
WHERE id = $1 AND organization_id = $2 AND role <> 'super_admin'
`

type SetUserCoarseRoleParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Role           string      `json:"role"`
}

// Organizasyon rolü değiştiğinde kaba users.role'ü (requireAdmin kapısı ve
// web kabuğu seçimi hâlâ buna bakar) senkron tutar: owner/admin -> 'admin',
// diğerleri -> 'kullanici'. super_admin satırına ASLA dokunmaz.
func (q *Queries) SetUserCoarseRole(ctx context.Context, arg SetUserCoarseRoleParams) error {
	_, err := q.db.Exec(ctx, setUserCoarseRole, arg.ID, arg.OrganizationID, arg.Role)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = now(), deleted_by = $3, is_active = false
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	DeletedBy      pgtype.UUID `json:"deleted_by"`
}

// Yumuşak silme: is_active de AYNI anda false yapılır (bkz. migration
// 0043 başlık notu -- "silinmiş kullanıcı giriş yapamaz" garantisi
// HALİHAZIRDA var olan is_active kontrolünden bedava gelir). Zaten
// silinmiş bir satırda 0 satır günceller (idempotent-safe: servis
// katmanı bunu ErrAlreadyDeleted'e çevirir).
func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.OrganizationID, arg.DeletedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $3, role = $4, is_active = $5
WHERE id = $1 AND organization_id = $2
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by
`

type UpdateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	FullName       string      `json:"full_name"`
	Role           string      `json:"role"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.OrganizationID,
		arg.FullName,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $3 WHERE id = $1 AND organization_id = $2
`

type UpdateUserPasswordParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PasswordHash   string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.OrganizationID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = $3, is_active = $4
WHERE id = $1 AND organization_id = $2
RETURNING id, username, password_hash, full_name, role, is_active, created_at, updated_at, last_login_at, organization_id, must_change_password, organization_role_id, deleted_at, deleted_by
`

type UpdateUserProfileParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	FullName       string      `json:"full_name"`
	IsActive       bool        `json:"is_active"`
}

// Kullanıcının kendi organizasyon-rolünden BAĞIMSIZ profil alanları
// (ad soyad + aktiflik) -- kaba users.role BİLEREK burada DEĞİŞTİRİLMEZ:
// o alan artık organizasyon rolünden türetilir (bkz. setUserOrganizationRole/
// SetUserCoarseRole), bu uçtan bağımsız yazılırsa ikisi birbirinden
// sapar (requireAdmin kapısı ve /admin vs /panel kabuk seçimi bozulur).
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.OrganizationID,
		arg.FullName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.MustChangePassword,
		&i.OrganizationRoleID,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
